/**
 * Provenance — port of dev.ergenverse.runtime.delta.Provenance
 *
 * 'Where state came from', NOT ownership. The blueprint is NEVER modified;
 * every new save starts from identical canon; divergence lives in the
 * WorldDeltaStore journal.
 *
 *   CANON       — generated by the deterministic blueprint + terrain generator
 *   SIMULATION  — produced by autonomous systems (beasts, weather, sect growth)
 *   PLAYER      — produced by the player (first-class actor)
 *
 * Canon is reality. The 仙逆 novels are objective law, not inspiration.
 */
export enum Provenance {
  CANON = 'CANON',
  SIMULATION = 'SIMULATION',
  PLAYER = 'PLAYER',
}

export const PROVENANCE_PRIORITY: Record<Provenance, number> = {
  // Compose order: blueprint structures → sim changes → player changes.
  // Player wins, sim overrides canon, canon is the immutable base.
  CANON: 0,
  SIMULATION: 1,
  PLAYER: 2,
}
