package dev.ergenverse.cultivation;

import dev.ergenverse.perception.DivineSense;
import dev.ergenverse.perception.PerceptionTier;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.StringTag;
import net.minecraft.nbt.Tag;
import net.minecraftforge.common.util.INBTSerializable;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * The player's cultivation state — the complete record of their
 * progress along the Dao.
 *
 * <p><b>The Prime Directive:</b> reality is objective; cultivation changes
 * understanding, not existence. This state tracks what the cultivator
 * can perceive and interact with. It does not determine what exists in
 * the world.
 *
 * <h2>Design Principles</h2>
 * <ul>
 *   <li>Cultivation does NOT use XP. It uses events, comprehension, and
 *       tribulation.</li>
 *   <li>Breakthrough is EVENT-BASED. It requires: sufficient Qi +
 *       comprehension + tribulation survival.</li>
 *   <li>Every field carries meaning — no filler stats.</li>
 *   <li>Realm determines what you can perceive and interact with, NOT
 *       what exists.</li>
 * </ul>
 *
 * <h2>Fields and their meaning</h2>
 * <ul>
 *   <li><b>currentRealm</b> — position on the 18-step ladder. Determines
 *       perception tier, divine sense baseline, lifespan, and what
 *       breakthrough comes next.</li>
 *   <li><b>qi</b> — current Qi, normalized 0-1 against maxQi. This is
 *       spiritual energy in the meridians/dantian. Depleted by techniques,
 *       combat, breakthroughs. Regenerated by meditation, spirit stones,
 *       spirit veins.</li>
 *   <li><b>maxQi</b> — maximum Qi capacity. Grows with realm and blood
 *       refinement. A Qi Condensation cultivator holds far less than a
 *       Nascent Soul cultivator.</li>
 *   <li><b>divineSense</b> — normalized 0-1 measure of divine sense
 *       potency. Used with {@link DivineSense#soulPowerTotal} to compute
 *       actual S_sense. Rises through soul cultivation, soul-search
 *       methods, realm advancement.</li>
 *   <li><b>bloodRefinement</b> — body refinement progress 0-1. Affects
 *       maxQi, physical durability, and lifespan extension. In Renegade
 *       Immortal, Wang Lin's body cultivation was secondary but critical
 *       for survival at equal-realm encounters.</li>
 *   <li><b>karma</b> — karmic debt 0-1. Accumulates from killing,
 *       soul-searching, breaking formations, forbidden arts. High karma
 *       increases heart demon risk and can block breakthroughs entirely.
 *       In RI, karma was a real and dangerous force — not a mere number.</li>
 *   <li><b>breakthroughProgress</b> — 0-1 progress toward the NEXT
 *       breakthrough. This is NOT XP. It is a composite of events:
 *       meditation sessions, Dao insights, surviving tribulation stages,
 *       consuming rare herbs, receiving teachings. It represents
 *       readiness, not accumulation.</li>
 *   <li><b>tribulationPending</b> — whether Heaven has marked this
 *       cultivator for tribulation. Set to true when breakthroughProgress
 *       reaches 1.0 and all conditions are met. The tribulation must be
 *       faced before the breakthrough can complete.</li>
 *   <li><b>heartDemonRisk</b> — 0-1 risk of heart demon eruption during
 *       breakthrough. Computed from karma, past trauma, moral choices,
 *       and realm-specific factors. Nascent Soul and above have
 *       inherently higher risk.</li>
 *   <li><b>daoComprehension</b> — map of Dao path IDs to comprehension
 *       depth (0-1). A cultivator may understand multiple Daos but
 *       deeply comprehend only one or two. Breakthrough requires
 *       sufficient comprehension in at least one Dao.</li>
 *   <li><b>currentTechniques</b> — list of active technique IDs the
 *       cultivator has learned and can use.</li>
 *   <li><b>lifeForce</b> — remaining life force. Decreases with age
 *       (server tick time), can be extended by breakthroughs, certain
 *       herbs, and life-saving treasures. When it hits 0, the cultivator
 *       dies of old age — unless they find a way to extend their life.</li>
 *   <li><b>suppressionMultiplier</b> — 0-1 (default 1.0). Reduced by
 *       higher-realm cultivators' spiritual pressure. A suppressed
 *       cultivator operates at reduced capacity — Qi regeneration slows,
 *       techniques weaken, breakthrough becomes harder. In Er Gen,
 *       realm suppression was absolute: a Nascent Soul cultivator's
 *       pressure could prevent a Foundation cultivator from even
 *       standing.</li>
 * </ul>
 */
public class CultivationState implements INBTSerializable<CompoundTag> {

    // ─── NBT keys ─────────────────────────────────────────────────────
    private static final String TAG_REALM = "realm";
    private static final String TAG_QI = "qi";
    private static final String TAG_MAX_QI = "max_qi";
    private static final String TAG_DIVINE_SENSE = "divine_sense";
    private static final String TAG_BLOOD_REFINEMENT = "blood_refinement";
    private static final String TAG_KARMA = "karma";
    private static final String TAG_BREAKTHROUGH_PROGRESS = "breakthrough_progress";
    private static final String TAG_TRIBULATION_PENDING = "tribulation_pending";
    private static final String TAG_HEART_DEMON_RISK = "heart_demon_risk";
    private static final String TAG_DAO_COMPREHENSION = "dao_comprehension";
    private static final String TAG_CURRENT_TECHNIQUES = "current_techniques";
    private static final String TAG_LIFE_FORCE = "life_force";
    private static final String TAG_SUPPRESSION = "suppression_multiplier";
    private static final String TAG_ESSENCES = "essences_comprehended";
    private static final String TAG_SAMSARA_INCARNATIONS = "samsara_incarnations";
    private static final String TAG_NEXT_INCARNATION_ID = "next_incarnation_id";

    // ─── Breakthrough thresholds (Renegade Immortal canon) ───────────
    //
    // These are the minimum conditions to ATTEMPT a breakthrough.
    // The breakthrough itself still requires tribulation survival.
    //
    // Per RI: Wang Lin often broke through with barely-sufficient Qi
    // but deep comprehension. Comprehension matters more than raw power.

    /** Minimum Qi fraction (0-1 of maxQi) needed to attempt breakthrough. */
    private static final double QI_THRESHOLD = 0.80;

    /** Minimum average Dao comprehension (0-1) across all studied paths. */
    private static final double COMPREHENSION_THRESHOLDS_BASE = 0.30;

    /** Karma threshold above which breakthrough is blocked outright. */
    private static final double KARMA_HARD_BLOCK = 0.90;

    /** Karma threshold above which heart demon risk is significantly increased. */
    private static final double KARMA_HEART_DEMON_FLOOR = 0.50;

    /** Per-realm comprehension requirement modifiers. Higher realms need deeper understanding. */
    private static final Map<RealmId, Double> REALM_COMPREHENSION_MULTIPLIER;
    static {
        Map<RealmId, Double> m = new LinkedHashMap<>();
        m.put(RealmId.MORTAL, 0.5);             // Entering Qi Condensation: basic sensing
        m.put(RealmId.QI_CONDENSATION, 0.7);     // Foundation: understanding Qi flow
        m.put(RealmId.FOUNDATION, 0.8);          // Core Formation: condensing a core
        m.put(RealmId.CORE_FORMATION, 1.0);      // Nascent Soul: forming a soul
        m.put(RealmId.NASCENT_SOUL, 1.2);        // Soul Formation: soul cultivates independently
        m.put(RealmId.SOUL_FORMATION, 1.5);      // Soul Transformation: soul transforms the body
        m.put(RealmId.SOUL_TRANSFORMATION, 1.8); // Ascendant: body and soul merge
        m.put(RealmId.ASCENDANT, 2.0);           // Illusory Yin: yin-yang transition begins
        m.put(RealmId.ILLUSORY_YIN, 2.2);        // Corporeal Yang: yang body
        m.put(RealmId.CORPOREAL_YANG, 2.5);      // Nirvana Scryer: see the void
        m.put(RealmId.NIRVANA_SCRYER, 2.8);      // Nirvana Cleanser: purify
        m.put(RealmId.NIRVANA_CLEANSER, 3.0);    // Nirvana Fruit: shatter
        m.put(RealmId.NIRVANA_FRUIT, 3.5);       // Spirit Seizer: seize another's body
        m.put(RealmId.SPIRIT_SEIZER, 3.8);       // True Immortal: shed mortality
        m.put(RealmId.TRUE_IMMORTAL, 4.0);       // Ancient: aeons of cultivation
        m.put(RealmId.ANCIENT, 4.5);             // Paragon: beyond peers
        m.put(RealmId.PARAGON, 5.0);             // Transcendence: step beyond the world
        m.put(RealmId.TRANSCENDENCE, 0.0);       // No next realm
        REALM_COMPREHENSION_MULTIPLIER = Collections.unmodifiableMap(m);
    }

    /** Max Qi base values per realm. Modified by bloodRefinement. */
    private static final Map<RealmId, Double> REALM_MAX_QI_BASE;
    static {
        Map<RealmId, Double> m = new LinkedHashMap<>();
        m.put(RealmId.MORTAL, 10.0);
        m.put(RealmId.QI_CONDENSATION, 100.0);
        m.put(RealmId.FOUNDATION, 500.0);
        m.put(RealmId.CORE_FORMATION, 2000.0);
        m.put(RealmId.NASCENT_SOUL, 10000.0);
        m.put(RealmId.SOUL_FORMATION, 50000.0);
        m.put(RealmId.SOUL_TRANSFORMATION, 200000.0);
        m.put(RealmId.ASCENDANT, 1000000.0);
        m.put(RealmId.ILLUSORY_YIN, 5000000.0);
        m.put(RealmId.CORPOREAL_YANG, 20000000.0);
        m.put(RealmId.NIRVANA_SCRYER, 100000000.0);
        m.put(RealmId.NIRVANA_CLEANSER, 500000000.0);
        m.put(RealmId.NIRVANA_FRUIT, 2_000_000_000.0);
        m.put(RealmId.SPIRIT_SEIZER, 10_000_000_000.0);
        m.put(RealmId.TRUE_IMMORTAL, 100_000_000_000.0);
        m.put(RealmId.ANCIENT, 1_000_000_000_000.0);
        m.put(RealmId.PARAGON, 10_000_000_000_000.0);
        m.put(RealmId.TRANSCENDENCE, Double.MAX_VALUE);
        REALM_MAX_QI_BASE = Collections.unmodifiableMap(m);
    }

    // ─── State fields ─────────────────────────────────────────────────

    private RealmId currentRealm = RealmId.MORTAL;
    private double qi = 0.0;                  // 0-1 normalized against maxQi
    private double maxQi = REALM_MAX_QI_BASE.get(RealmId.MORTAL);
    private double divineSense = 0.0;         // 0-1 normalized
    private double bloodRefinement = 0.0;     // 0-1 normalized
    private double karma = 0.0;               // 0-1 normalized
    private double breakthroughProgress = 0.0; // 0-1
    private boolean tribulationPending = false;
    private double heartDemonRisk = 0.0;      // 0-1
    private final Map<String, Double> daoComprehension = new LinkedHashMap<>();
    private final List<String> currentTechniques = new ArrayList<>();
    private double lifeForce = RealmId.MORTAL.lifespan;
    private double suppressionMultiplier = 1.0; // 1.0 = no suppression, 0.0 = fully suppressed

    /** Tick counter for qi regeneration timing. */
    private int tickCounter = 0;

    /** The 14 Essences comprehension status (Samsara Dao). Index = taxonomyOrder - 1. */
    private final boolean[] essencesComprehended = new boolean[14];

    /**
     * Active Samsara Incarnations — fragments of the cultivator's soul living
     * other lives in other contexts. Canon: "One Billion Samsara Incarnations".
     * Each incarnation, when reabsorbed, grants Dao insight (essence comprehension).
     * Per the Prime Directive: each incarnation is REAL — it lives a full life.
     */
    private final List<dev.ergenverse.wanglin.SamsaraDao.SamsaraIncarnation> samsaraIncarnations = new ArrayList<>();

    /** Counter for generating unique incarnation IDs. */
    private int nextIncarnationId = 1;

    public CultivationState() {
        // Default: a mortal with no cultivation
        recalculateMaxQi();
    }

    // ─── Realm queries ────────────────────────────────────────────────

    public RealmId getCurrentRealm() { return currentRealm; }

    public void setCurrentRealm(RealmId realm) {
        this.currentRealm = realm;
        this.tribulationPending = false;
        this.breakthroughProgress = 0.0;
        recalculateMaxQi();
        recalculateLifeForce();
    }

    /** The perception tier derived from the current realm. */
    public PerceptionTier getPerceptionTier() {
        return PerceptionTier.fromRealm(currentRealm);
    }

    /**
     * Compute the divine sense radius in blocks using the anti-lag formula.
     *
     * <p>Uses the player's actual S_sense (derived from realm baseline,
     * divine sense potency, and any manual bonuses) with the logarithmic
     * radius formula from {@link DivineSense#radius}.
     *
     * @param worldLawTier the world's law tier at the player's location
     * @return radius in blocks
     */
    public int getDivineSenseRadius(int worldLawTier) {
        if (currentRealm == RealmId.MORTAL) return 4; // mortals have no divine sense
        long sSense = computeSSense();
        return DivineSense.radius(sSense, worldLawTier, 16);
    }

    /** Compute S_sense from realm baseline × divine sense potency. */
    public long computeSSense() {
        long sRealm = DivineSense.S_REALM.getOrDefault(currentRealm, 1L);
        // divineSense is 0-1; at 1.0, S_sense = S_realm × 2 (full potency)
        // At 0.0, S_sense = S_realm × 0.5 (half from realm alone, minimal cultivation)
        return Math.round(sRealm * (0.5 + divineSense * 1.5));
    }

    // ─── Qi management ────────────────────────────────────────────────

    public double getQi() { return qi; }
    public double getMaxQi() { return maxQi; }

    /** Get the absolute Qi amount (qi fraction × maxQi). */
    public double getAbsoluteQi() { return qi * maxQi; }

    /**
     * Consume Qi. Returns the amount actually consumed (may be less if
     * insufficient Qi).
     */
    public double consumeQi(double amount) {
        double absoluteAmount = amount; // amount is in absolute Qi units
        double available = qi * maxQi;
        if (absoluteAmount > available) {
            double consumed = available;
            qi = 0.0;
            return consumed;
        }
        qi = (available - absoluteAmount) / maxQi;
        return absoluteAmount;
    }

    /**
     * Add Qi (from meditation, spirit stones, spirit veins, etc.).
     * Capped at 1.0.
     */
    public void addQi(double absoluteAmount) {
        double current = qi * maxQi;
        double newAmount = Math.min(current + absoluteAmount, maxQi);
        qi = newAmount / maxQi;
    }

    // ─── Field accessors ──────────────────────────────────────────────

    public double getDivineSense() { return divineSense; }
    public void setDivineSense(double v) { this.divineSense = clamp01(v); }

    public double getBloodRefinement() { return bloodRefinement; }
    public void setBloodRefinement(double v) {
        this.bloodRefinement = clamp01(v);
        recalculateMaxQi(); // blood refinement increases max Qi
    }

    public double getKarma() { return karma; }
    public void addKarma(double amount) {
        this.karma = clamp01(this.karma + amount);
    }
    public void reduceKarma(double amount) {
        this.karma = clamp01(this.karma - amount);
    }

    public double getBreakthroughProgress() { return breakthroughProgress; }
    public void addBreakthroughProgress(double amount) {
        this.breakthroughProgress = clamp01(this.breakthroughProgress + amount);
        // When progress reaches 1.0 and conditions are met, tribulation is triggered
        if (this.breakthroughProgress >= 1.0 && canBreakthrough()) {
            this.tribulationPending = true;
        }
    }

    public boolean isTribulationPending() { return tribulationPending; }
    public void setTribulationPending(boolean v) { this.tribulationPending = v; }

    public double getHeartDemonRisk() { return heartDemonRisk; }
    public void setHeartDemonRisk(double v) { this.heartDemonRisk = clamp01(v); }

    public Map<String, Double> getDaoComprehension() { return Collections.unmodifiableMap(daoComprehension); }

    /** Get comprehension of a specific Dao path. Returns 0.0 if not studied. */
    public double getComprehension(String daoId) {
        return daoComprehension.getOrDefault(daoId, 0.0);
    }

    /** Add comprehension for a Dao path. */
    public void addComprehension(String daoId, double amount) {
        daoComprehension.merge(daoId, amount, (old, add) -> clamp01(old + add));
    }

    /** Set comprehension for a Dao path. */
    public void setComprehension(String daoId, double value) {
        daoComprehension.put(daoId, clamp01(value));
    }

    /** Get the highest comprehension across all studied Dao paths. */
    public double getHighestComprehension() {
        return daoComprehension.values().stream()
                .mapToDouble(Double::doubleValue)
                .max()
                .orElse(0.0);
    }

    /** Get the average comprehension across all studied Dao paths. */
    public double getAverageComprehension() {
        if (daoComprehension.isEmpty()) return 0.0;
        return daoComprehension.values().stream()
                .mapToDouble(Double::doubleValue)
                .average()
                .orElse(0.0);
    }

    public List<String> getCurrentTechniques() { return Collections.unmodifiableList(currentTechniques); }

    public boolean hasTechnique(String techniqueId) {
        return currentTechniques.contains(techniqueId);
    }

    public void addTechnique(String techniqueId) {
        if (!currentTechniques.contains(techniqueId)) {
            currentTechniques.add(techniqueId);
        }
    }

    public void removeTechnique(String techniqueId) {
        currentTechniques.remove(techniqueId);
    }

    public double getLifeForce() { return lifeForce; }
    public void setLifeForce(double v) { this.lifeForce = Math.max(0, v); }
    public void reduceLifeForce(double amount) { this.lifeForce = Math.max(0, lifeForce - amount); }

    public double getSuppressionMultiplier() { return suppressionMultiplier; }
    public void setSuppressionMultiplier(double v) {
        this.suppressionMultiplier = clamp01(v);
    }

    // ─── Breakthrough logic ───────────────────────────────────────────

    /**
     * Check whether the cultivator CAN attempt a breakthrough.
     *
     * <p>This checks prerequisites only — it does not perform the
     * breakthrough. A successful attempt still requires surviving
     * tribulation and heart demons.
     *
     * <p>Conditions (per Renegade Immortal canon):
     * <ol>
     *   <li>Not already at maximum realm (Transcendence).</li>
     *   <li>Qi ≥ 80% of maxQi (need energy for the transformation).</li>
     *   <li>Breakthrough progress ≥ 1.0 (events have prepared the way).</li>
     *   <li>Karma &lt; 0.90 (extreme karma blocks the path outright).</li>
     *   <li>At least one Dao path with sufficient comprehension for the
     *       target realm.</li>
     * </ol>
     *
     * @return true if all prerequisites are met
     */
    public boolean canBreakthrough() {
        RealmId next = currentRealm.next();
        if (next == null) return false;            // already at Transcendence
        if (qi < QI_THRESHOLD) return false;        // not enough Qi
        if (breakthroughProgress < 1.0) return false; // not enough preparation
        if (karma >= KARMA_HARD_BLOCK) return false;  // karma blocks the path
        if (getHighestComprehension() < requiredComprehension()) return false; // no Dao deep enough
        return true;
    }

    /**
     * Compute the comprehension threshold for the next realm.
     *
     * <p>Higher realms require deeper Dao understanding. The base
     * threshold is 0.30, multiplied by a realm-specific factor that
     * increases with each step.
     */
    public double requiredComprehension() {
        double multiplier = REALM_COMPREHENSION_MULTIPLIER.getOrDefault(currentRealm, 1.0);
        return Math.min(1.0, COMPREHENSION_THRESHOLDS_BASE * multiplier);
    }

    /**
     * Attempt a breakthrough to the next realm.
     *
     * <p>This method checks all prerequisites and evaluates the three
     * breakthrough risks in order:
     * <ol>
     *   <li><b>Karma check</b> — extreme karma blocks outright.</li>
     *   <li><b>Comprehension check</b> — insufficient comprehension fails.</li>
     *   <li><b>Heart demon roll</b> — based on karma + realm-specific factors.</li>
     *   <li><b>Tribulation</b> — flagged as pending. The actual tribulation
     *       is handled by {@link CultivationEvents} (lightning strikes,
     *       player damage). If the player survives, the breakthrough
     *       completes.</li>
     * </ol>
     *
     * <p>If all checks pass, tribulation is set to pending and the
     * caller must trigger the actual tribulation event.
     *
     * @param rng random source for heart demon / tribulation rolls
     * @return the breakthrough result
     */
    public BreakthroughResult attemptBreakthrough(java.util.Random rng) {
        RealmId next = currentRealm.next();
        if (next == null) {
            return new BreakthroughResult(
                    BreakthroughResult.Outcome.INSUFFICIENT_COMPREHENSION,
                    currentRealm, currentRealm,
                    "Already at the peak of Transcendence. There is no higher realm.");
        }

        // 1. Karma hard block
        if (karma >= KARMA_HARD_BLOCK) {
            return BreakthroughResult.karmaBlocked(currentRealm,
                    "Karmic debt weighs upon the heavenly path like a mountain. " +
                    "The tribulation would be ten times stronger. Settle your debts first.");
        }

        // 2. Comprehension check
        double reqComp = requiredComprehension();
        double highestComp = getHighestComprehension();
        if (highestComp < reqComp) {
            return BreakthroughResult.insufficientComprehension(currentRealm,
                    String.format("Dao comprehension (%.2f) below the threshold for %s (%.2f). " +
                    "Meditate more deeply on your Dao.",
                    highestComp, next.name, reqComp));
        }

        // 3. Qi check
        if (qi < QI_THRESHOLD) {
            return BreakthroughResult.failedTribulation(currentRealm,
                    String.format("Qi reserves (%.1f%%) insufficient for breakthrough. " +
                    "Need at least %.0f%%. Meditate near a spirit vein or consume spirit stones.",
                    qi * 100, QI_THRESHOLD * 100));
        }

        // 4. Heart demon risk
        double effectiveHeartDemonRisk = computeHeartDemonRisk();
        if (rng.nextDouble() < effectiveHeartDemonRisk) {
            // Heart demon erupts! Breakthrough fails. Karma increases.
            this.karma = clamp01(karma + 0.05);
            this.heartDemonRisk = clamp01(heartDemonRisk + 0.1);
            this.qi = Math.max(0, qi - 0.3); // significant Qi loss
            this.breakthroughProgress = Math.max(0, breakthroughProgress - 0.2);
            return BreakthroughResult.heartDemon(currentRealm,
                    String.format("At the critical moment, a heart demon erupted! " +
                    "Your karma (%.2f) fed the demon. Qi depleted, progress lost. " +
                    "Resolve your inner conflicts before trying again.", karma));
        }

        // 5. All checks passed — tribulation is now pending
        this.tribulationPending = true;
        return new BreakthroughResult(
                BreakthroughResult.Outcome.SUCCESS,
                currentRealm, next,
                "The heavens sense your audacity. Tribulation descends!");
        // NOTE: The actual realm change happens after tribulation survival,
        // handled by CultivationEvents.completeBreakthrough()
    }

    /**
     * Complete the breakthrough after tribulation survival.
     *
     * <p>Called by {@link CultivationEvents} after the player endures
     * the tribulation lightning. This actually changes the realm.
     *
     * @return the new realm, or null if no breakthrough was pending
     */
    public RealmId completeBreakthrough() {
        if (!tribulationPending) return null;
        RealmId next = currentRealm.next();
        if (next == null) return null;

        // Consume Qi for the transformation
        this.qi = 0.1; // left with 10% after the massive expenditure

        // Advance the realm
        setCurrentRealm(next);

        // Karma is partially cleansed by tribulation (Heaven's test burns karma)
        this.karma = clamp01(karma * 0.7);

        // Heart demon risk decreases with successful breakthrough
        this.heartDemonRisk = clamp01(heartDemonRisk * 0.5);

        // Divine sense grows with realm
        this.divineSense = clamp01(Math.max(divineSense, 0.3 + currentRealm.order * 0.04));

        this.tribulationPending = false;
        return next;
    }

    /**
     * Fail the breakthrough after tribulation kills the cultivator.
     *
     * <p>Qi is severely depleted, karma increases, progress is lost.
     * The cultivator survives but is weakened.
     */
    public void failBreakthrough() {
        this.qi = Math.max(0, qi - 0.5);
        this.karma = clamp01(karma + 0.03);
        this.breakthroughProgress = Math.max(0, breakthroughProgress - 0.3);
        this.heartDemonRisk = clamp01(heartDemonRisk + 0.05);
        this.tribulationPending = false;
    }

    /**
     * Compute the effective heart demon risk for the current breakthrough attempt.
     *
     * <p>Factors (per Renegade Immortal canon):
     * <ul>
     *   <li>Base karma contribution: karma ≥ 0.50 adds 0.1-0.4 risk</li>
     *   <li>Realm contribution: Nascent Soul+ adds inherent risk</li>
     *   <li>Existing heartDemonRisk: accumulates across failed attempts</li>
     * </ul>
     */
    private double computeHeartDemonRisk() {
        double risk = heartDemonRisk * 0.5; // persistent risk from past failures

        // Karma contribution
        if (karma >= KARMA_HEART_DEMON_FLOOR) {
            double karmaFactor = (karma - KARMA_HEART_DEMON_FLOOR) / (1.0 - KARMA_HEART_DEMON_FLOOR);
            risk += karmaFactor * 0.4;
        }

        // Realm contribution: higher realms have inherently more heart demon risk
        // Nascent Soul (order 4) and above
        if (currentRealm.order >= 4) {
            risk += 0.05 + (currentRealm.order - 4) * 0.02;
        }

        return Math.min(0.95, risk);
    }

    // ─── Internal calculations ────────────────────────────────────────

    /** Recalculate max Qi based on realm and blood refinement. */
    private void recalculateMaxQi() {
        double base = REALM_MAX_QI_BASE.getOrDefault(currentRealm, 10.0);
        // Blood refinement adds up to 50% more max Qi
        this.maxQi = base * (1.0 + bloodRefinement * 0.5);
        // Ensure qi doesn't exceed new max (fractional)
        this.qi = Math.min(qi, 1.0);
    }

    /** Recalculate life force ceiling based on current realm's lifespan. */
    private void recalculateLifeForce() {
        // If lifeForce was at or above the old realm's lifespan, raise it
        // to the new realm's lifespan (breakthrough extends life).
        this.lifeForce = currentRealm.lifespan;
    }

    // ─── Tick-based updates (called from CultivationEvents) ──────────

    /**
     * Per-tick update. Handles passive Qi regeneration and life force decay.
     *
     * <p>Qi regeneration rate depends on realm and suppression:
     * <ul>
     *   <li>Qi Condensation: very slow natural regen (0.0001/tick)</li>
     *   <li>Foundation: 0.0003/tick</li>
     *   <li>Higher realms: faster, but still meaningful</li>
     *   <li>Suppression reduces regen rate proportionally</li>
     * </ul>
     *
     * <p>Life force decays by 1 tick of the realm's lifespan per tick.
     * For a mortal (100-year lifespan = ~52,560,000 ticks), this is
     * negligible per tick but meaningful over time.
     */
    public void serverTick() {
        tickCounter++;

        // Qi regeneration (every 20 ticks = 1 second)
        if (tickCounter % 20 == 0 && qi < 1.0 && currentRealm != RealmId.MORTAL) {
            double baseRate = getQiRegenRatePerSecond();
            double effectiveRate = baseRate * suppressionMultiplier;
            addQiAbsoluteNormalized(effectiveRate);
        }

        // Life force decay (every 600 ticks = 30 seconds for efficiency)
        if (tickCounter % 600 == 0) {
            // Lose 30 seconds of life per 30-second check
            lifeForce = Math.max(0, lifeForce - 30.0);
        }
    }

    /**
     * Get the Qi regeneration rate per second as a fraction of maxQi.
     *
     * <p>In Er Gen, Qi regeneration is slow and deliberate. It's not a
     * rapid cooldown. Cultivators meditate for hours or days.
     */
    private double getQiRegenRatePerSecond() {
        return switch (currentRealm) {
            case MORTAL -> 0.0;             // mortals have no Qi to regenerate
            case QI_CONDENSATION -> 0.0001; // ~16 minutes to fully regen
            case FOUNDATION -> 0.0003;      // ~5.5 minutes
            case CORE_FORMATION -> 0.0005;  // ~3.3 minutes
            case NASCENT_SOUL -> 0.001;     // ~1.7 minutes
            case SOUL_FORMATION -> 0.002;   // ~50 seconds
            case SOUL_TRANSFORMATION -> 0.003; // ~33 seconds
            case ASCENDANT -> 0.005;        // ~20 seconds
            default -> 0.008;               // higher realms: ~12 seconds
        };
    }

    /** Add Qi as a fraction of maxQi. */
    private void addQiAbsoluteNormalized(double fraction) {
        qi = Math.min(1.0, qi + fraction);
    }

    // ─── NBT serialization ────────────────────────────────────────────

    @Override
    public CompoundTag serializeNBT() {
        CompoundTag tag = new CompoundTag();
        tag.putInt(TAG_REALM, currentRealm.order);
        tag.putDouble(TAG_QI, qi);
        tag.putDouble(TAG_MAX_QI, maxQi);
        tag.putDouble(TAG_DIVINE_SENSE, divineSense);
        tag.putDouble(TAG_BLOOD_REFINEMENT, bloodRefinement);
        tag.putDouble(TAG_KARMA, karma);
        tag.putDouble(TAG_BREAKTHROUGH_PROGRESS, breakthroughProgress);
        tag.putBoolean(TAG_TRIBULATION_PENDING, tribulationPending);
        tag.putDouble(TAG_HEART_DEMON_RISK, heartDemonRisk);
        tag.putDouble(TAG_LIFE_FORCE, lifeForce);
        tag.putDouble(TAG_SUPPRESSION, suppressionMultiplier);

        // Dao comprehension: each entry as "daoId:comprehension"
        CompoundTag daoTag = new CompoundTag();
        for (Map.Entry<String, Double> entry : daoComprehension.entrySet()) {
            daoTag.putDouble(entry.getKey(), entry.getValue());
        }
        tag.put(TAG_DAO_COMPREHENSION, daoTag);

        // Techniques: list of strings
        ListTag techList = new ListTag();
        for (String tech : currentTechniques) {
            techList.add(StringTag.valueOf(tech));
        }
        tag.put(TAG_CURRENT_TECHNIQUES, techList);

        // Essences: byte array (14 booleans)
        byte[] essenceBytes = new byte[14];
        for (int i = 0; i < 14; i++) essenceBytes[i] = (byte) (essencesComprehended[i] ? 1 : 0);
        tag.putByteArray(TAG_ESSENCES, essenceBytes);

        // Samsara Incarnations: list of compounds
        ListTag incList = new ListTag();
        for (dev.ergenverse.wanglin.SamsaraDao.SamsaraIncarnation inc : samsaraIncarnations) {
            CompoundTag incTag = new CompoundTag();
            incTag.putString("id", inc.id);
            incTag.putString("context_world", inc.contextWorld);
            incTag.putString("identity", inc.incarnationIdentity);
            incTag.putInt("lifespan_years", inc.lifespanYears);
            incTag.putBoolean("reabsorbed", inc.reabsorbed);
            if (inc.daoInsightGained != null) {
                incTag.putString("dao_insight", inc.daoInsightGained);
            }
            incList.add(incTag);
        }
        tag.put(TAG_SAMSARA_INCARNATIONS, incList);
        tag.putInt(TAG_NEXT_INCARNATION_ID, nextIncarnationId);

        return tag;
    }

    @Override
    public void deserializeNBT(CompoundTag tag) {
        this.currentRealm = RealmId.byOrder(tag.getInt(TAG_REALM));
        this.qi = tag.getDouble(TAG_QI);
        this.maxQi = tag.getDouble(TAG_MAX_QI);
        this.divineSense = tag.getDouble(TAG_DIVINE_SENSE);
        this.bloodRefinement = tag.getDouble(TAG_BLOOD_REFINEMENT);
        this.karma = tag.getDouble(TAG_KARMA);
        this.breakthroughProgress = tag.getDouble(TAG_BREAKTHROUGH_PROGRESS);
        this.tribulationPending = tag.getBoolean(TAG_TRIBULATION_PENDING);
        this.heartDemonRisk = tag.getDouble(TAG_HEART_DEMON_RISK);
        this.lifeForce = tag.getDouble(TAG_LIFE_FORCE);
        this.suppressionMultiplier = tag.getDouble(TAG_SUPPRESSION);

        // Dao comprehension
        this.daoComprehension.clear();
        if (tag.contains(TAG_DAO_COMPREHENSION, Tag.TAG_COMPOUND)) {
            CompoundTag daoTag = tag.getCompound(TAG_DAO_COMPREHENSION);
            for (String key : daoTag.getAllKeys()) {
                this.daoComprehension.put(key, daoTag.getDouble(key));
            }
        }

        // Techniques
        this.currentTechniques.clear();
        if (tag.contains(TAG_CURRENT_TECHNIQUES, Tag.TAG_LIST)) {
            ListTag techList = tag.getList(TAG_CURRENT_TECHNIQUES, Tag.TAG_STRING);
            for (int i = 0; i < techList.size(); i++) {
                this.currentTechniques.add(techList.getString(i));
            }
        }

        // Essences
        if (tag.contains(TAG_ESSENCES, Tag.TAG_BYTE_ARRAY)) {
            byte[] eb = tag.getByteArray(TAG_ESSENCES);
            for (int i = 0; i < Math.min(eb.length, 14); i++) {
                this.essencesComprehended[i] = eb[i] != 0;
            }
        }

        // Samsara Incarnations
        this.samsaraIncarnations.clear();
        if (tag.contains(TAG_SAMSARA_INCARNATIONS, Tag.TAG_LIST)) {
            ListTag incList = tag.getList(TAG_SAMSARA_INCARNATIONS, Tag.TAG_COMPOUND);
            for (int i = 0; i < incList.size(); i++) {
                CompoundTag incTag = incList.getCompound(i);
                String daoInsight = incTag.contains("dao_insight") ? incTag.getString("dao_insight") : null;
                this.samsaraIncarnations.add(new dev.ergenverse.wanglin.SamsaraDao.SamsaraIncarnation(
                        incTag.getString("id"),
                        incTag.getString("context_world"),
                        incTag.getString("identity"),
                        incTag.getInt("lifespan_years"),
                        incTag.getBoolean("reabsorbed"),
                        daoInsight
                ));
            }
        }
        this.nextIncarnationId = tag.getInt(TAG_NEXT_INCARNATION_ID);
        if (this.nextIncarnationId < 1) this.nextIncarnationId = 1;

        // Sanity: recalculate derived values
        recalculateMaxQi();
    }

    // ─── Essence tracking (Samsara Dao) ──────────────────────────────

    /**
     * Get the 14-element boolean array of comprehended Essences.
     * Index 0 = taxonomy order 1 (Metal), index 13 = order 14 (Reincarnation).
     */
    public boolean[] getEssencesComprehended() {
        return essencesComprehended;
    }

    /**
     * Mark an Essence as comprehended by taxonomy order (1-14).
     * @param taxonomyOrder the essence taxonomy order (1=Metal, ..., 14=Reincarnation)
     */
    public void comprehendEssence(int taxonomyOrder) {
        if (taxonomyOrder >= 1 && taxonomyOrder <= 14) {
            essencesComprehended[taxonomyOrder - 1] = true;
        }
    }

    /**
     * Check if the Heaven-Defying Bead is in the player's inventory.
     * V1: checks for the registered ergenverse item by registry key path.
     */
    public boolean hasHeavenDefyingBead(net.minecraft.world.entity.player.Inventory inv) {
        for (int i = 0; i < inv.getContainerSize(); i++) {
            net.minecraft.world.item.ItemStack stack = inv.getItem(i);
            if (!stack.isEmpty()) {
                net.minecraft.resources.ResourceLocation rl = net.minecraftforge.registries.ForgeRegistries.ITEMS.getKey(stack.getItem());
                if (rl != null && rl.getPath().contains("heaven_defying_bead")) {
                    return true;
                }
            }
        }
        return false;
    }

    // ─── Samsara Incarnation tracking ────────────────────────────────

    /**
     * Get all Samsara Incarnations (active and reabsorbed).
     */
    public List<dev.ergenverse.wanglin.SamsaraDao.SamsaraIncarnation> getSamsaraIncarnations() {
        return Collections.unmodifiableList(samsaraIncarnations);
    }

    /**
     * Get only the active (not-yet-reabsorbed) incarnations.
     */
    public List<dev.ergenverse.wanglin.SamsaraDao.SamsaraIncarnation> getActiveIncarnations() {
        List<dev.ergenverse.wanglin.SamsaraDao.SamsaraIncarnation> out = new ArrayList<>();
        for (var inc : samsaraIncarnations) {
            if (!inc.reabsorbed) out.add(inc);
        }
        return out;
    }

    /**
     * Count active (un-reabsorbed) incarnations.
     */
    public int countActiveIncarnations() {
        int n = 0;
        for (var inc : samsaraIncarnations) if (!inc.reabsorbed) n++;
        return n;
    }

    /**
     * Summon a new Samsara Incarnation — a soul-fragment sent to live another life.
     *
     * <p>Canon: "One Billion Samsara Incarnations" (一亿分身). Each incarnation
     * lives a complete life in a different context. When reabsorbed, the
     * experiences return as Dao insight.
     *
     * <p>Requirements (v1): Heaven-Defying Bead in inventory (soul-vessel).
     * Cost: 10% of current absolute Qi (soul-fragment creation).
     *
     * @param inv the player's inventory (for Heaven-Defying Bead check)
     * @return the new incarnation, or null if not eligible
     */
    public dev.ergenverse.wanglin.SamsaraDao.SamsaraIncarnation summonIncarnation(
            net.minecraft.world.entity.player.Inventory inv) {
        if (!hasHeavenDefyingBead(inv)) return null;
        // Cost: 10% of current absolute Qi
        double cost = getAbsoluteQi() * 0.10;
        if (cost < 1.0) return null; // need at least some Qi to split off a fragment
        consumeQi(cost);

        String id = "inc_" + nextIncarnationId++;
        // Pick a context world from the canon options (v1: rotation among known worlds)
        String[] contexts = {
            "Mortal Town (lifespan 80 yrs)", "Suzaku Tomb (lifespan 200 yrs)",
            "Foreign Battleground (lifespan 50 yrs)", "Spirit Beast Forest (lifespan 300 yrs)",
            "Ancient God Cave (lifespan 500 yrs)", "Reincarnation Pool Cycle (lifespan 1000 yrs)",
            "Blood Ancestor Realm (lifespan 400 yrs)", "Ji Realm Wasteland (lifespan 120 yrs)"
        };
        String[] identities = {
            "wandering scholar", "village blacksmith", "wandering cultivator",
            "mountain hermit", "river fisherman", "scholar-warrior",
            "bandit chieftain", "temple keeper", "court advisor", "merchant's son"
        };
        java.util.Random rng = new java.util.Random();
        String context = contexts[rng.nextInt(contexts.length)];
        String identity = identities[rng.nextInt(identities.length)];
        int lifespan = 50 + rng.nextInt(950);

        var inc = new dev.ergenverse.wanglin.SamsaraDao.SamsaraIncarnation(
                id, context, identity, lifespan, false, null);
        samsaraIncarnations.add(inc);
        return inc;
    }

    /**
     * Reabsorb (merge) an active incarnation. Returns its Dao insight, which
     * can be converted into essence comprehension via {@link #comprehendEssence}.
     *
     * <p>Canon: when Wang Lin reabsorbs an incarnation, he gains its lifetime
     * of insight. v1: each merge grants one essence comprehension (the next
     * uncomprehended essence in Wang Lin's completion order).
     *
     * @param id the incarnation ID
     * @return the granted essence, or null if not found / already reabsorbed
     */
    public dev.ergenverse.wanglin.SamsaraDao.Essence mergeIncarnation(String id) {
        for (int i = 0; i < samsaraIncarnations.size(); i++) {
            var inc = samsaraIncarnations.get(i);
            if (inc.id.equals(id) && !inc.reabsorbed) {
                // Find next uncomprehended essence in Wang Lin's completion order
                dev.ergenverse.wanglin.SamsaraDao.Essence granted = null;
                for (var e : dev.ergenverse.wanglin.SamsaraDao.WANG_LIN_COMPLETION_ORDER) {
                    if (!essencesComprehended[e.taxonomyOrder - 1]) {
                        granted = e;
                        break;
                    }
                }
                String insightStr = granted != null
                        ? "Comprehended " + granted.name + " Essence"
                        : "All 14 Essences already comprehended; insight became universal Dao clarity.";
                // Replace with reabsorbed version
                var reabsorbed = new dev.ergenverse.wanglin.SamsaraDao.SamsaraIncarnation(
                        inc.id, inc.contextWorld, inc.incarnationIdentity,
                        inc.lifespanYears, true, insightStr);
                samsaraIncarnations.set(i, reabsorbed);

                if (granted != null) {
                    comprehendEssence(granted.taxonomyOrder);
                }
                return granted;
            }
        }
        return null;
    }

    /**
     * Find an incarnation by ID. Returns null if not found.
     */
    public dev.ergenverse.wanglin.SamsaraDao.SamsaraIncarnation getIncarnation(String id) {
        for (var inc : samsaraIncarnations) {
            if (inc.id.equals(id)) return inc;
        }
        return null;
    }

    // ─── Utility ──────────────────────────────────────────────────────

    private static double clamp01(double v) {
        return Math.max(0.0, Math.min(1.0, v));
    }

    @Override
    public String toString() {
        return String.format("CultivationState{realm=%s, qi=%.2f/%.0f, divineSense=%.2f, " +
                "karma=%.2f, breakthrough=%.2f, lifeForce=%.0f}",
                currentRealm.name, qi, maxQi, divineSense,
                karma, breakthroughProgress, lifeForce);
    }
}