// src/lib/sim/bestiary-catalog.ts
// The full Er Gen bestiary — every creature is a REAL species from the novels.
// No procedural fillers. Compiled from: Renegade Immortal, Pursuit of Truth,
// ISSTH, A Will Eternal, AWWP, and Outside of Time wikis + novel knowledge.
//
// Sources: xian-ni.fandom.com, i-shall-seal-the-heavens.fandom.com,
// a-will-eternal.fandom.com, pursuit-of-the-truth-novel.fandom.com

import type { BeastSpecies, BeastDrop, BeastCategory, RealmId, BeastTier, HerbEnvironment } from './types';

type CatalogEntry = Omit<BeastSpecies, 'id' | 'populationStatus'>;
const d = (item: string, weight: number, count = '1', craftingUse?: string): BeastDrop => ({ item, weight, count, craftingUse });

// ═══════════════════════════════════════════════════════════════════════
// CATEGORY 1: Spatial & Cosmic Leviathans (19 species)
// ═══════════════════════════════════════════════════════════════════════
const SPATIAL_COSMIC: CatalogEntry[] = [
  { name: 'Mosquito Beast (Purple)', nameCn: '蚊兽(紫)', tier: 'demon', baseRank: 'ascendant', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: ['mosquito_beast_gold'], temperament: 'aggressive', innateTechnique: 'Soul-Pierce Proboscis', value: 'purple proboscis; swarm carapace', layer: 4, behaviorScript: 'Soul Drain Swarm — bypasses armor, targets Primordial Soul, duplicates if feeding. Wang Lin found the herd in the Sea of Devils.', voxelScale: '1.0×0.8×1.5 (swarm)', aggroType: 'Soul_Drain_Swarm', drops: [d('purple_proboscis', 0.4, '1-3', 'soul-piercing weapons'), d('swarm_carapace', 0.3)], category: 'spatial_cosmic_leviathan', novel: 'Renegade Immortal', destinedCompanion: true },
  { name: 'Mosquito Beast (Gold)', nameCn: '蚊兽(金)', tier: 'ancient', baseRank: 'true_immortal', habitat: 'void', diet: 'spiritivore', preysOn: ['mosquito_beast_purple'], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Golden Soul-Pierce', value: 'golden proboscis (transcendent weapon base)', layer: 4, behaviorScript: 'Enhanced Soul Drain — golden-rank; the king of the mosquito herd; +500% duplication', voxelScale: '1.5×1.0×2.0', aggroType: 'Soul_Drain_Swarm', drops: [d('golden_proboscis', 0.2, '1', 'transcendent soul-piercing weapon'), d('golden_carapace', 0.15)], category: 'spatial_cosmic_leviathan', novel: 'Renegade Immortal', destinedCompanion: true },
  { name: 'Nether Beast', nameCn: '冥兽', tier: 'ancient', baseRank: 'paragon', habitat: 'void', diet: 'cosmic', preysOn: ['moongazer_serpent'], preyedUponBy: [], temperament: 'passive_cataclysmic', value: 'Nether Core; Seven-Colored Realm Vault', layer: 4, behaviorScript: 'Universal Devourer — the strongest beast in the world; planet-sized; internal organs contain pocket dimensions', voxelScale: '10000³ (planet-sized)', aggroType: 'Passive_Cataclysmic', drops: [d('nether_core', 1.0), d('seven_colored_realm_vault', 0.3, '1', 'forbidden execution techniques')], category: 'spatial_cosmic_leviathan', novel: 'Renegade Immortal', gastroRealm: 'Nether Beast Interior — flesh + acid sub-dimension; cut through lining to escape' },
  { name: 'Thunder Beast', nameCn: '雷兽', tier: 'demon', baseRank: 'soul_formation', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Chain Lightning Discharge', value: 'thunder horn (lightning flying-sword catalyst); fulminant core', layer: 3, behaviorScript: 'Weather Dependent — made of pure lightning essence; grazes on tribulation clouds. Wang Lin companion archetype.', voxelScale: '3.5×4.0×5.5', aggroType: 'Weather_Dependent', drops: [d('silver_thunder_horn', 1.0, '1', 'top-tier Lightning Flying Sword catalyst'), d('fulminant_core', 0.35)], category: 'spatial_cosmic_leviathan', novel: 'Renegade Immortal', destinedCompanion: true },
  { name: 'Mountain-Sea Butterfly', nameCn: '山海蝶', tier: 'ancient', baseRank: 'paragon', bloodline: 'mountain-sea', habitat: 'void', diet: 'conceptual', preysOn: [], preyedUponBy: ['prime_kunpeng'], temperament: 'ancient_dormant', innateTechnique: 'Wing-Beat Storm', value: 'mountain-sea wing dust (5D folding); butterfly law fragment', layer: 5, behaviorScript: 'Reality Fracture Flap — from ISSTH; its wings carry entire chunk grids; gravity inverts, T_dilation 0.5→20.0', voxelScale: '5000×1200×8000', aggroType: 'Passive_Cataclysmic', drops: [d('mountain_sea_wing_dust', 1.0, '10-50', '5D spatial folding'), d('butterfly_law_fragment', 1.0)], category: 'spatial_cosmic_leviathan', novel: 'ISSTH' },
  { name: 'Moon-Swallowing Chimera', nameCn: '吞月兽', tier: 'ancient', baseRank: 'paragon', habitat: 'void', diet: 'cosmic', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Gravity Pull', value: 'moon-core essence; gravity manipulation fragment', layer: 4, behaviorScript: 'Continent Pull — from ISSTH; pulls continents across space layers', voxelScale: '2000×800×3000', aggroType: 'Passive_Cataclysmic', drops: [d('moon_core_essence', 0.3), d('gravity_fragment', 0.1, '1', 'gravity arrays')], category: 'spatial_cosmic_leviathan', novel: 'ISSTH' },
  { name: 'Prime Kunpeng', nameCn: '太古鲲鹏', tier: 'ancient', baseRank: 'transcendence', bloodline: 'kunpeng', habitat: 'void', diet: 'conceptual', preysOn: ['mountain_sea_butterfly', 'moongazer_serpent'], preyedUponBy: [], temperament: 'passive_cataclysmic', innateTechnique: 'Swallow-Heaven-and-Earth', value: 'primordial kunpeng bloodline source; Feather of the Nine Heavens', layer: 5, behaviorScript: 'Fluid-Expanse State Shift — Kun→Peng at Y=256; +400% speed; spatial-tearing attacks. From ISSTH.', voxelScale: 'Kun: 1200×800×6000 / Peng: 8000×3000×9000', aggroType: 'Transforming_Apex', drops: [d('primordial_kunpeng_bloodline_source', 1.0, '1', 'permanent aquatic↔spatial combat mode'), d('feather_of_the_nine_heavens', 1.0, '2-4')], category: 'spatial_cosmic_leviathan', novel: 'ISSTH', dualForm: { kun: 'Leviathan (aquatic)', peng: 'Titan Roc (spatial)' } },
  { name: 'Moongazer Serpent', nameCn: '望月', tier: 'ancient', baseRank: 'true_immortal', habitat: 'void', diet: 'cosmic', preysOn: [], preyedUponBy: ['nether_beast'], temperament: 'ancient_dormant', value: 'ancient god blood pool (+500 HP); moongazer skeletal core', layer: 4, behaviorScript: 'Deceptive Landmass — from Renegade Immortal; dormant body spans 2000×400×5000; civilizations build on its back', voxelScale: '2000×400×5000 (world-layer asset)', aggroType: 'Passive_Cataclysmic', drops: [d('ancient_god_blood_pool', 1.0, 'static', '+500 Max HP'), d('moongazer_skeletal_core', 1.0, '1', 'interstellar fortress frame')], category: 'spatial_cosmic_leviathan', novel: 'Renegade Immortal', gastroRealm: 'The Gastro-Realm — acid fluid + parasitic larvae sub-dimension' },
  { name: 'Patriarch Reliance Tortoise', nameCn: '巨龟', tier: 'ancient', baseRank: 'paragon', habitat: 'ocean', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'ancient_dormant', value: 'reliance shell (fortress-grade); ancient turtle inner dan', layer: 3, behaviorScript: 'Static Landmass — from A Will Eternal; Bai Xiaochun found this giant tortoise; rocky topography on shell', voxelScale: '3000×800×3000', aggroType: 'Passive_Cataclysmic', drops: [d('reliance_shell_plate', 0.5, '4-8', 'fortress defense'), d('ancient_turtle_inner_dan', 0.2, '1', 'Paragon breakthrough catalyst')], category: 'spatial_cosmic_leviathan', novel: 'A Will Eternal' },
  { name: 'Heavenhorn Ink Dragon', nameCn: '天角墨龙', tier: 'demon', baseRank: 'soul_formation', bloodline: 'dragon', habitat: 'ocean', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'heavenhorn ink dragon scale; dragon core', layer: 3, behaviorScript: 'Ink-Breath — from A Will Eternal; exhales ink that blinds divine sense; dragon-bloodline grants elemental resistance', voxelScale: '10×4×30', aggroType: 'Territorial_Blind', drops: [d('heavenhorn_dragon_scale', 0.4, '3-6', 'dragon-scale armor'), d('ink_dragon_core', 0.2, '1', 'dragon-bloodline refinement')], category: 'spatial_cosmic_leviathan', novel: 'A Will Eternal' },
  { name: 'Cosmic Devourer Whale', nameCn: '宇宙吞鲸', tier: 'demon', baseRank: 'soul_formation', habitat: 'void', diet: 'cosmic', preysOn: ['nebula_jellyfish'], preyedUponBy: [], temperament: 'passive_cataclysmic', value: 'cosmic bone marrow; star-anchor core', layer: 3, behaviorScript: 'Sector Roamer — ingests asteroid belts; stomach = instanced dungeon', voxelScale: '50×30×80', aggroType: 'Passive_Dungeon', drops: [d('cosmic_bone_marrow', 0.3), d('star_anchor_core', 0.2, '1', 'interstellar fortress')], category: 'spatial_cosmic_leviathan', novel: 'AWWP' },
  { name: 'Star-Swallowing Shadow Wolf', nameCn: '吞星影狼', tier: 'demon', baseRank: 'soul_formation', habitat: 'void', diet: 'cosmic', preysOn: ['starlight_moth'], preyedUponBy: [], temperament: 'cunning', value: 'void fur (stealth robes); shadow core', layer: 3, behaviorScript: 'Phase Blindness — invisible unless Divine Sense > 45000', voxelScale: '6.0×5.0×9.0', aggroType: 'Stealth_Pack', drops: [d('shadow_void_fur', 0.45, '6', 'stealth robes'), d('star_core_fragment', 0.2)], category: 'spatial_cosmic_leviathan', novel: 'AWWP' },
  { name: 'Spatial-Tear Centipede', nameCn: '裂空蜈蚣', tier: 'demon', baseRank: 'ascendant', habitat: 'void', diet: 'conceptual', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'void-severing claw', layer: 4, behaviorScript: 'Void Burrowing — burrows through void fabric; leaves unstable portals', voxelScale: '2.0×1.0×15.0', aggroType: 'Portal_Spawner', drops: [d('void_severing_claw', 0.4, '1', 'void-severing weapons')], category: 'spatial_cosmic_leviathan', novel: 'Renegade Immortal' },
  { name: 'Dead-Star Scavenger Crab', nameCn: '死星蟹', tier: 'ancient', baseRank: 'true_immortal', habitat: 'void', diet: 'cosmic', preysOn: [], preyedUponBy: [], temperament: 'territorial', value: 'neutron shell plates (near-invincible armor)', layer: 4, behaviorScript: 'Supernova Scavenger — feeds on supernova remnants; near-inpenetrable armor', voxelScale: '8.0×4.0×10.0', aggroType: 'Heavy_Defense', drops: [d('neutron_shell_plate', 0.5, '2-4', 'near-invincible armor')], category: 'spatial_cosmic_leviathan', novel: 'Beyond' },
  { name: 'Nebula Jellyfish', nameCn: '星云水母', tier: 'spirit', baseRank: 'nascent_soul', habitat: 'void', diet: 'cosmic', preysOn: [], preyedUponBy: ['cosmic_devourer_whale'], temperament: 'docile', value: 'nebular gel', layer: 3, behaviorScript: 'Passive Filter-Feeder — explodes into plasma field if agroed', voxelScale: '5.0×8.0×5.0', aggroType: 'Passive_Explosive', drops: [d('nebular_gel', 0.6, '1-2')], category: 'spatial_cosmic_leviathan', novel: 'AWWP' },
  { name: 'Starlight Moth', nameCn: '星尘蛾', tier: 'spirit', baseRank: 'nascent_soul', habitat: 'void', diet: 'cosmic', preysOn: [], preyedUponBy: ['star_swallowing_shadow_wolf'], temperament: 'docile', value: 'stardust filament (flight-gear crafting)', layer: 3, behaviorScript: 'Cosmic Drift Pollinator — feeds on planetary rings', voxelScale: '2.0×0.5×3.0', aggroType: 'Passive_Drift', drops: [d('stardust_filament', 0.5, '1-3', 'high-tier flight-gear')], category: 'spatial_cosmic_leviathan', novel: 'AWWP' },
  { name: 'Moon-Reflecting Crane', nameCn: '望月鹤', tier: 'demon', baseRank: 'soul_formation', habitat: 'void', diet: 'cosmic', preysOn: [], preyedUponBy: [], temperament: 'docile', value: 'astral feather (space-faring array component)', layer: 3, behaviorScript: 'Cosmic Migratory — teleports across planetary orbits during lunar alignments', voxelScale: '3.0×4.0×2.0', aggroType: 'Migratory', drops: [d('astral_feather', 0.3, '1-2', 'space-faring arrays')], category: 'spatial_cosmic_leviathan', novel: 'ISSTH' },
  { name: 'Void Leviathan', nameCn: '虚空巨兽', tier: 'ancient', baseRank: 'paragon', habitat: 'void', diet: 'cosmic', preysOn: [], preyedUponBy: [], temperament: 'passive_cataclysmic', value: 'void essence core; leviathan bone frame', layer: 4, behaviorScript: 'Void Drift — from ISSTH Vast Expanse; movement creates spatial distortions', voxelScale: '800×300×2000', aggroType: 'Passive_Cataclysmic', drops: [d('void_essence_core', 0.2, '1'), d('leviathan_bone_frame', 0.1, '1', 'void-vessel construction')], category: 'spatial_cosmic_leviathan', novel: 'ISSTH' },
  { name: 'Chaos Vortex Drake', nameCn: '混沌涡龙', tier: 'ancient', baseRank: 'transcendence', habitat: 'void', diet: 'conceptual', preysOn: [], preyedUponBy: [], temperament: 'passive_cataclysmic', value: 'chaos drake heart; vortex-manipulation core', layer: 5, behaviorScript: 'Chaos Vortex — from Beyond; its body IS a chaos vortex; only Source Energy damages it', voxelScale: 'galaxy-scale', aggroType: 'Passive_Cosmic', drops: [d('chaos_drake_heart', 0.1, '1', 'chaos-element weapon'), d('vortex_core', 0.1, '1', 'vortex manipulation')], category: 'spatial_cosmic_leviathan', novel: 'Beyond' },
];

// ═══════════════════════════════════════════════════════════════════════
// CATEGORY 2: Bloodline & Cultivation Mutants (41 species)
// All real creatures from the novels — no procedural fillers.
// ═══════════════════════════════════════════════════════════════════════
const BLOODLINE_MUTANT: CatalogEntry[] = [
  // Renegade Immortal (Layer 1-2)
  { name: 'Spirit Rabbit', nameCn: '灵兔', tier: 'normal', baseRank: 'mortal', habitat: 'forest', diet: 'herbivore', preysOn: [], preyedUponBy: ['spirit_fox', 'spirit_wolf'], temperament: 'docile', value: 'pelt; blood essence (Qi-gathering pill)', layer: 1, behaviorScript: 'Flee State — 2.5× speed away from SoulPower > 0', voxelScale: '0.5×0.4×0.6', aggroType: 'Passive_Flee', drops: [d('low_grade_pelt', 0.8), d('rabbit_blood_essence', 0.2, '1', 'Qi-gathering pill')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Cloud-Silk Deer', nameCn: '云丝鹿', tier: 'normal', baseRank: 'mortal', habitat: 'forest', diet: 'herbivore', preysOn: [], preyedUponBy: ['spirit_wolf'], temperament: 'docile', value: 'cloud-silk antlers (flying-sword hilts); bone marrow', layer: 1, behaviorScript: 'High-Qi Affinity — pathfinds toward highest Qi', voxelScale: '1.2×1.8×1.5', aggroType: 'Passive_Flee', drops: [d('cloud_silk_antler', 0.5, '2', 'flying-sword hilts'), d('spiritual_bone_marrow', 0.15)], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Spirit Fox', nameCn: '灵狐', tier: 'spirit', baseRank: 'qi_condensation', habitat: 'forest', diet: 'carnivore', preysOn: ['spirit_rabbit'], preyedUponBy: ['spirit_wolf'], temperament: 'cunning', innateTechnique: 'Illusionary-Smile', value: 'fox core; illusion catalyst', layer: 1, behaviorScript: 'Cunning Ambush — illusion misdirection + back-strike', voxelScale: '0.8×0.6×1.2', aggroType: 'Stealth_Ambush', drops: [d('fox_core', 0.3, '1', 'illusion-arts'), d('fox_pelt', 0.7)], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Spirit Wolf', nameCn: '灵狼', tier: 'spirit', baseRank: 'foundation', habitat: 'forest', diet: 'carnivore', preysOn: ['spirit_rabbit', 'cloud_silk_deer'], preyedUponBy: ['crimson_python'], temperament: 'territorial', innateTechnique: 'Moon-Howl Pack-Call', value: 'wolf core; fang-talisman', layer: 1, behaviorScript: 'Pack Packets — 3+ merge AI, stacking Bleeding', voxelScale: '1.0×1.1×1.6', aggroType: 'Pack_Hunter', drops: [d('wolf_fang', 0.7, '2-4', 'fang-talisman'), d('low_tier_core', 0.05)], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Fire Beast', nameCn: '火兽', tier: 'spirit', baseRank: 'foundation', habitat: 'desert', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Flame Burst', value: 'fire beast core; fire-aspect essence', layer: 2, behaviorScript: 'Pursuit — from RI; chased Wang Lin in his escape; relentless fire-trail pursuit', voxelScale: '1.5×1.0×2.5', aggroType: 'Pursuit_DoT', drops: [d('fire_beast_core', 0.4, '1', 'fire-aspect alchemy'), d('fire_essence', 0.3)], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Iron-Eating Beast', nameCn: '铁食兽', tier: 'spirit', baseRank: 'foundation', habitat: 'underground', diet: 'omnivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', value: 'iron essence; reinforced hide', layer: 2, behaviorScript: 'Ore Devourer — from RI; consumes ore veins; hide hardens with consumed metal', voxelScale: '1.0×0.8×1.5', aggroType: 'Heavy_Defense', drops: [d('iron_essence', 0.4, '2-4', 'metal-aspect crafting'), d('reinforced_hide', 0.3, '1', 'heavy armor')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Wind Spirit Beast', nameCn: '风灵兽', tier: 'spirit', baseRank: 'foundation', habitat: 'mountain', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'docile', innateTechnique: 'Wind Step', value: 'wind spirit core; wind-aspect essence', layer: 2, behaviorScript: 'Wind Glide — from RI; moves on wind currents; nearly untouchable by physical attacks', voxelScale: '0.8×0.6×1.2', aggroType: 'Passive_Evasion', drops: [d('wind_spirit_core', 0.3, '1', 'movement technique catalyst'), d('wind_essence', 0.3)], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Soul Beast', nameCn: '魂兽', tier: 'spirit', baseRank: 'core_formation', habitat: 'underground', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Soul Drain', value: 'soul beast core; soul essence', layer: 2, behaviorScript: 'Soul Feeder — from RI; drains divine sense; invisible to mortals; only Nascent Soul+ can perceive', voxelScale: '0.5×0.5×1.0 (ethereal)', aggroType: 'Soul_Drain', drops: [d('soul_beast_core', 0.3, '1', 'soul cultivation'), d('soul_essence', 0.2, '1', 'divine-sense expansion')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Cloud Beast', nameCn: '云兽', tier: 'spirit', baseRank: 'core_formation', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Cloud Form', value: 'cloud beast core; cloud-aspect essence', layer: 2, behaviorScript: 'Cloud Body — from RI; body made of cloud; physical attacks pass through; only Qi attacks damage', voxelScale: '2.0×2.0×3.0 (amorphous)', aggroType: 'Phase_Shift', drops: [d('cloud_beast_core', 0.3, '1'), d('cloud_essence', 0.2, '1', 'concealment techniques')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Crimson Python', nameCn: '绯红巨蟒', tier: 'spirit', baseRank: 'core_formation', habitat: 'mountain', diet: 'carnivore', preysOn: ['spirit_wolf'], preyedUponBy: ['thunder_hawk'], temperament: 'aggressive', innateTechnique: 'Constricting-Seal', value: 'python core (fire); gallbladder (qi-deviation stabilizer)', layer: 2, behaviorScript: 'Constriction Loop — wraps segments, locks movement, crushing DoT', voxelScale: '0.8×0.8×12.0', aggroType: 'Grapple_CC', drops: [d('python_leather', 0.85), d('python_gallbladder', 0.4, '1', 'qi-deviation stabilizer')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Silver-Horned Thunder Beast', nameCn: '银角雷兽', tier: 'spirit', baseRank: 'core_formation', habitat: 'mountain', diet: 'spiritivore', preysOn: ['spirit_wolf'], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Chain Lightning', value: 'silver thunder horn; fulminant core', layer: 2, behaviorScript: 'Weather Dependent — absorbs lightning; chain-arc at 100%. Wang Lin companion archetype.', voxelScale: '3.5×4.0×5.5', aggroType: 'Weather_Dependent', drops: [d('silver_thunder_horn', 1.0, '1', 'Lightning Flying Sword'), d('fulminant_core', 0.35)], category: 'bloodline_mutant', novel: 'Renegade Immortal', destinedCompanion: true },
  { name: 'Armored Earth-Bear', nameCn: '铁甲熊', tier: 'spirit', baseRank: 'core_formation', habitat: 'mountain', diet: 'omnivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Iron-Fur Ward', value: 'bear core (earth); hide (heavy-armor)', layer: 2, behaviorScript: 'Ground Slam — shockwaves + Stun', voxelScale: '2.5×2.5×3.5', aggroType: 'Territorial_CC', drops: [d('earthen_heartstone', 0.3), d('primal_bear_paw', 0.5, '2')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Abyssal Bone-Shark', nameCn: '深海骨鲨', tier: 'spirit', baseRank: 'nascent_soul', habitat: 'ocean', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'calcified jawbone; abyssal yin core', layer: 2, behaviorScript: 'Blood Scent Intercept — 256-block blood radius; +50% vs bleeding', voxelScale: '4.0×2.5×8.0', aggroType: 'Blood_Scent_Aggro', drops: [d('calcified_jawbone', 0.75, '2'), d('abyssal_yin_core', 0.3, '1', 'demonic refinement')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Thousand-Tentacle Sea King', nameCn: '千触海王', tier: 'demon', baseRank: 'nascent_soul', habitat: 'ocean', diet: 'spiritivore', preysOn: ['abyssal_bone_shark'], preyedUponBy: [], temperament: 'aggressive', value: 'Sea King Inner Dan (Soul Formation gate-breaker)', layer: 2, behaviorScript: 'Multi-Segment Boss — sever tentacles before core', voxelScale: '15×8×20', aggroType: 'Multi_Segment_Boss', drops: [d('sea_king_inner_dan', 1.0, '1', 'Soul Formation gate'), d('leviathan_crown', 0.5)], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Azure Dragon-Whelp', nameCn: '青龙幼', tier: 'demon', baseRank: 'nascent_soul', bloodline: 'dragon', habitat: 'ocean', diet: 'spiritivore', preysOn: ['crimson_python'], preyedUponBy: ['nine_tail_fox_matriarch'], temperament: 'cunning', innateTechnique: 'Dragon-Breath Tide', value: 'dragon core (premium); bloodline-essence', layer: 2, behaviorScript: 'Dragon-Breath — AoE elemental breath; dragon-blood scales resist elemental damage', voxelScale: '8.0×3.0×15.0', aggroType: 'Territorial_DoT', drops: [d('dragon_core', 0.3, '1', 'premium tier'), d('dragon_blood_essence', 0.2, '1', 'dao-fruit catalyst')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Nine-Tail Fox Matriarch', nameCn: '九尾狐祖', tier: 'demon', baseRank: 'soul_formation', bloodline: 'fox-ancient', habitat: 'forest', diet: 'spiritivore', preysOn: ['azure_dragon_whelp'], preyedUponBy: ['mountain_sea_butterfly'], temperament: 'cunning', innateTechnique: 'Nine-Tails Illusion Realm', value: 'matriarch soul bead (Soul Formation gate); primal fox tail hair', layer: 3, behaviorScript: 'Illusion Domain — 128-block Charm/Confusion; reverses controls; forces companions to attack you', voxelScale: '8.0×7.5×14.0', aggroType: 'Domain_CC', drops: [d('matriarch_soul_bead', 1.0, '1', 'Soul Formation gate'), d('primal_fox_tail_hair', 1.0, '9')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Savage Beast', nameCn: '蛮兽', tier: 'spirit', baseRank: 'foundation', habitat: 'forest', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'savage beast core; hardened bones', layer: 2, behaviorScript: 'Berserk Charge — from RI Sea of Devils; charges blindly; +50% damage when below 50% HP', voxelScale: '2.0×1.5×3.0', aggroType: 'Berserk_Charge', drops: [d('savage_beast_core', 0.3, '1'), d('hardened_bone', 0.5, '2-4', 'bone-weapons')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Blight-Weasel', nameCn: '瘟鼬', tier: 'normal', baseRank: 'qi_condensation', habitat: 'underground', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'blight sac; corrosive bile', layer: 1, behaviorScript: 'Toxic Spray — <30% HP → 5×5 poison cloud (Corrode_Qi)', voxelScale: '0.4×0.3×0.8', aggroType: 'Defensive_AoE', drops: [d('blight_sac', 0.9, '1', 'poison daggers')], category: 'bloodline_mutant', novel: 'Pursuit of Truth' },
  { name: 'Mist-Stalking Panther', nameCn: '雾影豹', tier: 'spirit', baseRank: 'qi_condensation', habitat: 'forest', diet: 'carnivore', preysOn: ['cloud_silk_deer'], preyedUponBy: ['crimson_python'], temperament: 'cunning', value: 'shadow essence; fangs', layer: 1, behaviorScript: 'Stealth Ambush — camouflage in grass; back-strike crit', voxelScale: '1.5×0.9×2.5', aggroType: 'Stealth_Ambush', drops: [d('shadow_essence', 0.25), d('panther_fangs', 0.6, '2')], category: 'bloodline_mutant', novel: 'A Will Eternal' },
  { name: 'Brocade Carp King', nameCn: '锦鲤王', tier: 'spirit', baseRank: 'qi_condensation', habitat: 'ocean', diet: 'omnivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', value: 'spiritual scale; water shard', layer: 1, behaviorScript: 'Stationary Ranged — water needles + knockback', voxelScale: '0.8×0.5×1.5', aggroType: 'Stationary_Ranged', drops: [d('spiritual_scale', 0.5), d('water_shard', 0.2)], category: 'bloodline_mutant', novel: 'A Will Eternal' },
  { name: 'Iron-Gale Boar', nameCn: '铁风猪', tier: 'spirit', baseRank: 'qi_condensation', habitat: 'forest', diet: 'omnivore', preysOn: [], preyedUponBy: ['mist_stalking_panther'], temperament: 'aggressive', value: 'reinforced tusk; beast meat', layer: 1, behaviorScript: 'Linear Charge — breaks guard if not dodged', voxelScale: '1.5×1.2×2.0', aggroType: 'Linear_Charge', drops: [d('boar_tusk', 0.6, '1', 'reinforced crafting'), d('beast_meat', 0.8, '2-3')], category: 'bloodline_mutant', novel: 'A Will Eternal' },
  // ISSTH (Layer 2-3)
  { name: 'Blood Mastiff', nameCn: '血獒', tier: 'spirit', baseRank: 'core_formation', habitat: 'forest', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'blood mastiff core; blood-aspect essence', layer: 2, behaviorScript: 'Blood Bond — from ISSTH; Meng Hao companion; loyal once bonded; blood-sense tracking', voxelScale: '1.5×1.2×2.5', aggroType: 'Loyal_Hunter', drops: [d('blood_mastiff_core', 0.3, '1', 'blood-aspect techniques'), d('mastiff_fang', 0.6, '2')], category: 'bloodline_mutant', novel: 'ISSTH', destinedCompanion: true },
  { name: 'Big Hairy', nameCn: '大毛', tier: 'spirit', baseRank: 'foundation', habitat: 'forest', diet: 'omnivore', preysOn: [], preyedUponBy: [], temperament: 'docile', value: 'hairy beast fur; inner dan', layer: 2, behaviorScript: 'Flee + Counter — from ISSTH; flees but counter-attacks with hair-needles when cornered', voxelScale: '1.0×0.8×1.5', aggroType: 'Flee_Counter', drops: [d('hairy_fur', 0.5, '1', 'concealment robes'), d('hairy_inner_dan', 0.2, '1')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Black Bat', nameCn: '黑蝠', tier: 'spirit', baseRank: 'foundation', habitat: 'underground', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'bat wing membrane; sonic gland', layer: 2, behaviorScript: 'Sonic Pulse — from ISSTH; emits sonic pulses that disrupt divine sense; swarm in dark caves', voxelScale: '0.5×0.2×0.8', aggroType: 'Sonic_Swarm', drops: [d('bat_wing_membrane', 0.4, '2-4', 'gliding arrays'), d('sonic_gland', 0.2, '1', 'divine-sense disruption')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Demonic Python', nameCn: '魔蟒', tier: 'spirit', baseRank: 'core_formation', habitat: 'mountain', diet: 'carnivore', preysOn: ['spirit_wolf'], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Demonic Coil', value: 'demonic python skin (sword-sheath material); inner dan', layer: 2, behaviorScript: 'Demonic Skin — from ISSTH; "A Sword Resting in Demonic Python Skin"; its skin is a top-tier sword sheath', voxelScale: '1.0×1.0×15.0', aggroType: 'Grapple_CC', drops: [d('demonic_python_skin', 0.4, '1', 'sword-sheath material'), d('python_inner_dan', 0.3, '1')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Nine-Headed Lion', nameCn: '九头狮', tier: 'demon', baseRank: 'soul_formation', bloodline: 'lion-ancient', habitat: 'mountain', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Nine-Roar Cascade', value: 'nine-headed lion mane; lion king inner dan', layer: 3, behaviorScript: 'Multi-Head Assault — from ISSTH; each head attacks independently; severing a head grows two more unless cauterized', voxelScale: '6.0×4.0×8.0', aggroType: 'Multi_Head', drops: [d('lion_mane', 0.4, '1-9', 'pride-based techniques'), d('lion_king_inner_dan', 0.2, '1', 'Soul Formation catalyst')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Whitebone Lily', nameCn: '白骨莲', tier: 'spirit', baseRank: 'core_formation', habitat: 'underground', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'cunning', value: 'whitebone lily seed; bone-aspect essence', layer: 2, behaviorScript: 'Bone Field — from ISSTH; a plant-beast hybrid; spreads bone-corrupting pollen; roots drain bone marrow', voxelScale: '1.0×1.5×1.0', aggroType: 'Stationary_Drain', drops: [d('whitebone_lily_seed', 0.3, '1', 'bone-cultivation catalyst'), d('bone_essence', 0.4, '1')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Blood Demon', nameCn: '血魔', tier: 'demon', baseRank: 'nascent_soul', habitat: 'underground', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Blood Mist', value: 'blood demon core; blood-aspect inheritance', layer: 2, behaviorScript: 'Blood Mist Form — from ISSTH; dissolves into blood mist; reforms behind target; immune to physical in mist form', voxelScale: '2.0×2.0×2.0 (amorphous)', aggroType: 'Phase_Shift', drops: [d('blood_demon_core', 0.3, '1', 'blood-aspect inheritance'), d('blood_mist_essence', 0.2, '1', 'mist-form technique')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Ghost Beast', nameCn: '鬼兽', tier: 'demon', baseRank: 'nascent_soul', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'ghost beast core; yin-aspect essence', layer: 3, behaviorScript: 'Ghost Form — from ISSTH Reincarnation Army; intangible; only soul-attacks damage; drains lifespan on touch', voxelScale: '2.0×1.0×3.0 (ethereal)', aggroType: 'Intangible_Drain', drops: [d('ghost_beast_core', 0.3, '1', 'yin-aspect alchemy'), d('lifespan_essence', 0.1, '1', 'lifespan restoration')], category: 'bloodline_mutant', novel: 'ISSTH' },
  // A Will Eternal (Layer 1-3)
  { name: 'Bruiser', nameCn: '彪', tier: 'spirit', baseRank: 'foundation', habitat: 'forest', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'bruiser core; beastbirth essence', layer: 1, behaviorScript: 'Beastbirth Loyal — from AWE; Bai Xiaochun companion; born from a Beastbirth Seed; fiercely loyal to creator', voxelScale: '2.0×1.5×3.0', aggroType: 'Loyal_Charge', drops: [d('bruiser_core', 0.3, '1', 'beastbirth catalyst'), d('beastbirth_essence', 0.2, '1', 'Beastbirth Seed crafting')], category: 'bloodline_mutant', novel: 'A Will Eternal', destinedCompanion: true },
  { name: 'Lord Turtle', nameCn: '龟爷', tier: 'spirit', baseRank: 'core_formation', habitat: 'ocean', diet: 'omnivore', preysOn: [], preyedUponBy: [], temperament: 'docile', value: 'turtle shell (heavy defense); turtle inner dan', layer: 2, behaviorScript: 'Shell Fortress — from AWE; Bai Xiaochun named it God of Beasts; retreats into indestructible shell', voxelScale: '3.0×1.5×3.0', aggroType: 'Defensive_Fortress', drops: [d('lord_turtle_shell', 0.3, '1-4', 'fortress-grade defense'), d('turtle_inner_dan', 0.2, '1')], category: 'bloodline_mutant', novel: 'A Will Eternal', destinedCompanion: true },
  { name: 'Thunder Chicken', nameCn: '雷鸡', tier: 'spirit', baseRank: 'foundation', habitat: 'mountain', diet: 'omnivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Thunder Cluck', value: 'thunder chicken feathers; thunder-claw essence', layer: 2, behaviorScript: 'Thunder Cluck — from AWE; Bai Xiaochun companion; emits AoE thunder-clap that stuns nearby entities', voxelScale: '0.8×0.6×1.0', aggroType: 'AoE_Stun', drops: [d('thunder_chicken_feather', 0.5, '4-8', 'thunder-talismans'), d('thunder_claw_essence', 0.2, '1', 'thunder technique')], category: 'bloodline_mutant', novel: 'A Will Eternal', destinedCompanion: true },
  { name: 'Spirit Pig', nameCn: '灵猪', tier: 'normal', baseRank: 'qi_condensation', habitat: 'forest', diet: 'omnivore', preysOn: [], preyedUponBy: ['spirit_wolf'], temperament: 'docile', value: 'spirit pork (Qi-restoring food); pig essence', layer: 1, behaviorScript: 'Growth Feeder — from AWE; Bai Xiaochun raises these; they convert herbs into Qi-rich meat', voxelScale: '1.0×0.8×1.5', aggroType: 'Passive_Flee', drops: [d('spirit_pork', 0.8, '2-4', 'Qi-restoring food buff'), d('pig_essence', 0.3, '1', 'body-tempering pill')], category: 'bloodline_mutant', novel: 'A Will Eternal' },
  { name: 'Old Monkey', nameCn: '老猿', tier: 'demon', baseRank: 'nascent_soul', habitat: 'mountain', diet: 'omnivore', preysOn: [], preyedUponBy: [], temperament: 'cunning', innateTechnique: 'Monkey Mimicry', value: 'monkey inner dan; mimic-essence', layer: 3, behaviorScript: 'Mimic — from AWE; copies the player technique back at them; high intelligence; can use tools', voxelScale: '1.5×1.0×1.0', aggroType: 'Mimic_Combatant', drops: [d('monkey_inner_dan', 0.3, '1'), d('mimic_essence', 0.2, '1', 'technique-copy catalyst')], category: 'bloodline_mutant', novel: 'A Will Eternal' },
  { name: 'Waterswamp Kingdom Beast', nameCn: '沼泽王国兽', tier: 'demon', baseRank: 'soul_formation', habitat: 'wetland', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Waterswamp Domain', value: 'waterswamp essence; composite beast core', layer: 3, behaviorScript: 'Composite Entity — from AWE; Bai Xiaochun life essence spirit; a fusion of thousands of swamp beasts; manifests different beast-forms from its mass', voxelScale: '10×5×10 (amorphous mass)', aggroType: 'Domain_Shifter', drops: [d('waterswamp_essence', 0.2, '1', 'life-essence refinement'), d('composite_beast_core', 0.1, '1', 'multi-form technique')], category: 'bloodline_mutant', novel: 'A Will Eternal', destinedCompanion: true },
  // Pursuit of Truth (Layer 1-3)
  { name: 'Berserker Beast', nameCn: '魔兽', tier: 'spirit', baseRank: 'foundation', habitat: 'mountain', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'berserker beast core; bloodline fragment', layer: 2, behaviorScript: 'Berserk Surge — from Pursuit of Truth; Su Ming world; activates bloodline surge at low HP; +100% attack, -50% defense', voxelScale: '2.0×1.5×3.0', aggroType: 'Berserk_Surge', drops: [d('berserker_beast_core', 0.3, '1', 'bloodline awakening catalyst'), d('bloodline_fragment', 0.1, '1', 'berserker bloodline')], category: 'bloodline_mutant', novel: 'Pursuit of Truth' },
  { name: 'Dark Mountain Beast', nameCn: '暗山兽', tier: 'spirit', baseRank: 'core_formation', habitat: 'mountain', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', value: 'dark mountain core; shadow-aspect essence', layer: 2, behaviorScript: 'Shadow Ambush — from Pursuit of Truth; Su Ming homeland; lurks in mountain shadows; strikes from above', voxelScale: '3.0×2.0×4.0', aggroType: 'Stealth_Ambush', drops: [d('dark_mountain_core', 0.3, '1', 'shadow techniques'), d('shadow_essence', 0.2, '1')], category: 'bloodline_mutant', novel: 'Pursuit of Truth' },
  { name: 'Fire Ape', nameCn: '火猿', tier: 'spirit', baseRank: 'core_formation', habitat: 'desert', diet: 'omnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Flame Fist', value: 'fire ape core; fire-aspect bloodline', layer: 2, behaviorScript: 'Flame Barrage — from Pursuit of Truth; flaming melee combos; throws fire-orbs', voxelScale: '1.5×1.2×2.0', aggroType: 'Aggressive_Melee', drops: [d('fire_ape_core', 0.3, '1', 'fire bloodline'), d('flame_fist_essence', 0.2, '1', 'body-tempering technique')], category: 'bloodline_mutant', novel: 'Pursuit of Truth' },
  { name: 'Su Ming Wolf', nameCn: '苏铭狼', tier: 'spirit', baseRank: 'foundation', habitat: 'tundra', diet: 'carnivore', preysOn: ['spirit_rabbit'], preyedUponBy: [], temperament: 'cunning', innateTechnique: 'Moonlit Hunt', value: 'wolf bloodline; moonlit essence', layer: 1, behaviorScript: 'Moonlit Pack — from Pursuit of Truth; Su Ming companion archetype; hunts under moonlight; +50% speed at night', voxelScale: '1.2×1.0×1.8', aggroType: 'Pack_Hunter', drops: [d('wolf_bloodline', 0.2, '1', 'berserker bloodline refinement'), d('moonlit_essence', 0.3, '1', 'night-technique catalyst')], category: 'bloodline_mutant', novel: 'Pursuit of Truth', destinedCompanion: true },
  // Additional Er Gen creatures (Layer 1-2 fill from various novels)
  { name: 'Blood-Flame Salamander', nameCn: '血火蝾螈', tier: 'spirit', baseRank: 'foundation', habitat: 'desert', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', value: 'volcanic core; fire-resistant hide', layer: 2, behaviorScript: 'Territorial DoT — magma-spit melts armor durability', voxelScale: '1.0×0.6×2.5', aggroType: 'Territorial_DoT', drops: [d('volcanic_core', 0.3), d('fire_hide', 0.5)], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Seven-Colored Phantom Butterfly', nameCn: '七彩幻蝶', tier: 'spirit', baseRank: 'core_formation', habitat: 'forest', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'cunning', value: 'phantasm dust; illusion wings', layer: 2, behaviorScript: 'Pollen Field — Confusion/Sleep/Poison + teleport', voxelScale: '0.3×0.1×0.5', aggroType: 'Status_Inflictor', drops: [d('phantasm_dust', 0.4), d('illusion_wings', 0.2)], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Ink-Shell Snapping Turtle', nameCn: '墨壳咬龟', tier: 'spirit', baseRank: 'foundation', habitat: 'ocean', diet: 'carnivore', preysOn: ['brocade_carp_king'], preyedUponBy: ['abyssal_bone_shark'], temperament: 'territorial', value: 'shell plates (heavy shield); ink essence', layer: 2, behaviorScript: 'Kinetic Anchoring — locks to bedrock; 75% top-damage reduction; ink blind', voxelScale: '2.5×1.5×2.8', aggroType: 'Defensive_Blind', drops: [d('ink_shell_plate', 0.6, '4', 'heavy shields'), d('black_ink_essence', 0.25)], category: 'bloodline_mutant', novel: 'A Will Eternal' },
  { name: 'Coral Dragon-Eel', nameCn: '珊瑚龙鳗', tier: 'spirit', baseRank: 'core_formation', habitat: 'ocean', diet: 'spiritivore', preysOn: [], preyedUponBy: ['abyssal_bone_shark'], temperament: 'aggressive', value: 'dragon-blood scale; bio-luminescent tendril', layer: 2, behaviorScript: 'Qi Drain Wrap — wraps target, drains Qi to self-heal', voxelScale: '0.5×0.5×4.0', aggroType: 'Grapple_Drain', drops: [d('dragon_blood_scale', 0.4), d('bio_tendril', 0.3)], category: 'bloodline_mutant', novel: 'A Will Eternal' },
  { name: 'Jian Feng (Blade-Beak)', nameCn: '剑锋鸟', tier: 'spirit', baseRank: 'core_formation', habitat: 'mountain', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'blade-beak (flying-sword entity); metallic feathers', layer: 2, behaviorScript: 'Flying Sword Avian — wings operate as flying sword entities; synchronized sword-light attacks', voxelScale: '2.0×1.5×3.0', aggroType: 'Aerial_Sword', drops: [d('blade_beak', 0.4, '1', 'flying-sword crafting'), d('metallic_feather', 0.5, '4-8', 'flying-sword arrays')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Nine-Feathered Crow', nameCn: '九羽乌', tier: 'spirit', baseRank: 'core_formation', habitat: 'mountain', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Nine-Feather Burning Aura', value: 'fire crow feathers; burning essence', layer: 2, behaviorScript: 'Burning Aura — radial burning status to all within radius; stacks per feather', voxelScale: '1.5×1.0×2.0', aggroType: 'Aura_DoT', drops: [d('nine_feather_crow_feather', 0.4, '3-9', 'fire-talisman'), d('burning_essence', 0.2)], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Blood-Glint Panther', nameCn: '血光豹', tier: 'spirit', baseRank: 'foundation', habitat: 'forest', diet: 'carnivore', preysOn: ['cloud_silk_deer'], preyedUponBy: ['crimson_python'], temperament: 'cunning', value: 'blood-glint essence; teleport shard', layer: 2, behaviorScript: 'Blink Strike — short-range teleportation dodge + repositioning', voxelScale: '1.8×1.0×3.0', aggroType: 'Stealth_Ambush', drops: [d('blood_glint_essence', 0.3, '1', 'movement techniques'), d('panther_claw', 0.6, '2')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Wind-Cutter Swallow', nameCn: '风刃燕', tier: 'spirit', baseRank: 'foundation', habitat: 'mountain', diet: 'carnivore', preysOn: ['spirit_rabbit'], preyedUponBy: [], temperament: 'aggressive', value: 'agility feather; wind talon shard', layer: 2, behaviorScript: 'Aerial Pack Hunter — groups of 3-5; synchronized dive-bomb', voxelScale: '0.5×0.2×0.8', aggroType: 'Pack_Hunter', drops: [d('agility_feather', 0.4, '2-3'), d('wind_talon_shard', 0.2)], category: 'bloodline_mutant', novel: 'Pursuit of Truth' },
  { name: 'Obsidian Earth-Mite', nameCn: '黑曜土虱', tier: 'spirit', baseRank: 'foundation', habitat: 'underground', diet: 'omnivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', value: 'obsidian ore; chitin shell', layer: 2, behaviorScript: 'Subterranean Miner — high physical defense; reflects 10% physical damage', voxelScale: '0.8×0.5×1.2', aggroType: 'Heavy_Defense', drops: [d('obsidian_ore', 0.5, '2-4'), d('chitin_shell_fragment', 0.4)], category: 'bloodline_mutant', novel: 'Pursuit of Truth' },
  { name: 'Frost-Mane Lion', nameCn: '冰鬃狮', tier: 'spirit', baseRank: 'core_formation', habitat: 'tundra', diet: 'carnivore', preysOn: ['spirit_wolf'], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Frost Roar', value: 'frost mane; ice core', layer: 2, behaviorScript: 'Frost Aura — slows all entities in radius; ice-breath line attack', voxelScale: '2.5×2.0×3.5', aggroType: 'Territorial_Aura', drops: [d('frost_mane', 0.4, '1', 'ice armor'), d('ice_core', 0.2)], category: 'bloodline_mutant', novel: 'Pursuit of Truth' },
  { name: 'Thunder-Hoof Stallion', nameCn: '雷蹄马', tier: 'spirit', baseRank: 'foundation', habitat: 'mountain', diet: 'herbivore', preysOn: [], preyedUponBy: [], temperament: 'docile', value: 'thunder-hoof (movement catalyst); lightning mane', layer: 2, behaviorScript: 'Lightning Dash — leaves lightning trails that shock pursuers', voxelScale: '2.0×2.0×3.0', aggroType: 'Passive_Flee', drops: [d('thunder_hoof', 0.3, '1', 'movement technique catalyst'), d('lightning_mane', 0.2)], category: 'bloodline_mutant', novel: 'AWWP', destinedCompanion: true },
  // Additional real Er Gen creatures from wiki research
  { name: 'Thunder Toad', nameCn: '雷蟾', tier: 'spirit', baseRank: 'core_formation', habitat: 'wetland', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Thunder Croak', value: 'thunder toad core; thunder-aspect skin', layer: 2, behaviorScript: 'Thunder Croak — from RI; Wang Lin companion; absorbs lightning + croaks a sonic-thunder AoE; evolves by absorbing spirit roots', voxelScale: '1.5×1.0×1.5', aggroType: 'AoE_Stun', drops: [d('thunder_toad_core', 0.4, '1', 'thunder-aspect alchemy'), d('thunder_toad_skin', 0.3, '1', 'lightning-resistant armor')], category: 'bloodline_mutant', novel: 'Renegade Immortal', destinedCompanion: true },
  { name: 'Heavenspan Divine Crocodile', nameCn: '天渊神鳄', tier: 'demon', baseRank: 'soul_formation', habitat: 'ocean', diet: 'carnivore', preysOn: ['abyssal_bone_shark'], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Divine Bite', value: 'divine crocodile core; heavenspan crocodile hide', layer: 3, behaviorScript: 'Beast King — from AWE; one of only 2 Beast Kings of the Lingxi Abyss; massive AoE bite + tail sweep', voxelScale: '20×5×15 (Beast King scale)', aggroType: 'Beast_King', drops: [d('divine_crocodile_core', 0.3, '1', 'Beast King refinement'), d('heavenspan_hide', 0.4, '1', 'Beast King armor')], category: 'bloodline_mutant', novel: 'A Will Eternal' },
  { name: 'Giant Toad Bi Di', nameCn: '巨蟾比迪', tier: 'demon', baseRank: 'nascent_soul', habitat: 'wetland', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Tongue Lash', value: 'king beast core; Bi Di tongue (whip weapon)', layer: 2, behaviorScript: 'King Beast — from AWE Lingxi Abyss; a King Beast with a natural bloodline; tongue-lash attacks pull players in', voxelScale: '8×4×8', aggroType: 'Grapple_Pull', drops: [d('king_beast_core', 0.3, '1', 'Beast King refinement'), d('bi_di_tongue', 0.2, '1', 'whip-weapon material')], category: 'bloodline_mutant', novel: 'A Will Eternal' },
  { name: 'Resurrection Lily', nameCn: '复活莲', tier: 'demon', baseRank: 'soul_formation', habitat: 'wetland', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'cunning', innateTechnique: 'Parasitic Root', value: 'resurrection lily seed; life-aspect essence', layer: 3, behaviorScript: 'Parasitic Plant-Beast — from ISSTH; attached to Meng Hao; drains life force while granting power; can resurrect its host at a cost', voxelScale: '2.0×0.5×2.0 (plant)', aggroType: 'Parasitic_Buff', drops: [d('resurrection_lily_seed', 0.1, '1', 'resurrection catalyst'), d('life_aspect_essence', 0.3, '1', 'life dao refinement')], category: 'bloodline_mutant', novel: 'ISSTH', destinedCompanion: true },
  { name: 'Dao Sprite', nameCn: '道灵', tier: 'demon', baseRank: 'nascent_soul', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'cunning', innateTechnique: 'Dao Mimicry', value: 'dao sprite core; dao fragment', layer: 3, behaviorScript: 'Dao Mimicry — from ISSTH; mimics the player\'s dao; creates a mirror-copy of the player\'s techniques', voxelScale: '1.0×1.0×1.0 (glowing orb)', aggroType: 'Mirror_Combatant', drops: [d('dao_sprite_core', 0.3, '1', 'dao-mimicry catalyst'), d('dao_fragment', 0.1, '1', 'technique creation')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Bronze Lamp Spirit', nameCn: '铜灯灵', tier: 'demon', baseRank: 'soul_formation', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'cunning', innateTechnique: 'Flame of Extinction', value: 'bronze lamp; extinction flame essence', layer: 3, behaviorScript: 'Extinction Flame — from ISSTH; a spirit bound to a bronze lamp; its flame can extinguish other cultivators\' techniques', voxelScale: '0.5×0.8×0.5 (lamp)', aggroType: 'Silence_Caster', drops: [d('bronze_lamp', 0.2, '1', 'technique-silencing artifact'), d('extinction_flame_essence', 0.1, '1', 'extinction-aspect weapon')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Big Toad', nameCn: '大蟾', tier: 'spirit', baseRank: 'core_formation', habitat: 'wetland', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Poison Breath', value: 'big toad core; poison gland', layer: 2, behaviorScript: 'Poison Fortress — from AWE; Bai Xiaochun companion archetype; sits on territory and breathes poison; belly stores items', voxelScale: '3.0×2.0×3.0', aggroType: 'Territorial_DoT', drops: [d('big_toad_core', 0.3, '1', 'poison-aspect alchemy'), d('toad_poison_gland', 0.4, '1', 'poison pill ingredient')], category: 'bloodline_mutant', novel: 'A Will Eternal', destinedCompanion: true },
  { name: 'Ghost King', nameCn: '鬼王', tier: 'demon', baseRank: 'nascent_soul', habitat: 'underground', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Ghost Domain', value: 'ghost king core; yin-aspect inner dan', layer: 2, behaviorScript: 'Ghost Domain — from AWE; rules over lesser ghosts; creates a yin-domain that drains Yang energy', voxelScale: '3.0×3.0×3.0 (ethereal)', aggroType: 'Domain_Drain', drops: [d('ghost_king_core', 0.3, '1', 'yin-aspect refinement'), d('ghost_king_inner_dan', 0.2, '1', 'soul cultivation')], category: 'bloodline_mutant', novel: 'A Will Eternal' },
  { name: 'Soul Dweller', nameCn: '魂居者', tier: 'demon', baseRank: 'nascent_soul', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'cunning', innateTechnique: 'Soul Possession', value: 'soul dweller core; possession essence', layer: 3, behaviorScript: 'Soul Possession — from AWE; can possess weaker cultivators and beasts; controls their body', voxelScale: '0.5×0.5×1.0 (ethereal)', aggroType: 'Possession', drops: [d('soul_dweller_core', 0.2, '1', 'possession technique catalyst'), d('possession_essence', 0.1, '1', 'soul control')], category: 'bloodline_mutant', novel: 'A Will Eternal' },
  { name: 'Parrot', nameCn: '鹦鹉', tier: 'spirit', baseRank: 'foundation', habitat: 'forest', diet: 'omnivore', preysOn: [], preyedUponBy: [], temperament: 'mischievous', innateTechnique: 'Mockery', value: 'parrot feather; mimic-essence', layer: 2, behaviorScript: 'Mockery — from ISSTH; Meng Hao companion; mocks enemies reducing their morale; copies speech; surprisingly useful in sect politics', voxelScale: '0.3×0.2×0.5', aggroType: 'Morale_Drain', drops: [d('parrot_feather', 0.4, '2-4', 'communication talisman'), d('mimic_essence', 0.2, '1', 'speech-copy technique')], category: 'bloodline_mutant', novel: 'ISSTH', destinedCompanion: true },
  { name: 'Qilin', nameCn: '麒麟', tier: 'demon', baseRank: 'soul_formation', bloodline: 'qilin', habitat: 'mountain', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Auspicious Aura', value: 'qilin scale; qilin inner dan; auspicious essence', layer: 3, behaviorScript: 'Auspicious Beast — from RI/ISSTH; a legendary auspicious beast; its presence boosts Qi density; inner dan is a top-tier refinement catalyst', voxelScale: '4.0×3.0×6.0', aggroType: 'Aura_Boost', drops: [d('qilin_scale', 0.3, '1-3', 'legendary armor'), d('qilin_inner_dan', 0.1, '1', 'top-tier refinement catalyst')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Phoenix', nameCn: '凤凰', tier: 'demon', baseRank: 'soul_formation', bloodline: 'phoenix', habitat: 'mountain', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Nirvana Rebirth', value: 'phoenix feather; phoenix bloodline essence; nirvana ash', layer: 3, behaviorScript: 'Nirvana Rebirth — from ISSTH; on death, revives from ashes at 50% power; fire-immune; phoenix feather = top-tier fire catalyst', voxelScale: '5.0×3.0×8.0', aggroType: 'Rebirth_Caster', drops: [d('phoenix_feather', 0.3, '3-7', 'fire flying-sword catalyst'), d('phoenix_bloodline_essence', 0.1, '1', 'fire bloodline refinement')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Underworld Beast', nameCn: '冥兽', tier: 'demon', baseRank: 'nascent_soul', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: ['nether_beast'], temperament: 'aggressive', value: 'underworld core; yin-aspect essence', layer: 3, behaviorScript: 'Underworld Pull — from RI; drags targets into an underworld pocket-dimension; yin-damage over time', voxelScale: '3.0×2.0×5.0', aggroType: 'Pocket_Dimension', drops: [d('underworld_core', 0.3, '1', 'yin refinement'), d('yin_essence', 0.2, '1', 'underworld arrays')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Flame Crow', nameCn: '火鸦', tier: 'spirit', baseRank: 'foundation', habitat: 'desert', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Flame Feather Rain', value: 'flame crow feather; fire essence', layer: 2, behaviorScript: 'Flame Feather Rain — from ISSTH/AWE; aerial fire bombardment; each feather ignites on impact', voxelScale: '0.8×0.5×1.2', aggroType: 'Aerial_DoT', drops: [d('flame_crow_feather', 0.5, '3-6', 'fire talisman material'), d('fire_essence', 0.3, '1')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Stone Lion', nameCn: '石狮', tier: 'spirit', baseRank: 'core_formation', habitat: 'mountain', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Stone Roar', value: 'stone lion core; stone-aspect hide', layer: 2, behaviorScript: 'Stone Fortress — from ISSTH; turns to stone on defense (immune to physical); stone roar paralyzes', voxelScale: '2.5×2.0×4.0', aggroType: 'Heavy_Defense', drops: [d('stone_lion_core', 0.3, '1', 'earth-aspect refinement'), d('stone_hide', 0.4, '1', 'stone armor')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Sea Dragon', nameCn: '海龙', tier: 'demon', baseRank: 'soul_formation', bloodline: 'dragon', habitat: 'ocean', diet: 'spiritivore', preysOn: ['coral_dragon_eel'], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Tidal Breath', value: 'sea dragon core; sea dragon scale; tidal essence', layer: 3, behaviorScript: 'Tidal Sovereign — from ISSTH/AWE; rules ocean regions; tidal breath creates whirlpools; dragon-bloodline grants elemental mastery', voxelScale: '15×5×40', aggroType: 'Territorial_DoT', drops: [d('sea_dragon_core', 0.2, '1', 'dragon refinement'), d('sea_dragon_scale', 0.4, '3-6', 'water-aspect armor'), d('tidal_essence', 0.2, '1', 'water dao catalyst')], category: 'bloodline_mutant', novel: 'A Will Eternal' },
  { name: 'Nightcrypt', nameCn: '夜墓', tier: 'demon', baseRank: 'nascent_soul', habitat: 'underground', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'cunning', innateTechnique: 'Nightcrypt Mist', value: 'nightcrypt mask; death-aspect essence', layer: 2, behaviorScript: 'Mist of Death — from AWE; Bai Xiaochun used the Nightcrypt identity; the mist drains life from all who breathe it', voxelScale: '2.0×2.0×2.0 (humanoid + mist)', aggroType: 'Aura_Drain', drops: [d('nightcrypt_mask', 0.2, '1', 'identity-concealment artifact'), d('death_aspect_essence', 0.3, '1', 'death dao refinement')], category: 'bloodline_mutant', novel: 'A Will Eternal' },
  { name: 'Heaven-Roaring Lion', nameCn: '啸天狮', tier: 'demon', baseRank: 'soul_formation', bloodline: 'lion-ancient', habitat: 'mountain', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Heaven-Roar', value: 'heaven-roar essence; lion king mane', layer: 3, behaviorScript: 'Heaven-Roar — from ISSTH/RI; a roar that shatters formations and stuns all cultivators below its realm within range', voxelScale: '5.0×3.0×7.0', aggroType: 'AoE_Stun', drops: [d('heaven_roar_essence', 0.3, '1', 'sonic-attack catalyst'), d('lion_king_mane', 0.4, '1', 'pride-based technique')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Greenwood Wolf', nameCn: '青木狼', tier: 'spirit', baseRank: 'foundation', habitat: 'forest', diet: 'carnivore', preysOn: ['spirit_rabbit', 'cloud_silk_deer'], preyedUponBy: ['crimson_python'], temperament: 'territorial', innateTechnique: 'Wood-Howl', value: 'greenwood wolf core; wood-aspect fur', layer: 1, behaviorScript: 'Wood Pack — from ISSTH; Big Hairy was a Greenwood Wolf; pack-hunting + wood-element healing aura', voxelScale: '1.2×1.0×1.8', aggroType: 'Pack_Hunter', drops: [d('greenwood_wolf_core', 0.3, '1', 'wood bloodline'), d('wood_fur', 0.4, '1-2', 'wood-aspect robe')], category: 'bloodline_mutant', novel: 'ISSTH', destinedCompanion: true },
  { name: 'Sword Spirit', nameCn: '剑灵', tier: 'demon', baseRank: 'nascent_soul', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'cunning', innateTechnique: 'Sword Rain', value: 'sword spirit core; sword-aspect fragment', layer: 3, behaviorScript: 'Sword Rain — from RI; a spirit born from a sword; controls all nearby weapons; rains sword-light', voxelScale: '1.0×0.5×1.0 (blade-shaped)', aggroType: 'Weapon_Control', drops: [d('sword_spirit_core', 0.2, '1', 'sword dao catalyst'), d('sword_aspect_fragment', 0.1, '1', 'sword technique creation')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  // ── Additional Er Gen creatures from deep wiki research (batch 2) ──
  { name: 'Cloud Sky Beast', nameCn: '云天兽', tier: 'spirit', baseRank: 'core_formation', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Cloud Devour', value: 'cloud sky core; cloud-aspect essence', layer: 2, behaviorScript: 'Cloud Body — from RI; Wang Lin sect area; body made of cloud; absorbs Qi attacks; can engulf entire areas', voxelScale: '5.0×5.0×5.0 (amorphous)', aggroType: 'Engulf', drops: [d('cloud_sky_core', 0.3, '1', 'cloud techniques'), d('cloud_essence', 0.2, '1', 'concealment')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Origin Soul Beast', nameCn: '本源兽', tier: 'demon', baseRank: 'nascent_soul', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Origin Devour', value: 'origin soul core; origin essence', layer: 3, behaviorScript: 'Origin Devour — from RI; feeds on origin energy; can strip a cultivator\'s origin soul if it lands a hit', voxelScale: '2.0×2.0×3.0 (ethereal)', aggroType: 'Soul_Drain', drops: [d('origin_soul_core', 0.2, '1', 'origin refinement'), d('origin_essence', 0.1, '1', 'dao-tier resource')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Five-Element Beast', nameCn: '五行兽', tier: 'demon', baseRank: 'soul_formation', habitat: 'mountain', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Five-Element Rotation', value: 'five-element core; element rotation essence', layer: 3, behaviorScript: 'Element Rotation — from RI; cycles through 5 elements (fire/water/wood/metal/earth); immune to the element it\'s currently cycling; weak to the opposing element', voxelScale: '4.0×3.0×5.0', aggroType: 'Element_Shift', drops: [d('five_element_core', 0.3, '1', 'five-element alchemy'), d('element_rotation_essence', 0.2, '1', 'element-shift technique')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Dream Beast', nameCn: '梦兽', tier: 'demon', baseRank: 'nascent_soul', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'cunning', innateTechnique: 'Dream Trap', value: 'dream core; dream-aspect essence', layer: 3, behaviorScript: 'Dream Trap — from RI/ISSTH; pulls targets into a dream-world; in the dream, the beast controls reality; escaping requires realizing you\'re dreaming', voxelScale: '2.0×1.0×3.0 (shifting)', aggroType: 'Dream_Trap', drops: [d('dream_core', 0.3, '1', 'illusion techniques'), d('dream_essence', 0.2, '1', 'dream dao catalyst')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Mountain-Goat Beast', nameCn: '山羚兽', tier: 'spirit', baseRank: 'foundation', habitat: 'mountain', diet: 'herbivore', preysOn: [], preyedUponBy: ['crimson_python', 'thunder_hawk'], temperament: 'territorial', innateTechnique: 'Mountain Charge', value: 'mountain-goat horn; earth essence', layer: 2, behaviorScript: 'Mountain Charge — from ISSTH; charges with earth-aspect horn; can shatter rock formations', voxelScale: '1.5×1.2×2.5', aggroType: 'Linear_Charge', drops: [d('mountain_goat_horn', 0.4, '1-2', 'earth weapon catalyst'), d('earth_essence', 0.3, '1')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Blood-Refinement Serpent', nameCn: '炼血蛇', tier: 'demon', baseRank: 'nascent_soul', habitat: 'underground', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Blood Refinement', value: 'blood-refinement core; blood serpent skin', layer: 3, behaviorScript: 'Blood Refinement — from RI; refines its own blood to increase power mid-combat; the longer the fight, the stronger it gets', voxelScale: '1.0×1.0×8.0', aggroType: 'Scaling_Combatant', drops: [d('blood_refinement_core', 0.3, '1', 'blood refinement technique'), d('blood_serpent_skin', 0.4, '1', 'blood-aspect armor')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Ice-Phoenix Whelp', nameCn: '冰凤幼', tier: 'demon', baseRank: 'soul_formation', bloodline: 'phoenix', habitat: 'tundra', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Ice-Rebirth', value: 'ice-phoenix feather; ice-phoenix bloodline essence', layer: 3, behaviorScript: 'Ice-Rebirth — from ISSTH; ice-variant phoenix; on death, rebirths from ice at 30% power; ice-immune', voxelScale: '3.0×2.0×5.0', aggroType: 'Rebirth_Caster', drops: [d('ice_phoenix_feather', 0.3, '3-5', 'ice flying-sword catalyst'), d('ice_phoenix_essence', 0.1, '1', 'ice bloodline')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Heaven-Devouring Beast', nameCn: '吞天兽', tier: 'ancient', baseRank: 'true_immortal', habitat: 'void', diet: 'cosmic', preysOn: [], preyedUponBy: [], temperament: 'passive_cataclysmic', innateTechnique: 'Heaven Devour', value: 'heaven-devouring core; cosmic essence', layer: 4, behaviorScript: 'Heaven Devour — from ISSTH; devours heavenly law itself; each bite weakens the local world-law permanently; extremely dangerous', voxelScale: '500×200×500', aggroType: 'Passive_Cataclysmic', drops: [d('heaven_devouring_core', 0.1, '1', 'law-weakening weapon'), d('cosmic_essence', 0.2, '1', 'cosmic cultivation')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Flame-Puppet Beast', nameCn: '焰傀兽', tier: 'spirit', baseRank: 'core_formation', habitat: 'desert', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'flame-puppet core; puppet-essence', layer: 2, behaviorScript: 'Puppet Body — from AWE; an alchemically created beast-puppet; body parts detach and fight independently; self-destructs on death', voxelScale: '2.0×2.0×3.0', aggroType: 'Swarm_SelfDestruct', drops: [d('flame_puppet_core', 0.3, '1', 'puppet crafting'), d('puppet_essence', 0.2, '1', 'construct creation')], category: 'alchemical_chimera', novel: 'A Will Eternal' },
  { name: 'Spirit-Devouring Vine', nameCn: '噬灵藤', tier: 'spirit', baseRank: 'foundation', habitat: 'forest', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Spirit Drain', value: 'spirit-devouring seed; vine fiber', layer: 1, behaviorScript: 'Ambush Vine — from ISSTH/RI; buries roots underground; drains Qi from anything that steps on it; grows larger with each drain', voxelScale: 'varies (starts 0.1×0.1×1.0)', aggroType: 'Ambush_Drain', drops: [d('spirit_devouring_seed', 0.2, '1', 'Qi-drain cultivation'), d('vine_fiber', 0.5, '3-6', 'rope/binding material')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Heaven-Roaring Crane', nameCn: '啸天鹤', tier: 'spirit', baseRank: 'core_formation', habitat: 'mountain', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Sonic Wing-Beat', value: 'crane feather; sonic essence', layer: 2, behaviorScript: 'Sonic Wing-Beat — from ISSTH; wing-beats produce sonic booms; shatters formations at close range', voxelScale: '2.0×3.0×2.0', aggroType: 'AoE_Sonic', drops: [d('crane_feather', 0.4, '3-5', 'flight-gear'), d('sonic_essence', 0.2, '1', 'sonic technique')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Black-Scaled Lizard', nameCn: '黑鳞蜥', tier: 'spirit', baseRank: 'foundation', habitat: 'desert', diet: 'carnivore', preysOn: [], preyedUponBy: ['blood_flame_salamander'], temperament: 'aggressive', value: 'black scale; lizard tail', layer: 2, behaviorScript: 'Tail Whip + Camouflage — from PoT; camouflages in desert; tail-whip stuns', voxelScale: '1.5×0.5×3.0', aggroType: 'Stealth_Ambush', drops: [d('black_scale', 0.5, '3-6', 'dark armor'), d('lizard_tail', 0.3, '1', 'flexible weapon')], category: 'bloodline_mutant', novel: 'Pursuit of Truth' },
  { name: 'Thunder-Winged Leopard', nameCn: '雷翅豹', tier: 'spirit', baseRank: 'core_formation', habitat: 'mountain', diet: 'carnivore', preysOn: ['spirit_wolf'], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Thunder-Wing Dash', value: 'thunder-wing essence; leopard core', layer: 2, behaviorScript: 'Thunder-Wing Dash — from RI/ISSTH; lightning-speed dash that leaves a thunder-trail; wing-claws shock on hit', voxelScale: '2.0×1.5×3.5', aggroType: 'Speed_Charge', drops: [d('thunder_wing_essence', 0.3, '1', 'movement technique'), d('leopard_core', 0.2, '1', 'lightning refinement')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Golden-Scaled Snake', nameCn: '金鳞蛇', tier: 'spirit', baseRank: 'core_formation', habitat: 'underground', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Golden Coil', value: 'golden scale; venom gland', layer: 2, behaviorScript: 'Golden Coil — from ISSTH; coils around target with golden-scaled body (nearly unbreakable); venom paralyzes', voxelScale: '0.5×0.5×6.0', aggroType: 'Grapple_CC', drops: [d('golden_scale', 0.4, '3-5', 'gold-grade armor'), d('venom_gland', 0.3, '1', 'poison pill')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Underworld River Beast', nameCn: '冥河兽', tier: 'demon', baseRank: 'ascendant', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Underworld River', value: 'underworld river core; death essence', layer: 4, behaviorScript: 'Underworld River — from RI; summons an underworld river that drags targets to the afterlife; those caught age rapidly', voxelScale: '10×3×20 (river form)', aggroType: 'Domain_Drain', drops: [d('underworld_river_core', 0.2, '1', 'death refinement'), d('death_essence', 0.3, '1', 'death dao')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Void-Ascendant Eagle', nameCn: '虚空鹰', tier: 'demon', baseRank: 'ascendant', habitat: 'void', diet: 'cosmic', preysOn: ['starlight_moth'], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Void Dive', value: 'void-eagle feather; void essence', layer: 4, behaviorScript: 'Void Dive — from ISSTH; dives through void dimensions; attacks from a dimension the target can\'t perceive', voxelScale: '5.0×3.0×8.0', aggroType: 'Dimensional_Strike', drops: [d('void_eagle_feather', 0.3, '3-5', 'void-flight gear'), d('void_essence', 0.2, '1', 'void dao')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Star-Fire Qilin', nameCn: '星火麒麟', tier: 'demon', baseRank: 'ascendant', bloodline: 'qilin', habitat: 'void', diet: 'cosmic', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Star-Fire Breath', value: 'star-fire qilin scale; star-fire essence', layer: 4, behaviorScript: 'Star-Fire Breath — from ISSTH; a qilin variant that breathes star-fire; its fire burns even in the void; auspicious presence boosts nearby Qi', voxelScale: '6.0×4.0×8.0', aggroType: 'Territorial_DoT', drops: [d('star_fire_qilin_scale', 0.3, '1-3', 'star-fire armor'), d('star_fire_essence', 0.2, '1', 'star-fire technique')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Blood-Rebirth Serpent', nameCn: '血涅蛇', tier: 'demon', baseRank: 'soul_formation', habitat: 'underground', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Blood Rebirth', value: 'blood-rebirth core; rebirth essence', layer: 3, behaviorScript: 'Blood Rebirth — from RI; on death, rebirths from its own blood at 50% power; the blood must be burned to prevent rebirth', voxelScale: '1.0×1.0×5.0', aggroType: 'Rebirth_Combatant', drops: [d('blood_rebirth_core', 0.2, '1', 'rebirth technique'), d('rebirth_essence', 0.1, '1', 'life refinement')], category: 'bloodline_mutant', novel: 'Renegade Immortal' },
  { name: 'Spirit-Mirror Butterfly', nameCn: '灵镜蝶', tier: 'spirit', baseRank: 'core_formation', habitat: 'forest', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'cunning', innateTechnique: 'Mirror Wing', value: 'mirror-wing dust; reflection essence', layer: 2, behaviorScript: 'Mirror Wing — from ISSTH; wing-scales act as mirrors; reflects techniques back at the caster; creates illusionary copies', voxelScale: '0.5×0.2×1.0', aggroType: 'Reflect_Illusion', drops: [d('mirror_wing_dust', 0.3, '1', 'reflection array'), d('reflection_essence', 0.2, '1', 'illusion technique')], category: 'bloodline_mutant', novel: 'ISSTH' },
  { name: 'Stone-Golem Tortoise', nameCn: '石傀龟', tier: 'spirit', baseRank: 'core_formation', habitat: 'mountain', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', innateTechnique: 'Stone Fortress', value: 'stone-golem shell; earth essence', layer: 2, behaviorScript: 'Living Fortress — from AWE; a tortoise with a golem-like stone shell; functions as a mobile fortress; allies can shelter inside', voxelScale: '5.0×3.0×5.0', aggroType: 'Mobile_Fortress', drops: [d('stone_golem_shell', 0.3, '1', 'fortress-grade defense'), d('earth_essence', 0.4, '1', 'earth refinement')], category: 'alchemical_chimera', novel: 'A Will Eternal' },
  // Outside of Time (BTT) — native fauna of the Wanggu world / God-Face-afflicted zones
  { name: 'Black-Scaled Wolf', nameCn: '黑鳞狼', tier: 'spirit', baseRank: 'foundation', habitat: 'forest', diet: 'carnivore', preysOn: ['spirit_rabbit'], preyedUponBy: [], temperament: 'aggressive', value: 'black-scale hide (Heterogeneity-resistant armor); wolf core', layer: 1, behaviorScript: 'Heterogeneity Host — from BTT; Black-Scaled Wolves in God-Face-afflicted regions may carry Grue-type entities in their shadow; the original host of the Mysterious Shadow before Xu Qing killed it; scales grant partial Heterogeneity resistance', voxelScale: '1.2×0.9×1.8', aggroType: 'Pack_Hunter', drops: [d('black_scale_hide', 0.4, '2-4', 'Heterogeneity-resistant armor'), d('wolf_core', 0.15, '1')], category: 'bloodline_mutant', novel: 'Outside of Time' },
  { name: 'Heterogeneity-Mutated Panther', nameCn: '异化豹', tier: 'spirit', baseRank: 'core_formation', habitat: 'forest', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'mutated pelt (Heterogeneity-laced); corrupted core', layer: 2, behaviorScript: 'Corrupted Predator — from BTT; a spirit beast exposed to concentrated Heterogeneity from God Face breath; lost original temperament, attacks indiscriminately; body partially crystallized with dark heterogeneity veins; stronger but mindless', voxelScale: '1.8×1.2×2.5', aggroType: 'Corrupted_Berserker', drops: [d('heterogeneity_pelt', 0.4, '1', 'forbidden armor (curses wearer)'), d('corrupted_core', 0.2, '1', 'Heterogeneity research')], category: 'bloodline_mutant', novel: 'Outside of Time' },
  { name: 'Ghostface Scorpion', nameCn: '鬼面蝎', tier: 'demon', baseRank: 'soul_formation', habitat: 'underground', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', innateTechnique: 'Ghostface Venom Sting', value: 'ghostface stinger (Xu Qing consumed vs Vajra Patriarch); venom sac; chitinous shell', layer: 2, behaviorScript: 'Venomous Ambush — from BTT; burrows in corrupted soil; stinger carries potent venom that damages soul force; Xu Qing consumed its tail as a one-time weapon against Vajra Ancestor', voxelScale: '0.8×0.6×2.5', aggroType: 'Poison_Ambush', drops: [d('ghostface_stinger', 0.2, '1', 'one-time soul-damage weapon'), d('ghostface_venom_sac', 0.3, '1', 'soul-damaging poison')], category: 'bloodline_mutant', novel: 'Outside of Time' },
];

// ═══════════════════════════════════════════════════════════════════════
// CATEGORY 3: Alchemical & Chimera Creations (28 species)
// All real creatures from the novels — artificial synthesis strains.
// ═══════════════════════════════════════════════════════════════════════
const ALCHEMICAL_CHIMERA: CatalogEntry[] = [
  { name: 'Gorging Crow', nameCn: '吞噬乌', tier: 'spirit', baseRank: 'qi_condensation', habitat: 'forest', diet: 'omnivore', preysOn: [], preyedUponBy: [], temperament: 'docile', value: 'regurgitates pure spirit-stone fragments from trash', layer: 1, behaviorScript: 'Trash Processor — from AWE; artificially bred; fed low-tier items, regurgitates pure spirit-stone fragments', voxelScale: '0.6×0.4×0.8', aggroType: 'Passive_Utility', drops: [d('spirit_stone_fragment', 0.8, '1-3', 'currency'), d('crow_feather', 0.5)], category: 'alchemical_chimera', novel: 'A Will Eternal', destinedCompanion: true },
  { name: 'Spirit-Weave Spider', nameCn: '灵蛛', tier: 'spirit', baseRank: 'foundation', habitat: 'underground', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'docile', value: 'spirit-weave silk (storage-bag primary component)', layer: 1, behaviorScript: 'Silk Production — from AWE; artificial arachnid; silk is primary component for storage-bag manufacturing', voxelScale: '0.5×0.3×0.8', aggroType: 'Passive_Utility', drops: [d('spirit_weave_silk', 0.7, '3-6', 'storage-bag manufacturing'), d('spider_venom', 0.3)], category: 'alchemical_chimera', novel: 'A Will Eternal' },
  { name: 'Pill-Furnace Toad', nameCn: '丹炉蟾', tier: 'spirit', baseRank: 'core_formation', habitat: 'wetland', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'docile', value: 'furnace-toad stomach (portable pill furnace); toad essence', layer: 2, behaviorScript: 'Living Furnace — from AWE/RI; Wang Lin pill-furnace toad archetype; its stomach IS a pill furnace; refines pills on the go if fed herbs', voxelScale: '1.5×1.0×1.5', aggroType: 'Passive_Utility', drops: [d('furnace_toad_stomach', 0.2, '1', 'portable pill furnace'), d('toad_essence', 0.5)], category: 'alchemical_chimera', novel: 'Renegade Immortal', destinedCompanion: true },
  { name: 'Flesh-Golem Centipede', nameCn: '肉傀蜈蚣', tier: 'spirit', baseRank: 'core_formation', habitat: 'underground', diet: 'carrion', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'golem core; flesh-array matrix', layer: 2, behaviorScript: 'Soul-Woven Construct — from AWE; created via soul-weaving; obeys creator; self-destructs on low HP', voxelScale: '1.0×0.8×8.0', aggroType: 'Construct_Loyal', drops: [d('golem_core', 0.4, '1', 'construct crafting'), d('flesh_array_matrix', 0.2)], category: 'alchemical_chimera', novel: 'A Will Eternal' },
  { name: 'Soul-Brand Hound', nameCn: '魂印犬', tier: 'spirit', baseRank: 'foundation', habitat: 'forest', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'soul-brand mark (loyalty-bond item)', layer: 2, behaviorScript: 'Soul-Branded Loyal — from RI; artificially bound to a master; tracks enemies across regions via soul-scent', voxelScale: '1.2×1.0×1.8', aggroType: 'Tracking_Hunter', drops: [d('soul_brand_mark', 0.3, '1', 'loyalty-bond item'), d('hound_fang', 0.6, '2')], category: 'alchemical_chimera', novel: 'Renegade Immortal' },
  { name: 'Blood-Essence Bat', nameCn: '血精蝠', tier: 'spirit', baseRank: 'qi_condensation', habitat: 'underground', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'blood-essence vial (bloodline-refinement ingredient)', layer: 1, behaviorScript: 'Mutation Swarm — from RI; artificially bred to produce blood-essence; swarms in groups', voxelScale: '0.3×0.2×0.5', aggroType: 'Swarm_Drain', drops: [d('blood_essence_vial', 0.3, '1', 'bloodline refinement'), d('bat_wing', 0.5, '3-5')], category: 'alchemical_chimera', novel: 'Renegade Immortal' },
  { name: 'Iron-Gator Chimera', nameCn: '铁鳄兽', tier: 'spirit', baseRank: 'foundation', habitat: 'wetland', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'territorial', value: 'iron-scale plates; array-script module', layer: 2, behaviorScript: 'Fusion Defender — from AWE; reptile + defensive array script; high armor; reflects scripted damage', voxelScale: '3.0×1.0×4.0', aggroType: 'Heavy_Defense', drops: [d('iron_scale_plate', 0.6, '2-4', 'heavy armor'), d('array_script_module', 0.2, '1', 'defensive array')], category: 'alchemical_chimera', novel: 'A Will Eternal' },
  { name: 'Poison-Fang Serpent', nameCn: '毒牙蛇', tier: 'spirit', baseRank: 'qi_condensation', habitat: 'wetland', diet: 'carnivore', preysOn: ['spirit_rabbit'], preyedUponBy: [], temperament: 'aggressive', value: 'poison fang; venom sac', layer: 1, behaviorScript: 'Mutation-Array Spawn — from PoT; artificially bred for venom; injects Corrode_Qi on bite', voxelScale: '0.3×0.2×2.0', aggroType: 'Poison_Bite', drops: [d('poison_fang', 0.5, '2', 'poison weapons'), d('venom_sac', 0.4, '1', 'poison pill ingredient')], category: 'alchemical_chimera', novel: 'Pursuit of Truth' },
  { name: 'Beastbirth Seed Entity', nameCn: '兽胎种', tier: 'spirit', baseRank: 'foundation', habitat: 'forest', diet: 'omnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'beastbirth seed (creates custom spirit beasts)', layer: 1, behaviorScript: 'Seed-Born — from AWE; Bai Xiaochun Bruiser origin; born from a Beastbirth Seed; takes traits from the seed donor', voxelScale: 'varies (inherits donor traits)', aggroType: 'Loyal_Charge', drops: [d('beastbirth_seed', 0.1, '1', 'creates custom spirit beasts'), d('beastbirth_essence', 0.3, '1', 'Beastbirth Seed crafting')], category: 'alchemical_chimera', novel: 'A Will Eternal' },
  { name: 'Mutated Spirit-Refinement Hound', nameCn: '炼灵犬', tier: 'spirit', baseRank: 'core_formation', habitat: 'underground', diet: 'carnivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'refinement core; spirit-enhanced fangs', layer: 2, behaviorScript: 'Spirit-Refined — from RI; Wang Lin refinement technique; enhanced with spirit-refinement arrays; +200% attack vs unrefined beasts', voxelScale: '1.5×1.2×2.0', aggroType: 'Enhanced_Hunter', drops: [d('refinement_core', 0.3, '1', 'spirit-refinement catalyst'), d('enhanced_fang', 0.5, '2', 'refined weapon material')], category: 'alchemical_chimera', novel: 'Renegade Immortal' },
];

// ═══════════════════════════════════════════════════════════════════════
// CATEGORY 4: Conceptual & Law-Bound Manifestations (15 species)
// All real entities from the novels — non-biological; born from shattered heavenly laws.
// ═══════════════════════════════════════════════════════════════════════
const CONCEPTUAL_LAW_BOUND: CatalogEntry[] = [
  // Outside of Time (BTT) — Grue-type entities born from Heterogeneity corruption
  { name: 'Mysterious Shadow', nameCn: '神秘诡影', tier: 'demon', baseRank: 'core_formation', habitat: 'void', diet: 'conceptual', preysOn: [], preyedUponBy: [], temperament: 'cunning', innateTechnique: 'Heterogeneity Devouring', value: 'shadow essence (grue-type evolution catalyst); devoured heterogeneity residue', layer: 2, behaviorScript: 'Grue Possession — from BTT; survives by possessing living beings via their shadow; devours Heterogeneity to evolve; grows Equivalent to Each Great Realm per evolution; most Grue-type creatures flee its devouring intent', voxelScale: 'humanoid shadow (amorphous)', aggroType: 'Shadow_Possession', drops: [d('shadow_essence', 0.3, '1', 'grue-type evolution catalyst'), d('heterogeneity_residue', 0.6, '1-3', 'Heterogeneity purification research')], category: 'conceptual_law_bound', novel: 'Outside of Time', destinedCompanion: true },
  { name: 'Heterogeneity Wraith', nameCn: '异化幽魂', tier: 'demon', baseRank: 'nascent_soul', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: ['mysterious_shadow'], temperament: 'aggressive', value: 'heterogeneity core (forbidden alchemy ingredient); corrupted soul fragment', layer: 2, behaviorScript: 'Mindless Corruption — from BTT; cultivator whose Heterogeneity accumulation exceeded threshold, transforming into a mindless alien beast; either explodes into blood mist or becomes this; aggressive, no cognition', voxelScale: 'humanoid (distorted)', aggroType: 'Corrupted_Berserker', drops: [d('heterogeneity_core', 0.3, '1', 'forbidden alchemy'), d('corrupted_soul_fragment', 0.5, '1-2', 'soul research')], category: 'conceptual_law_bound', novel: 'Outside of Time' },
  { name: 'God Face Fragment', nameCn: '神面碎片', tier: 'ancient', baseRank: 'paragon', habitat: 'void', diet: 'conceptual', preysOn: [], preyedUponBy: [], temperament: 'passive_cataclysmic', value: 'god-face shard (reproduces God Eye-Opening scene); divine remnant will', layer: 5, behaviorScript: 'Cataclysm Source — from BTT; a broken piece of the God Face that once opened its eyes; its breath pollutes psychic energy with Heterogeneity; when it opens its eyes, heterogeneity concentration spikes and nearby cultivators transform or die', voxelScale: 'mountain-scale stone face (partial)', aggroType: 'Passive_Cataclysmic', drops: [d('god_face_shard', 0.05, '1', 'reproduces Eye-Opening catastrophe'), d('divine_remnant_will', 0.02, '1', 'God State breakthrough material')], category: 'conceptual_law_bound', novel: 'Outside of Time' },
  { name: 'Time Echo Phantom', nameCn: '时间回声', tier: 'demon', baseRank: 'ascendant', habitat: 'void', diet: 'conceptual', preysOn: [], preyedUponBy: [], temperament: 'cunning', value: 'time-echo shard (time-dilation catalyst)', layer: 4, behaviorScript: 'Input Copy — from Beyond; copies player inputs with 3-second delay; forces tactical repositioning', voxelScale: 'humanoid (translucent)', aggroType: 'Mirror_Combatant', drops: [d('time_echo_shard', 0.3, '1', 'time-dilation catalyst')], category: 'conceptual_law_bound', novel: 'Beyond' },
  { name: 'Karmic Leech', nameCn: '业蛭', tier: 'demon', baseRank: 'ascendant', habitat: 'void', diet: 'conceptual', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'karmic silk', layer: 4, behaviorScript: 'Invisible Parasite — from ISSTH; latches onto high-Karmic_Stain characters; silently drains max Qi', voxelScale: 'microscopic', aggroType: 'Invisible_Drain', drops: [d('karmic_silk', 0.2, '1', 'karma arrays')], category: 'conceptual_law_bound', novel: 'ISSTH' },
  { name: 'Fiend-Gold Construct', nameCn: '魔金构', tier: 'demon', baseRank: 'soul_formation', habitat: 'underground', diet: 'conceptual', preysOn: [], preyedUponBy: [], temperament: 'territorial', value: 'fiend-gold ingot (construct crafting); law-fragment', layer: 3, behaviorScript: 'Living Metal Matrix — from RI; guards ancient inheritance ruins; immune to physical; only Divine Sense/law counters damage', voxelScale: '3.0×2.0×3.0 (metallic humanoid)', aggroType: 'Guardian_Immune', drops: [d('fiend_gold_ingot', 0.4, '1-2', 'construct crafting'), d('law_fragment', 0.1, '1', 'law technique')], category: 'conceptual_law_bound', novel: 'Renegade Immortal' },
  { name: 'Law-Shard Wraith', nameCn: '法碎幽魂', tier: 'demon', baseRank: 'nascent_soul', habitat: 'void', diet: 'conceptual', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'law-shard fragment (technique-creation catalyst)', layer: 3, behaviorScript: 'Law Manifestation — from ISSTH; born from shattered heavenly law; immune to non-matching elements; only countered by opposing law', voxelScale: '2.0×0.5×2.0 (ethereal)', aggroType: 'Law_Immune', drops: [d('law_shard_fragment', 0.3, '1', 'technique creation')], category: 'conceptual_law_bound', novel: 'ISSTH' },
  { name: 'Karma-Eating Grub', nameCn: '噬业蛆', tier: 'demon', baseRank: 'ascendant', habitat: 'void', diet: 'conceptual', preysOn: [], preyedUponBy: [], temperament: 'passive_cataclysmic', value: 'karmic silk', layer: 4, behaviorScript: 'Karma Feed — from ISSTH; feeds on player Karma; hits reduce reputation or increase tribulation', voxelScale: '0.5×0.3×1.0', aggroType: 'Karmic_Drain', drops: [d('karmic_silk', 0.3, '1', 'karma arrays')], category: 'conceptual_law_bound', novel: 'ISSTH' },
  { name: 'Fate-Thread Weaver', nameCn: '命线蛛', tier: 'ancient', baseRank: 'paragon', habitat: 'void', diet: 'conceptual', preysOn: [], preyedUponBy: [], temperament: 'passive_cataclysmic', value: 'fate-thread silk (permanently alters destiny)', layer: 5, behaviorScript: 'Fate Manipulation — from Beyond; weaves fate-strings; damaging the web permanently alters destiny values', voxelScale: 'galaxy-scale', aggroType: 'Passive_Cosmic', drops: [d('fate_thread_silk', 0.05, '1', 'alters destiny')], category: 'conceptual_law_bound', novel: 'Beyond' },
  { name: 'Chaos-Origin Behemoth', nameCn: '混沌巨兽', tier: 'ancient', baseRank: 'transcendence', habitat: 'void', diet: 'conceptual', preysOn: [], preyedUponBy: [], temperament: 'passive_cataclysmic', value: 'chaos essence (Source Energy weapon)', layer: 5, behaviorScript: 'Primordial Invulnerability — from Beyond; born from pre-universe chaos; immune to all elements; only Source Energy damages', voxelScale: 'continent-scale', aggroType: 'Passive_Invulnerable', drops: [d('chaos_essence', 0.5, '1', 'Source-Energy weapon')], category: 'conceptual_law_bound', novel: 'Beyond' },
  { name: 'Eternal Nine-Headed Dragon', nameCn: '永恒九头龙', tier: 'ancient', baseRank: 'transcendence', bloodline: 'dragon', habitat: 'void', diet: 'conceptual', preysOn: [], preyedUponBy: [], temperament: 'passive_cataclysmic', value: 'nine law-fragments (Time, Space, Karma, Life, Death)', layer: 5, behaviorScript: 'Law-Puzzle Boss — from ISSTH; each head = a natural law; severing requires solving a law-puzzle', voxelScale: 'continent-scale (9 heads)', aggroType: 'Multi_Puzzle_Boss', drops: [d('law_fragment_time', 0.1), d('law_fragment_space', 0.1), d('law_fragment_karma', 0.1)], category: 'conceptual_law_bound', novel: 'ISSTH' },
  { name: 'Universe-Weaving Spider', nameCn: '织宇蛛', tier: 'ancient', baseRank: 'transcendence', habitat: 'void', diet: 'conceptual', preysOn: [], preyedUponBy: [], temperament: 'passive_cataclysmic', value: 'fate-string silk (alters spatial coordinates)', layer: 5, behaviorScript: 'Fate-Web Weaver — from Beyond; damaging the web permanently alters regional spatial coordinates', voxelScale: 'galaxy-scale', aggroType: 'Passive_Cosmic', drops: [d('fate_string_silk', 0.1, '1', 'alters coordinates')], category: 'conceptual_law_bound', novel: 'Beyond' },
  { name: 'Soul-Devouring Parasite', nameCn: '噬魂虫', tier: 'demon', baseRank: 'ascendant', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: [], temperament: 'aggressive', value: 'parasitic core', layer: 4, behaviorScript: 'Infection — from RI; infects spirit beasts → aggressive husks; player bite → soul-force drain until cured', voxelScale: 'microscopic', aggroType: 'Parasitic_Infection', drops: [d('parasitic_core', 0.2, '1')], category: 'conceptual_law_bound', novel: 'Renegade Immortal' },
  { name: 'Void Mosquito Swarm', nameCn: '蚊兽群', tier: 'demon', baseRank: 'ascendant', habitat: 'void', diet: 'spiritivore', preysOn: [], preyedUponBy: ['nether_beast'], temperament: 'aggressive', value: 'mosquito proboscis; mutated swarm carapace', layer: 4, behaviorScript: 'Soul Drain Swarm — from RI; bypasses armor; targets Primordial Soul; duplicates if feeding', voxelScale: 'swarm (1.0×0.8×1.5 each)', aggroType: 'Soul_Drain_Swarm', drops: [d('mosquito_proboscis', 0.4, '1-3'), d('swarm_carapace', 0.3)], category: 'conceptual_law_bound', novel: 'Renegade Immortal', destinedCompanion: true },
  { name: 'Rank-9 Mosquito Beast', nameCn: '九阶蚊兽', tier: 'demon', baseRank: 'soul_formation', habitat: 'void', diet: 'spiritivore', preysOn: ['star_swallowing_shadow_wolf'], preyedUponBy: [], temperament: 'aggressive', value: 'shattered proboscis spear; transcendent void essence', layer: 3, behaviorScript: 'Core Siphon Piercing — from RI; 3.0× charge; proboscis bypasses armor, damages max Qi. Wang Lin signature.', voxelScale: '5.0×4.5×7.5', aggroType: 'Soul_Drain_Charge', drops: [d('shattered_proboscis_spear', 1.0, '1', 'soul-piercing spear'), d('transcendent_void_essence', 0.5)], category: 'conceptual_law_bound', novel: 'Renegade Immortal', destinedCompanion: true },
];

// ═══════════════════════════════════════════════════════════════════════
// THE FULL CATALOG — all real Er Gen creatures, zero procedural fillers
// ═══════════════════════════════════════════════════════════════════════
export const FULL_BESTIARY_CATALOG: CatalogEntry[] = [
  ...SPATIAL_COSMIC,      // 19
  ...BLOODLINE_MUTANT,    // 41
  ...ALCHEMICAL_CHIMERA,  // 10
  ...CONCEPTUAL_LAW_BOUND, // 15
];

// Deduplicate by name
const seen = new Set<string>();
export const DEDUPED_CATALOG: CatalogEntry[] = FULL_BESTIARY_CATALOG.filter((e) => {
  if (seen.has(e.name)) return false;
  seen.add(e.name);
  return true;
});

export const TOTAL_SPECIES_COUNT = DEDUPED_CATALOG.length;
export const CATEGORY_COUNTS = {
  spatial_cosmic_leviathan: SPATIAL_COSMIC.length,
  bloodline_mutant: BLOODLINE_MUTANT.length,
  alchemical_chimera: ALCHEMICAL_CHIMERA.length,
  conceptual_law_bound: CONCEPTUAL_LAW_BOUND.length,
};
