package dev.ergenverse.wanglin;

import dev.ergenverse.core.Ergenverse;
import dev.ergenverse.simulation.WorldRuntimeState;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.server.level.ServerLevel;

import javax.annotation.Nullable;
import java.util.HashMap;
import java.util.Map;

/**
 * Cave World Ownership — the cosmological truth that every "world" in Wang Lin's
 * branch can be OWNED by a higher-tier cultivator who farms it.
 *
 * <p><b>Canon (C5, CANON_RI_COMPLETE_WORLD.md):</b>
 * <pre>
 *   The Cave World is owned by the Seven-Colored Daoist.
 *   He created it as an artificial farm to harvest Joss Flames.
 *   Every cultivator inside is, unknowingly, his livestock.
 *   The seal he placed prevents Third-Step cultivators from rising
 *   (because a Third-Step cultivator could challenge his ownership).
 *   Wang Lin's escape = kill the owner = become the new owner.
 * </pre>
 *
 * <p><b>Per the Prime Directive:</b> ownership is OBJECTIVE. The fact that the
 * player doesn't know they're being farmed doesn't change the farm's existence.
 * A mortal on Planet Suzaku is livestock; their ignorance doesn't unmake the
 * livestock status. Cultivation reveals the ownership; combat resolves it.
 *
 * <p><b>Owner privileges (the owner of a world can):</b>
 * <ul>
 *   <li>Set a cultivation ceiling (no cultivator inside can naturally exceed it).</li>
 *   <li>Harvest Joss Flames generated by mortal faith inside the world.</li>
 *   <li>Bind or unbind the world's spiritual layer.</li>
 *   <li>Seal sub-regions with arrays they personally designed.</li>
 *   <li>Evict, kill, or reincarnate any cultivator inside (karmic cost applies).</li>
 * </ul>
 *
 * <p><b>Owner vulnerabilities (how to escape ownership):</b>
 * <ul>
 *   <li>Kill the owner directly (Wang Lin's path: kill Seven-Colored Daoist).</li>
 *   <li>Outlast the owner (if the owner dies of karma/tribulation, ownership reverts).</li>
 *   <li>Transcend the world entirely (the 4th Step void-crosses out of any owned world).</li>
 * </ul>
 *
 * <p>This class is the runtime registry of who owns what.
 *
 * <h2>Runtime ownership state</h2>
 * <p>The canon defaults (CAVE_WORLD, SEALED_REALM, OUTER_REALM, IAC) are immutable
 * t₀ snapshots. When a player kills an owner, a runtime override is recorded that
 * supersedes the canon default — per the Prime Directive, the player's actions
 * can diverge from canon. Use {@link #getRuntimeOwnership(String)} to read the
 * current effective ownership; use {@link #transferOwnership} to record a kill.
 */
public final class CaveWorldOwnership {

    private CaveWorldOwnership() {}

    /**
     * Runtime ownership overrides keyed by worldLayerId.
     * Populated when a player kills an owner. The override replaces the canon
     * default for the duration of the world save (persisted via WorldRuntimeState).
     */
    private static final Map<String, Ownership> RUNTIME_OWNERSHIP = new HashMap<>();

    /**
     * Record of which NPC characterId is the canon owner of which world layer.
     * When an EntityCultivator with one of these IDs dies, ownership transfers.
     */
    private static final Map<String, String> OWNER_NPC_TO_WORLD = new HashMap<>();
    static {
        // The Seven-Colored Daoist owns Cave World + Sealed Realm + Outer Realm
        OWNER_NPC_TO_WORLD.put("seven_colored_daoist", "cave_world");

        // Per canon: other world-layer owners that players can encounter
        // Tu Si's remnant consciousness owns the Land of the Ancient God (trial realm)
        // — his spirit remains as the trial guardian; killing it transfers ownership
        OWNER_NPC_TO_WORLD.put("tu_s remnants", "land_of_the_ancient_god");

        // The Vermilion Bird's sealed spirit owns the Suzaku Tomb (pocket dimension)
        // — a 4th-step Vermilion Bird ancestor sealed its remnant there
        OWNER_NPC_TO_WORLD.put("vermilion_bird_ancestor_spirit", "suzaku_tomb");

        // The Blood Ancestor owns the Immortal Graveyard (pocket dimension)
        // — his blood domain persists as the graveyard's core
        OWNER_NPC_TO_WORLD.put("blood_ancestor", "immortal_graveyard");
    }

    /**
     * Ownership record for a single world-layer.
     * A world with ownerId == null is "free" — no cultivator owns it.
     */
    public static final class Ownership {
        public final String worldLayerId;       // e.g. "cave_world"
        public final String worldLayerName;
        public final String ownerId;            // null = free world
        public final String ownerName;          // null = free world
        public final String ownerRealmId;       // the cultivation realm of the owner (gates escape difficulty)
        public final String originReason;       // why is this world owned? (canon: "Seven-Colored Daoist created the Cave World as a Joss Flame farm")
        public final String harvestCurrency;    // what the owner harvests ("joss_flames", "karma", "soul_essence", etc.)
        public final int cultivationCeilingAbsoluteTier;  // no cultivator inside can naturally exceed this absolute tier
        public final boolean sealActive;        // is the seal currently suppressing cultivators?
        public final String sealArrayId;        // the formation enforcing the ceiling (null if owner-power-only)

        public Ownership(String worldLayerId, String worldLayerName, String ownerId, String ownerName,
                         String ownerRealmId, String originReason, String harvestCurrency,
                         int cultivationCeilingAbsoluteTier, boolean sealActive, String sealArrayId) {
            this.worldLayerId = worldLayerId;
            this.worldLayerName = worldLayerName;
            this.ownerId = ownerId;
            this.ownerName = ownerName;
            this.ownerRealmId = ownerRealmId;
            this.originReason = originReason;
            this.harvestCurrency = harvestCurrency;
            this.cultivationCeilingAbsoluteTier = cultivationCeilingAbsoluteTier;
            this.sealActive = sealActive;
            this.sealArrayId = sealArrayId;
        }

        public boolean isFree() { return ownerId == null; }
    }

    // ─── Canon ownership records (Wang Lin's branch) ────────────────────

    /** The Cave World — owned by Seven-Colored Daoist. */
    public static final Ownership CAVE_WORLD = new Ownership(
        "cave_world", "The Cave World",
        "seven_colored_daoist", "Seven-Colored Daoist",
        "paragon",                              // owner is at Paragon / 4th-Step-adjacent tier
        "Created the Cave World as an artificial farm to harvest Joss Flames from mortal faith.",
        "joss_flames",
        9,                                       // absolute tier 9 = Nirvana Fruit ceiling; Third-Step (tier 10+) suppressed
        true,
        "realm_sealing_grand_array"              // the Realm-Sealing Grand Array enforces the ceiling inside the Sealed Realm
    );

    /** The Sealed Realm — the inner half, also sealed (separately) by the Realm-Sealing Grand Array. */
    public static final Ownership SEALED_REALM = new Ownership(
        "sealed_realm", "Sealed Realm",
        "seven_colored_daoist", "Seven-Colored Daoist (inherited)",  // same owner as Cave World
        "paragon",
        "The Sealed Realm is the inner half of the Cave World. The Realm-Sealing Grand Array (spirit: Heaven-Splitting Axe) was placed to prevent Third-Step cultivators from rising inside it.",
        "joss_flames",
        8,                                       // even tighter ceiling — Heaven Blight (quasi-Third-Step) is the cap
        true,
        "realm_sealing_grand_array"
    );

    /** The Outer Realm — outer half of the Cave World. NOT separately sealed (but still inside the Cave World). */
    public static final Ownership OUTER_REALM = new Ownership(
        "outer_realm", "Outer Realm",
        "seven_colored_daoist", "Seven-Colored Daoist (inherited)",
        "paragon",
        "The outer half of the Cave World. Higher-tier cultivators dwell here because the Realm-Sealing Array doesn't apply. Still owned by the Seven-Colored Daoist as part of the Cave World.",
        "joss_flames",
        11,                                      // Third-Step cultivators can exist here (the array doesn't seal this half)
        false,
        null
    );

    /** The Immortal Astral Continent — NOT owned (it's the 'true' reality outside the Cave World). */
    public static final Ownership IAC = new Ownership(
        "immortal_astral_continent", "Immortal Astral Continent",
        null, null,
        null,
        "The 'true' reality outside the Cave World. No single owner. The 9 Suns (Grand Empyreans) collectively dominate but do not 'own' it as a farm.",
        null,
        14,                                      // Heaven Trampling tier is achievable here
        false,
        null
    );

    /** The Land of the Ancient God — owned by Tu Si's remnant consciousness. */
    public static final Ownership LAND_OF_ANCIENT_GOD = new Ownership(
        "land_of_the_ancient_god", "Land of the Ancient God",
        "tu_s remnants", "Tu Si's Remnant",
        "soul_formation",
        "A trial realm left by the Ancient God Tu Si. His remnant consciousness governs the Restrictions Mountain trial and the star-absorption cultivation environment.",
        "star_energy",
        7,  // Core Formation ceiling — Nascent Soul+ can challenge the trial
        true,
        "ancient_god_restriction_array"
    );

    /** Suzaku Tomb — owned by the Vermilion Bird ancestor's sealed spirit. */
    public static final Ownership SUZAKU_TOMB = new Ownership(
        "suzaku_tomb", "Suzaku Tomb",
        "vermilion_bird_ancestor_spirit", "Vermilion Bird Ancestor Spirit",
        "deity_transformation",
        "A pocket dimension sealing the 2nd-Generation Vermilion Bird's remnant. The tomb contains Vermilion Bird inheritances and is guarded by the ancestor's spirit.",
        "vermilion_bird_essence",
        10,  // Nascent Soul ceiling — Soul Formation+ can challenge
        true,
        "vermilion_bird_seal"
    );

    /** Immortal Graveyard — owned by the Blood Ancestor's lingering domain. */
    public static final Ownership IMMORTAL_GRAVEYARD = new Ownership(
        "immortal_graveyard", "Immortal Graveyard",
        "blood_ancestor", "Blood Ancestor",
        "soul_formation",
        "A pocket dimension formed from the Blood Ancestor's domain after his death. Ghosts and undead roam; the blood domain persists as the core.",
        "soul_essence",
        8,  // Core Formation ceiling
        true,
        "blood_domain_array"
    );

    /**
     * The "is this world owned?" check.
     * Returns the canon ownership record, or null if the world is free.
     * For runtime overrides (after a player kills the owner), use {@link #getRuntimeOwnership(String)}.
     */
    public static Ownership getOwnership(String worldLayerId) {
        switch (worldLayerId) {
            case "cave_world": return CAVE_WORLD;
            case "sealed_realm": return SEALED_REALM;
            case "outer_realm": return OUTER_REALM;
            case "immortal_astral_continent": return IAC;
            case "land_of_the_ancient_god": return LAND_OF_ANCIENT_GOD;
            case "suzaku_tomb": return SUZAKU_TOMB;
            case "immortal_graveyard": return IMMORTAL_GRAVEYARD;
            default: return null;  // unknown = treat as free
        }
    }

    /**
     * Get the effective ownership: runtime override if present, otherwise the canon default.
     * This is the method gameplay code should use to check "who owns this world right now?"
     */
    public static Ownership getRuntimeOwnership(String worldLayerId) {
        Ownership override = RUNTIME_OWNERSHIP.get(worldLayerId);
        return override != null ? override : getOwnership(worldLayerId);
    }

    /**
     * Is the given NPC characterId a known world owner?
     * @return the worldLayerId they own, or null if not an owner
     */
    public static String getOwnedWorldForNpc(String characterId) {
        if (characterId == null) return null;
        return OWNER_NPC_TO_WORLD.get(characterId);
    }

    /**
     * Check whether an owner NPC has already been killed (runtime override exists).
     * @param worldLayerId the world to check
     * @return true if the canon owner has been killed and replaced (or world freed)
     */
    public static boolean isOwnerReplaced(String worldLayerId) {
        return RUNTIME_OWNERSHIP.containsKey(worldLayerId);
    }

    /**
     * Clear all runtime ownership overrides (called on server stop).
     */
    public static void clearRuntimeOverrides() {
        RUNTIME_OWNERSHIP.clear();
    }

    /**
     * The "am I being farmed?" check.
     * This is the central horror of Wang Lin's cosmology: most cultivators
     * spend their entire lives as livestock without ever knowing.
     *
     * <p>Per the Prime Directive: the player is farmed regardless of whether
     * they know it. Cultivation reveals it; it doesn't change it.
     *
     * @param worldLayerId the world the player is currently in
     * @return true if the world is owned AND the seal is active (i.e. player is subject to the ceiling)
     */
    public static boolean isPlayerFarmed(String worldLayerId) {
        Ownership o = getRuntimeOwnership(worldLayerId);
        return o != null && !o.isFree() && o.sealActive;
    }

    /**
     * The cultivation ceiling for a given world.
     * Returns the absolute tier the player cannot naturally exceed.
     * Returns Integer.MAX_VALUE if the world has no ceiling (free world).
     *
     * <p>This is enforced by the world's law (not by the owner's attention).
     * The owner doesn't need to actively suppress every cultivator — the seal does it.
     */
    public static int cultivationCeiling(String worldLayerId) {
        Ownership o = getRuntimeOwnership(worldLayerId);
        if (o == null || o.isFree() || !o.sealActive) return Integer.MAX_VALUE;
        return o.cultivationCeilingAbsoluteTier;
    }

    /**
     * The "can the player break through to this absolute tier in this world?" check.
     * Returns false if the world's ceiling blocks the breakthrough.
     *
     * <p>Exceptions (per canon):
     * <ul>
     *   <li>If the player has the Heaven-Defying Bead, the bead's "defy heaven" nature
     *       allows ONE tier above the ceiling per major arc (Wang Lin's signature loophole).</li>
     *   <li>If the player kills the array's spirit (the Heaven-Splitting Axe), the seal breaks.</li>
     *   <li>If the player kills the owner (Seven-Colored Daoist), ownership transfers.</li>
     * </ul>
     */
    public static boolean canBreakthroughTo(String worldLayerId, int targetAbsoluteTier, boolean hasHeavenDefyingBead) {
        int ceiling = cultivationCeiling(worldLayerId);
        if (targetAbsoluteTier <= ceiling) return true;
        // The Heaven-Defying Bead allows ONE tier above the ceiling (the "defy heaven" loophole)
        if (hasHeavenDefyingBead && targetAbsoluteTier == ceiling + 1) return true;
        return false;
    }

    /**
     * The "what happens when the owner is killed?" transition.
     * Per canon: ownership transfers to the killer (Wang Lin killed Seven-Colored
     * Daoist and became the new Cave World owner).
     *
     * <p>This method BOTH returns the new ownership AND records it as the runtime
     * override (so subsequent queries via {@link #getRuntimeOwnership} see the
     * new owner). The canon default remains pristine per the Prime Directive.
     *
     * <p>Side effects:
     * <ul>
     *   <li>Dissolves the Realm-Sealing Grand Array (the new owner inherits and frees the seal).</li>
     *   <li>Lifts the cultivation ceiling (new ceiling = 14, effectively unbounded).</li>
     *   <li>Joss Flame harvest now flows to the new owner.</li>
     * </ul>
     *
     * @param worldLayerId the world whose owner was killed
     * @param killerId the entity that killed the owner
     * @param killerName the entity's name
     * @param killerRealmId the entity's cultivation realm
     * @return the new ownership record
     */
    /**
     * Transfer ownership without persisting (legacy / command-only path).
     * Use {@link #transferOwnership(String, String, String, String, ServerLevel)} for gameplay use.
     */
    public static Ownership transferOwnership(String worldLayerId, String killerId, String killerName, String killerRealmId) {
        return transferOwnership(worldLayerId, killerId, killerName, killerRealmId, null);
    }

    /**
     * Transfer ownership AND persist to world save.
     * @param level the ServerLevel to persist into (null = skip persistence, only in-memory)
     */
    public static Ownership transferOwnership(String worldLayerId, String killerId, String killerName, String killerRealmId, @Nullable ServerLevel level) {
        Ownership old = getRuntimeOwnership(worldLayerId);
        if (old == null) {
            Ergenverse.LOGGER.warn("[Ergenverse] CaveWorldOwnership: cannot transfer ownership of unknown world {}", worldLayerId);
            return null;
        }
        Ergenverse.LOGGER.info("[Ergenverse] CaveWorldOwnership: {} ownership transferred from {} to {} (killed owner).",
            worldLayerId, old.ownerName, killerName);
        // The new owner inherits the world but can choose to dissolve the seal
        Ownership newOwner = new Ownership(
            worldLayerId, old.worldLayerName,
            killerId, killerName,
            killerRealmId,
            "Inherited by killing the previous owner (" + old.ownerName + "). " + old.originReason,
            old.harvestCurrency,
            14,  // the new owner can choose to lift the ceiling (Wang Lin did)
            false,  // new owner dissolves the seal
            null
        );
        // Record as runtime override — subsequent queries see the new owner
        RUNTIME_OWNERSHIP.put(worldLayerId, newOwner);

        // Persist to world save (survives server restart)
        persistToWorldSave(level);
        if (level != null) {
            Ergenverse.LOGGER.info("[CaveWorldOwnership] Ownership persisted to world save for world {}.", worldLayerId);
        } else {
            Ergenverse.LOGGER.warn("[CaveWorldOwnership] Ownership transfer for {} was NOT persisted (no ServerLevel provided). Will persist on next server tick restore cycle.", worldLayerId);
        }

        // Also dissolve the Realm-Sealing Grand Array if it was enforcing the seal
        if (RealmSealingGrandArray.isArrayActive()) {
            RealmSealingGrandArray.dissolve();
        }
        // Cascade: if the killed owner also owned related world layers (e.g. Seven-Colored Daoist
        // owned cave_world + sealed_realm + outer_realm), transfer all of them.
        for (String relatedWorld : new String[]{"sealed_realm", "outer_realm"}) {
            if (relatedWorld.equals(worldLayerId)) continue;
            Ownership related = getRuntimeOwnership(relatedWorld);
            if (related != null && related.ownerId != null && related.ownerId.equals(old.ownerId)
                    && !RUNTIME_OWNERSHIP.containsKey(relatedWorld)) {
                Ownership cascaded = new Ownership(
                        relatedWorld, related.worldLayerName,
                        killerId, killerName, killerRealmId,
                        "Inherited by killing the previous owner (" + related.ownerName + "). " + related.originReason,
                        related.harvestCurrency,
                        14,
                        false,
                        null);
                RUNTIME_OWNERSHIP.put(relatedWorld, cascaded);
                Ergenverse.LOGGER.info("[Ergenverse] CaveWorldOwnership: cascaded {} ownership to {} (same previous owner).",
                        relatedWorld, killerName);
            }
        }
        return newOwner;
    }

    /**
     * Serialize the runtime ownership overrides to a map for persistence.
     * Returns a deep copy; modifying the returned map does not affect runtime state.
     */
    public static Map<String, Ownership> snapshotRuntimeOverrides() {
        return new HashMap<>(RUNTIME_OWNERSHIP);
    }

    /**
     * Restore runtime overrides from WorldRuntimeState (persisted across server restarts).
     * Called on server tick to ensure ownership survives restart.
     */
    public static void restoreFromWorldSave(@Nullable ServerLevel level) {
        if (level == null) return;
        WorldRuntimeState state = WorldRuntimeState.get(level);
        Map<String, CompoundTag> overrides = state.getAllCaveWorldOwnershipOverrides();
        if (overrides.isEmpty()) return;
        for (Map.Entry<String, CompoundTag> entry : overrides.entrySet()) {
            CompoundTag tag = entry.getValue();
            Ownership ownership = new Ownership(
                entry.getKey(),
                tag.contains("world_name") ? tag.getString("world_name") : entry.getKey(),
                tag.contains("owner_id") ? tag.getString("owner_id") : null,
                tag.contains("owner_name") ? tag.getString("owner_name") : null,
                tag.contains("owner_realm") ? tag.getString("owner_realm") : null,
                tag.contains("origin_reason") ? tag.getString("origin_reason") : "",
                tag.contains("harvest_currency") ? tag.getString("harvest_currency") : null,
                tag.contains("ceiling_tier") ? tag.getInt("ceiling_tier") : 14,
                tag.contains("seal_active") && tag.getBoolean("seal_active"),
                tag.contains("seal_array") ? tag.getString("seal_array") : null
            );
            RUNTIME_OWNERSHIP.put(entry.getKey(), ownership);
        }
        Ergenverse.LOGGER.info("[CaveWorldOwnership] Restored {} ownership overrides from world save.", overrides.size());
    }

    /**
     * Persist current runtime overrides to WorldRuntimeState.
     */
    public static void persistToWorldSave(@Nullable ServerLevel level) {
        if (level == null) return;
        WorldRuntimeState state = WorldRuntimeState.get(level);
        for (Map.Entry<String, Ownership> entry : RUNTIME_OWNERSHIP.entrySet()) {
            CompoundTag tag = new CompoundTag();
            Ownership o = entry.getValue();
            tag.putString("world_name", o.worldLayerName);
            tag.putString("owner_id", o.ownerId != null ? o.ownerId : "");
            tag.putString("owner_name", o.ownerName != null ? o.ownerName : "");
            tag.putString("owner_realm", o.ownerRealmId != null ? o.ownerRealmId : "");
            tag.putString("origin_reason", o.originReason);
            tag.putString("harvest_currency", o.harvestCurrency != null ? o.harvestCurrency : "");
            tag.putInt("ceiling_tier", o.cultivationCeilingAbsoluteTier);
            tag.putBoolean("seal_active", o.sealActive);
            tag.putString("seal_array", o.sealArrayId != null ? o.sealArrayId : "");
            state.setCaveWorldOwnership(entry.getKey(), tag);
        }
    }
}
