package dev.ergenverse.wanglin;

import dev.ergenverse.core.Ergenverse;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * Joss Flame Economy — the harvest loop of the Cave World.
 *
 * <p><b>Canon (C5, CANON_RI_COMPLETE_WORLD.md):</b>
 * <pre>
 *   Joss Flames (香火) are cultivation energy produced by mortal faith.
 *   Mortals worship → generate Joss Flames → cultivators collect →
 *   the Cave World owner (Seven-Colored Daoist) harvests.
 *   Every cultivator inside the Cave World is, unknowingly,
 *   a Joss Flame farmer for the owner.
 * </pre>
 *
 * <p>The Joss Flame economy is the engine of Wang Lin's cosmology.
 * It is why the Cave World exists. It is why the Seven-Colored Daoist
 * placed the seal (to keep his livestock productive). It is why Wang Lin
 * must kill him to escape (the owner will not abandon his farm).
 *
 * <p><b>Per the Prime Directive:</b> Joss Flames are GENERATED by mortal faith
 * whether or not the player perceives them. A mortal village generates Joss
 * Flames constantly; the mortal villagers never see them. A cultivator at
 * Soul Formation+ can perceive the flames; a cultivator at Third-Step+ can
 * harvest them directly. The owner harvests automatically through the seal.
 *
 * <p><b>The harvest loop (4 stages):</b>
 * <ol>
 *   <li><b>GENERATION</b> — mortal worship generates Joss Flames at a village temple/shrine.</li>
 *   <li><b>COLLECTION</b> — a cultivator (or the world's spiritual layer) gathers the flames into a storage vessel.</li>
 *   <li><b>REFINEMENT</b> — the collector refines the flames into pure cultivation energy.</li>
 *   <li><b>HARVEST</b> — the world owner (via the seal) siphons a percentage of all refined flames.</li>
 * </ol>
 *
 * <p>Wang Lin's unique position: he eventually perceives the loop (Book 11+),
 * refuses to be livestock, and kills the owner. The loop then belongs to him.
 */
public final class JossFlameEconomy {

    private JossFlameEconomy() {}

    /** The 4 stages of the Joss Flame harvest loop. */
    public enum Stage {
        GENERATION("Mortal worship generates Joss Flames at a temple/shrine."),
        COLLECTION("A cultivator gathers the flames into a storage vessel."),
        REFINEMENT("The collector refines the flames into pure cultivation energy."),
        HARVEST("The world owner siphons a percentage of all refined flames via the seal.");

        public final String description;
        Stage(String d) { this.description = d; }
    }

    /** A Joss Flame source — a place where mortal worship generates flames. */
    public static final class JossFlameSource {
        public final String id;
        public final String villageId;
        public final String templeName;          // e.g. "Temple of the Mountain Spirit"
        public final String worshippedEntity;    // what the mortals worship (a spirit, an ancestor, a fake god)
        public final int mortalWorshipperCount;  // more mortals = more flames
        public final double flameGenerationRate; // flames per in-game day
        public final double accumulatedFlames;   // current uncollected flames
        public final String collectorId;         // null = uncollected (floating in spiritual layer)

        public JossFlameSource(String id, String villageId, String templeName, String worshippedEntity,
                              int mortalWorshipperCount, double flameGenerationRate, double accumulatedFlames,
                              String collectorId) {
            this.id = id; this.villageId = villageId; this.templeName = templeName;
            this.worshippedEntity = worshippedEntity; this.mortalWorshipperCount = mortalWorshipperCount;
            this.flameGenerationRate = flameGenerationRate; this.accumulatedFlames = accumulatedFlames;
            this.collectorId = collectorId;
        }
    }

    /** Runtime registry of Joss Flame sources per village. */
    private static final Map<String, JossFlameSource> SOURCES = new HashMap<>();

    /** The owner's harvest percentage (canon: the Seven-Colored Daoist takes ~30% of all refined flames via the seal). */
    public static final double OWNER_HARVEST_PERCENTAGE = 0.30;

    /**
     * Register a Joss Flame source at a village.
     * Called during world generation when a mortal village + temple is created.
     */
    public static JossFlameSource registerSource(String villageId, String templeName, String worshippedEntity,
                                                  int mortalWorshipperCount) {
        String id = "joss_" + UUID.randomUUID().toString().substring(0, 8);
        // Generation rate: 1 flame per 10 mortals per day, modified by temple prominence
        double rate = (mortalWorshipperCount / 10.0) * (0.5 + Math.random() * 0.5);
        JossFlameSource source = new JossFlameSource(id, villageId, templeName, worshippedEntity,
            mortalWorshipperCount, rate, 0.0, null);
        SOURCES.put(id, source);
        Ergenverse.LOGGER.debug("[Ergenverse] JossFlameEconomy: source {} registered at village {} ({} mortals, {}/day)",
            id, villageId, mortalWorshipperCount, String.format("%.2f", rate));
        return source;
    }

    /**
     * Tick the Joss Flame economy for one in-game day.
     * Each source generates flames; the owner harvests a percentage of all collected flames.
     *
     * @param ownerActive true if the Cave World owner (Seven-Colored Daoist) is still alive
     * @return the total flames harvested by the owner this tick
     */
    public static double tickDay(boolean ownerActive) {
        double ownerHarvest = 0.0;
        for (JossFlameSource source : SOURCES.values()) {
            // Stage 1: generation
            double generated = source.flameGenerationRate;
            double newAccumulated = source.accumulatedFlames + generated;

            // Stage 2: collection — if a collector is assigned, they gather; otherwise flames accumulate
            if (source.collectorId != null) {
                // Stage 3: refinement happens at the collector (handled by the collector's capability)
                // Stage 4: harvest — owner siphons OWNER_HARVEST_PERCENTAGE of all collected flames
                if (ownerActive) {
                    double ownerCut = generated * OWNER_HARVEST_PERCENTAGE;
                    ownerHarvest += ownerCut;
                    // The remaining 70% goes to the collector
                    Ergenverse.LOGGER.debug("[Ergenverse] JossFlameEconomy: owner harvested {} flames from source {}",
                        String.format("%.2f", ownerCut), source.id);
                }
                // Collector gets the rest (70% if owner active, 100% if owner dead)
                double collectorCut = ownerActive ? generated * (1 - OWNER_HARVEST_PERCENTAGE) : generated;
                // (In a full implementation, this would feed into the collector's cultivation progression)
                Ergenverse.LOGGER.debug("[Ergenverse] JossFlameEconomy: collector {} gained {} flames from source {}",
                    source.collectorId, String.format("%.2f", collectorCut), source.id);
            } else {
                // Uncollected flames dissipate slowly into the spiritual layer (40% loss per day)
                double dissipated = newAccumulated * 0.40;
                newAccumulated -= dissipated;
                Ergenverse.LOGGER.debug("[Ergenverse] JossFlameEconomy: {} flames dissipated at source {} (no collector)",
                    String.format("%.2f", dissipated), source.id);
            }

            // Update source (immutable, so replace)
            SOURCES.put(source.id, new JossFlameSource(source.id, source.villageId, source.templeName,
                source.worshippedEntity, source.mortalWorshipperCount, source.flameGenerationRate,
                source.collectorId == null ? newAccumulated : 0.0, source.collectorId));
        }
        return ownerHarvest;
    }

    /**
     * A collector (cultivator) claims a Joss Flame source.
     * Requires Soul Formation+ cultivation (per canon: must perceive the flames to collect them).
     *
     * @return true if the claim succeeded
     */
    public static boolean claimSource(String sourceId, String collectorId, String collectorRealmId) {
        JossFlameSource source = SOURCES.get(sourceId);
        if (source == null) return false;
        // Canon: collectors below Soul Formation cannot perceive Joss Flames
        if (!canPerceiveJossFlames(collectorRealmId)) {
            Ergenverse.LOGGER.debug("[Ergenverse] JossFlameEconomy: collector {} cannot perceive Joss Flames (realm too low)",
                collectorId);
            return false;
        }
        if (source.collectorId != null && !source.collectorId.equals(collectorId)) {
            return false;  // already claimed by another
        }
        SOURCES.put(sourceId, new JossFlameSource(source.id, source.villageId, source.templeName,
            source.worshippedEntity, source.mortalWorshipperCount, source.flameGenerationRate,
            source.accumulatedFlames, collectorId));
        Ergenverse.LOGGER.info("[Ergenverse] JossFlameEconomy: source {} claimed by collector {}",
            sourceId, collectorId);
        return true;
    }

    /**
     * Can a cultivator at this realm perceive Joss Flames?
     * Canon: requires Soul Formation (化神) — the realm where the Domain forms
     * and the cultivator begins to perceive the spiritual layer directly.
     */
    public static boolean canPerceiveJossFlames(String realmId) {
        switch (realmId) {
            case "soul_formation":
            case "soul_transformation":
            case "ascendant":
            case "illusory_yin":
            case "corporeal_yang":
            case "nirvana_scryer":
            case "nirvana_cleanser":
            case "nirvana_fruit":
            case "spirit_seizer":
            case "true_immortal":
            case "ancient":
            case "paragon":
            case "transcendence":
                return true;
            default:
                return false;  // mortals through Nascent Soul cannot perceive
        }
    }

    /**
     * The "am I being farmed?" insight.
     * A cultivator at Nirvana Scryer+ can ANALYZE the harvest loop and realize
     * they are livestock. This is the moment Wang Lin's cosmology becomes personal.
     *
     * <p>Per canon: Wang Lin realized the Cave World was a farm around Book 11
     * when he met the Seven-Colored Daoist directly. Before that, he suspected.
     */
    public static boolean canPerceiveOwnershipLoop(String realmId) {
        switch (realmId) {
            case "nirvana_scryer":
            case "nirvana_cleanser":
            case "nirvana_fruit":
            case "spirit_seizer":
            case "true_immortal":
            case "ancient":
            case "paragon":
            case "transcendence":
                return true;
            default:
                return false;
        }
    }
}
