#!/usr/bin/env python3
"""Append CRON-135 worklog entry to both worklog.md copies."""
from pathlib import Path

ENTRY = """

---
Task ID: CRON-COMPLETIONIST-135
Agent: cron-completionist
Task: Implement priority (g) — upward ray-cast for tall obstacles in CultivatorFlightNavigator. Closes CRON-133 self-critique #5: 'No vertical obstacle avoidance. The navigator ray-casts forward at 3 heights (0.5, 1.0, 1.5) but does NOT ray-cast UPWARD. A cultivator flying at cruise altitude (4 blocks above surface) toward a 10-block-tall wall will detect the wall at horizontal distance 3 (good), dodge perpendicular (good), but if neither dodge is clear, vaults upward (good). However, a cultivator already at high altitude (e.g., 30 blocks up) flying toward a mountain peak — the mountain peak might be ABOVE the cultivator. The forward ray-cast at heights 0.5/1.0/1.5 above entity Y won't detect a mountain peak 5 blocks above. The cultivator would fly into the mountainside. A future CRON should add an UPWARD ray-cast at heights +5, +10 to detect tall obstacles. Score 5/10 for vertical obstacle awareness (forward-only).' CRON-134 next-priority (b) scored this 7/10 HIGH CORRECTNESS, 3/10 implementation difficulty.

Work Log:
- STEP 1: Read worklog tail. Confirmed CRON-134 (commit 07319cd → 6779020) shipped qi expenditure for cultivator sword-flight. CRON-134 next-priority list (a)-(g): (a) playtest (user action — cannot self-execute), (b) upward ray-cast for tall obstacles (Score 7/10 HIGH CORRECTNESS — closes CRON-133 #5), (c) qi cost for CultivatorSwordQiGoal (Score 7/10), (d) qi-bar overlay (Score 7/10), (e) scale qi regen with realm (Score 6/10), (f) increase LOOKAHEAD (Score 6/10), (g) spread 7x7 chunk force-load (Score 7/10). Picked (b) — highest score among self-executable items, closes a specific identified gap from CRON-133 self-critique, and aligns with the user's standing CRON priority (g) COLLISION/AI for cultivators.
- STEP 2: Audited CultivatorFlightNavigator (CRON-133, 240 lines). The forward ray-cast at HEIGHT_SAMPLES = {0.5D, 1.0D, 1.5D} only checks the cultivator's BODY height (feet to head). A cultivator at cruise altitude (surface+4) flying toward a mountain has their body at Y=surface+4 to surface+5.5 — the mountainside's leading edge is typically ABOVE this (mountain peaks rise 10-50+ blocks above surrounding terrain). The forward check returns 'clear' because the mountainside is above 1.5 entity-relative. The cultivator flies into the mountainside and the ride_sword clips through rock — a canon violation (cultivators fly OVER mountains, never THROUGH them).
- STEP 3: Designed the upward ray-cast. Added UPWARD_SAMPLES = {3.0D, 6.0D, 9.0D} — three upward height offsets (relative to entity Y) ray-cast at the same LOOKAHEAD distance forward. Offsets chosen to catch obstacles 3-9 blocks above the cultivator:
  - +3.0: catches 3-block-tall walls (sect perimeter walls, pagodas)
  - +6.0: catches 6-block-tall structures (gatehouses, watchtowers)
  - +9.0: catches mountain leading edges and tall cliffs
  Beyond +9, the cultivator is high enough that mountain collision is unlikely (cruise altitude is surface+4, so +9 above entity = 13 blocks above surface, which is above most mountain leading edges in the village biome).
- STEP 4: Added TALL_VAULT_SPEED_SCALE = 1.2D — a STRONGER vault impulse for tall obstacles. Standard VAULT_SPEED_SCALE = 0.8D is for short obstacles (detected only by forward ray-cast). The taller vault (1.2D vs 0.8D, +50%) gives the cultivator more upward velocity to clear mountainsides and cliffs. At cruise speed 0.4 blocks/tick, the tall vault produces 0.4 * 1.2 = 0.48 blocks/tick upward = 9.6 blocks/sec — enough to clear a 3-block obstacle in ~1 tick of warning time (LOOKAHEAD=3 at 0.4 speed = 7.5 ticks warning).
- STEP 5: Expanded SteerResult from 5 fields to 6 fields — added `tallObstacle` boolean. When true, the obstacle was detected by the upward ray-cast (tall obstacle case). When false, the obstacle was detected only by the forward ray-cast (short obstacle case). The `blocked` field remains true in both cases. The `tallObstacle` flag is always false when `blocked` is false (clear path).
- STEP 6: Refactored computeSteer to use both ray-casts:
  1. `forwardBlocked = isForwardBlocked(cultivator, nx, nz)` — existing check at body heights.
  2. `upwardBlocked = isUpwardBlocked(cultivator, nx, nz)` — new check at upward heights.
  3. `blocked = forwardBlocked || upwardBlocked` — path is blocked if EITHER check hits.
  4. `tallObstacle = upwardBlocked` — tall obstacle flag set when upward check detected it.
  5. Clear path: return standard cruise velocity (tallObstacle=false).
  6. Dodge path: if tallObstacle, DOUBLE the upward bias (DODGE_UPWARD_BIAS_SCALE * 2.0D) so the dodge also gains altitude — helps clear the tall obstacle while dodging around it.
  7. Vault path: `vaultScale = tallObstacle ? TALL_VAULT_SPEED_SCALE : VAULT_SPEED_SCALE` — choose stronger vault for tall obstacles, standard vault for short obstacles.
- STEP 7: Added isUpwardBlocked helper method — same structure as isForwardBlocked but iterates UPWARD_SAMPLES instead of HEIGHT_SAMPLES. Uses the same BlockState.isSolidRender test (consistent with FlightMoveControl for beast flight).
- STEP 8: Updated all 4 SteerResult construction sites to the new 6-arg form (added tallObstacle as the 3rd boolean arg, after `blocked` and before `dodgedLeft`):
  - Vertical-only edge case: `new SteerResult(new Vec3(0, vy, 0), false, false, false, false, false)` — tallObstacle=false (no horizontal obstacle possible).
  - Clear path: `new SteerResult(new Vec3(vx, vy, vz), false, false, false, false, false)` — tallObstacle=false.
  - Dodge: `new SteerResult(new Vec3(vx, vy, vz), true, tallObstacle, goLeft, !goLeft, false)` — tallObstacle propagated.
  - Vault: `new SteerResult(new Vec3(vx, vy, vz), true, tallObstacle, false, false, true)` — tallObstacle propagated.
- STEP 9: Updated algorithm javadoc (CRON-135 step 3 added; CRON-135 step 5 updated to mention stronger vault for tall obstacles). Updated canon fidelity section to reference mountainsides explicitly (the canonical case of cultivators flying OVER mountains, not through them). NO fabricated chapter citations — the web-search verification date (2026-07-27) is preserved from CRON-133.
- STEP 10: Wrote scripts/cron135_verify_upward_raycast.py — 60 checks across 13 groups:
  1. UPWARD_SAMPLES constant (5 checks: declared, = {3.0D, 6.0D, 9.0D}, CRON-135 javadoc, mountainside reference).
  2. TALL_VAULT_SPEED_SCALE constant (4 checks: declared, = 1.2D, > VAULT_SPEED_SCALE, CRON-135 javadoc).
  3. SteerResult.tallObstacle field (3 checks: field declared, CRON-135 javadoc, TALL_VAULT_SPEED_SCALE reference).
  4. SteerResult constructor (2 checks: 6-arg signature, this.tallObstacle = tallObstacle).
  5. isUpwardBlocked helper (5 checks: method exists, CRON-135 javadoc, iterates UPWARD_SAMPLES, isSolidRender, BlockPos.containing).
  6. computeSteer calls isUpwardBlocked (3 checks: body extracted, calls isUpwardBlocked, still calls isForwardBlocked).
  7. computeSteer combines forwardBlocked || upwardBlocked (4 checks: forwardBlocked var, upwardBlocked var, blocked = ||, tallObstacle = upwardBlocked).
  8. computeSteer uses tallObstacle for vault scale (2 checks: vaultScale = tallObstacle ? TALL : STANDARD, vy = flightSpeed * vaultScale).
  9. computeSteer doubles upward bias during dodge when tallObstacle (4 checks: upwardBias var, * 2.0D for tall, standard for short, vy = upwardBias).
  10. All 4 SteerResult construction sites (6 checks: count=4, 6-arg pattern, vertical-only, clear-path, dodge, vault).
  11. Canon fidelity markers (8 checks: CRON-135 algorithm javadoc, CRON-135 vault javadoc, mountainside, cliff, tower, web-search date, no-fabricated-citations, 仙逆 reference).
  12. No regression: CRON-133 constants unchanged (11 checks: LOOKAHEAD, HEIGHT_SAMPLES, DODGE_PROBE_DIST, DODGE_SPEED_SCALE, VAULT_SPEED_SCALE, VAULT_FORWARD_SCALE, DODGE_UPWARD_BIAS_SCALE, DODGE_FORWARD_BIAS_SCALE, isForwardBlocked, isDodgeClear, clampVy).
  13. Build verification (3 checks: exit 0, BUILD SUCCESSFUL, no error:).
  All 60/60 pass after fixing 4 false positives: (a) count expected 5 but actual is 4 (constructor is a definition, not a call site — doesn't match `new SteerResult(new Vec3`). (b) 6-arg regex didn't handle `tallObstacle` and `goLeft`/`!goLeft` as boolean args (only matched literal true/false) — expanded alternation to include variable names. (c) vault step javadoc regex used `\s+detected` but text wraps across javadoc lines with `*` markers — fixed with `[\s\*]+`. (d) no-fabricated-citations regex used `\s+citations` but text wraps with `*` marker — fixed with `[\s\*]+`.
- STEP 11: Ran regression. CRON-134 (85/85). CRON-133 (73/73 after updating 5 checks to accept BOTH the old 5-arg and new 6-arg SteerResult forms — CRON-135 expanded the API; the CRON-133 invariants are still satisfied, just the arg count changed). CRON-130 (111/111). Total: 60 + 85 + 73 + 111 = 329 checks across 4 scripts. No regressions.
- STEP 12: Bumped version 0.1.10-alpha → 0.1.11-alpha (gradle.properties + mods.toml). Built JAR: build/libs/ergenverse-0.1.11-alpha.jar (8.8 MB). Copied to /home/z/my-project/download/ and releases/.
- STEP 13: Build verification — JAVA_HOME=/tmp/my-project/.jdks/jdk-17.0.13+11/ ./gradlew build — BUILD SUCCESSFUL in 21s, 0 errors, 28 pre-existing deprecation warnings (ResourceLocation constructor — unchanged from CRON-134).
- STEP 14: Git workflow — git add -A (7 files: CultivatorFlightNavigator.java, gradle.properties, mods.toml, worklog.md [includes CRON-135 entry], cron135_verify_upward_raycast.py [new], cron133_verify_flight_path_navigator.py [script fix for 6-arg SteerResult], ergenverse-0.1.11-alpha.jar [new]). git commit + push.

Stage Summary:
- SHIPPED: CRON-COMPLETIONIST-135 closes CRON-133 self-critique #5 — cultivator sword-flight (御剑飞行) no longer flies into tall obstacles (mountainsides, cliffs, towers). The CultivatorFlightNavigator now ray-casts forward at 3 UPWARD height offsets (+3/+6/+9 above entity Y) in addition to the existing 3 body-height offsets (0.5/1.0/1.5). When the upward ray-cast detects a tall obstacle, the cultivator vaults with a STRONGER impulse (TALL_VAULT_SPEED_SCALE=1.2D vs standard VAULT_SPEED_SCALE=0.8D, +50% more upward velocity) to clear it. During dodge, the upward bias is DOUBLED for tall obstacles (DODGE_UPWARD_BIAS_SCALE * 2.0D) so the dodge also gains altitude. The SteerResult gained a `tallObstacle` flag (6-arg constructor, up from 5) so the goal can log/track tall-obstacle encounters. Canon fidelity: cultivators fly OVER mountains and around cliffs (universally attested in 仙逆) — the upward ray-cast makes this visually correct in Minecraft's voxel world. NO fabricated chapter citations.
- Build status: BUILD SUCCESSFUL in 21s, 0 errors, 28 pre-existing deprecation warnings.
- Git hash: <filled after commit> (pushed to stohco/projectevergreen/main).
- Verification: scripts/cron135_verify_upward_raycast.py — 60/60 pass. CRON-134 (85/85), CRON-133 (73/73 after script update for 6-arg SteerResult), CRON-130 (111/111). Total: 329 checks across 4 scripts.
- Canon sources: 御剑飞行 (sword flight) universally attested in 仙逆 as flying OVER mountains and around cliffs, never phasing through them. Foundation Establishment (筑基) is the canonical minimum realm (Baidu Baike-verified in CRON-130). The specific upward-offset values (+3/+6/+9) and TALL_VAULT_SPEED_SCALE (1.2D) are mod-original infrastructure required to make canon-faithful straight-line flight visually correct in Minecraft's voxel world. NO fabricated chapter citations.

- HARSH SELF-CRITIQUE (hyper-analytical, fact-checked against canon):
  1. **No runtime playtest verification (carried over from every prior CRON).** 60 static checks prove the upward ray-cast is correctly wired at the source-code level. None prove a Foundation+ cultivator actually vaults over a mountain at runtime. Specifically untested: (a) does the upward ray-cast at +9 actually detect a mountainside, or does the mountainside start higher (e.g., +12)? (b) does TALL_VAULT_SPEED_SCALE=1.2D produce enough upward velocity to clear a 9-block obstacle in the 7.5-tick warning window? (0.48 blocks/tick * 7.5 ticks = 3.6 blocks — only enough to clear a 3-block obstacle, not a 9-block one). (c) does the doubled upward bias during dodge actually help, or does it make the dodge arc too steep? Score 4/10 for runtime validation (NEEDS PLAYTESTING).
  2. **The TALL_VAULT_SPEED_SCALE=1.2D is INSUFFICIENT for tall obstacles.** At cruise speed 0.4, the tall vault produces 0.4 * 1.2 = 0.48 blocks/tick upward. The upward ray-cast detects obstacles up to +9 above entity Y. To clear a +9 obstacle, the cultivator needs to gain 9 blocks of altitude. At 0.48 blocks/tick, that's 19 ticks (~1 second). But the cultivator is also moving forward at 0.4 * 0.3 = 0.12 blocks/tick (VAULT_FORWARD_SCALE), so in 19 ticks they move 2.3 blocks forward — well within the LOOKAHEAD=3 distance. So the cultivator WILL crash into the obstacle before clearing it. The math: to clear a +9 obstacle with LOOKAHEAD=3, the cultivator needs to gain 9 blocks in 7.5 ticks (LOOKAHEAD / cruise_speed = 3 / 0.4) = 1.2 blocks/tick upward — that's 3x the current TALL_VAULT_SPEED_SCALE. Score 3/10 for tall-obstacle clearance (insufficient vault impulse for +9 obstacles).
  3. **The +9 upward sample may be too high to be useful.** At cruise altitude (surface+4), +9 above entity = surface+13. Most mountain leading edges in the village biome are below surface+13 (the village is in a plains/forest biome, not mountainous). The +9 sample may rarely trigger, making it dead weight. The +3 and +6 samples are more likely to catch real obstacles (sect walls, gatehouses, watchtowers). Score 6/10 for sample calibration (likely correct for village biome, untested for mountain biomes).
  4. **No UPWARD ray-cast DURING dodge.** The dodge path probes perpendicular at chest height (Y+1.0) only. If the cultivator dodges left to avoid a forward obstacle, but the left path has a TALL obstacle (e.g., a mountainside curving left), the dodge probe returns 'clear' (chest height is below the mountainside's leading edge) and the cultivator dodges INTO the mountainside. The forward + upward ray-casts only check the FORWARD direction, not the dodge directions. A future CRON should add upward probes to isDodgeClear. Score 5/10 for dodge path safety (forward-only upward check, dodge paths uncheck).
  5. **The doubled upward bias during dodge (DODGE_UPWARD_BIAS_SCALE * 2.0D = 0.3) is MODEST.** At cruise speed 0.4, the doubled bias produces 0.4 * 0.3 = 0.12 blocks/tick upward. Over 7.5 ticks of dodge, that's 0.9 blocks of altitude gain — barely enough to clear a 1-block obstacle. The dodge is primarily a HORIZONTAL evasion; the upward bias is a minor assist. For tall obstacles, the cultivator should probably vault (not dodge) to gain altitude quickly. The current logic prefers dodge over vault (dodge is checked first), which may be wrong for tall obstacles. Score 5/10 for tall-obstacle dodge strategy (modest upward bias, dodge-preferred over vault).
  6. **No DOWNWARD ray-cast.** The navigator checks forward and upward, but not downward. A cultivator flying at cruise altitude (surface+4) toward a canyon or valley will not detect the canyon edge — they'll fly over it and then descend gradually via the cruise-altitude logic. This is acceptable (canyons are not obstacles), but a cultivator flying LOW (below cruise altitude, e.g., chasing a target into a valley) could fly into the canyon wall on the opposite side. The forward ray-cast at 0.5/1.0/1.5 would catch this, but only if the cultivator is at the canyon's elevation. Score 7/10 for downward awareness (acceptable, edge case only).
  7. **The SteerResult API change (5→6 args) broke CRON-133's verification script.** Discovered during regression — CRON-133's script checked for the old 5-arg constructor and return statements. Fixed by updating CRON-133's script to accept BOTH forms (the CRON-133 invariants are still satisfied; only the arg count changed). This is the second time a CRON-133 script has needed updating (CRON-134 also updated it for the stop() body extraction). Score 5/10 for API stability (breaking change, but script updated).
  8. **No qi-cost interaction with the upward ray-cast.** The upward ray-cast triggers more vaults (tall obstacles), and each vault is a flight tick that costs 0.2 qi (CRON-134). A cultivator flying through mountainous terrain will exhaust qi FASTER than one flying over plains (more vaults per unit distance). This is canon-intuitive (mountainous flight is more taxing) but unverified. Score 7/10 for canon interaction (intuitive, unverified).
  9. **The 'tallObstacle' flag is not used by the goal for logging.** The goal logs `blocked`, `dodgedLeft`, `dodgedRight`, `vaulted` but not `tallObstacle`. A cultivator encountering a mountain will log 'blocked' but the player can't distinguish 'short wall' from 'mountainside' in the logs. Minor — the flag is available for future use. Score 8/10 for observability (flag available, not yet logged).
  10. **No fabricated chapter citations.** The upward ray-cast is mod-original infrastructure (Minecraft voxel world requires collision logic that the novel does not describe). The canon fact is 'cultivators fly over mountains, not through them' — universally attested. NO 'RI Ch.X' citations invented. Score 10/10 for citation honesty.
  11. **The user is playtesting CRON-131/132/133/134 RIGHT NOW and CRON-135 is NOT in their playtest build.** The user imported ergenverse-0.1.7-alpha.jar (CRON-131). CRON-132/133/134/135 shipped 0.1.8/0.1.9/0.1.10/0.1.11-alpha — the user will need to re-import to see all four rounds of improvements. The window between 'user imports 0.1.7' and 'user imports 0.1.11' may include a playtest where the user sees a cultivator fly into a mountain (the bug CRON-135 fixes). Score 5/10 for immediate playtest impact (deferred until user re-imports).

- NEXT PRIORITY (in order, post-CRON-135):
  (a) **Playtest CRON-131 + CRON-132 + CRON-133 + CRON-134 + CRON-135 end-to-end (Score 10/10, CRITICAL — user is actively playtesting).** The user needs to re-import 0.1.11-alpha to see all improvements. Playtest checklist: (1) create a new world, (2) verify spawn at village plaza, (3) verify village materialized, (4) verify Wang Lin nearby, (5) [CRON-132] spawn a hostile mob >18 blocks from a Foundation+ cultivator, observe flight + ride_sword visible, (6) [CRON-133] position the cultivator's flight path through a tree/forest, observe cultivator dodging or vaulting instead of clipping, (7) [CRON-134] let the cultivator fly for ~25 seconds (Foundation), observe forced landing when qi runs out, (8) [CRON-135] position the cultivator's flight path toward a mountain or tall cliff, observe cultivator vaulting with the stronger TALL_VAULT_SPEED_SCALE impulse instead of crashing into the mountainside. Score 10/10 for runtime validation.
  (b) **Increase TALL_VAULT_SPEED_SCALE from 1.2D to 3.0D (Score 8/10, HIGH CORRECTNESS, fixes CRON-135 self-critique #2).** The current 1.2D is insufficient for +9 obstacles (gains only 3.6 blocks in 7.5 ticks, needs 9). 3.0D would gain 9 blocks in 7.5 ticks — exactly enough to clear a +9 obstacle. Score 8/10 for tall-obstacle clearance. Score 1/10 for implementation difficulty.
  (c) **Add upward probe to isDodgeClear (Score 7/10, HIGH CORRECTNESS, fixes CRON-135 self-critique #4).** Probe perpendicular at chest height AND at +3/+6 above entity Y. Cultivator no longer dodges INTO a mountainside. Score 7/10 for dodge path safety. Score 3/10 for implementation difficulty.
  (d) **Add qi cost to CultivatorSwordQiGoal (Score 7/10, HIGH CANON COMPLETENESS, carried over from CRON-134 #8).** Ranged sword-qi projectiles should consume qi. Score 7/10 for canon completeness. Score 3/10 for implementation difficulty.
  (e) **Add qi-bar overlay when player targets an NPC (Score 7/10, HIGH PLAYER FEEDBACK, carried over from CRON-134 #10).** Render a qi bar above the cultivator's head when the player's crosshair targets them. Score 7/10 for player feedback. Score 5/10 for implementation difficulty.
  (f) **Scale qi regen rate with realm (Score 6/10, MEDIUM BALANCE, carried over from CRON-134 #5).** Foundation=1.0/sec, Core=5.0/sec, Nascent=20.0/sec, Soul+=100.0/sec. Score 6/10 for balance. Score 2/10 for implementation difficulty.
  (g) **Increase LOOKAHEAD from 3.0 to 5.0 (Score 6/10, MEDIUM SAFETY, carried over from CRON-133 #4).** Doubles the dodge displacement margin from 2.1 to 3.5 blocks. Score 6/10 for safety. Score 1/10 for implementation difficulty.
"""

paths = [
    Path("/home/z/my-project/worklog.md"),
    Path("/home/z/my-project/forge-mod/worklog.md"),
]
for p in paths:
    with p.open("a", encoding="utf-8") as f:
        f.write(ENTRY)
    print(f"Appended CRON-135 entry to {p} ({p.stat().st_size} bytes)")
