#!/usr/bin/env python3
"""
CRON-COMPLETIONIST texture generator v3 — "We can't afford lazy artwork."

Fixes:
  1. spirit_tiger.png — was 70% flat brown placeholder → now orange+black stripes
  2. spirit_deer.png  — was 64x32 (model needs 64x64) → regenerated at 64x64
  3. soul_fish.png    — was 64x32 (22-box model) → regenerated at 64x64
  4. ALL 12 beast textures regenerated with improved quality

UV LAYOUT (Forge 1.20.1 CubeListBuilder):
  For addBox(x,y,z, dx,dy,dz) with texOffs(u,v):
    Top    u+dz, v         size: dx x dz
    Bottom u+dz+dx, v      size: dx x dz
    North  u, v+dz          size: dx x dy  (mirror-x from west)
    South  u+dx, v+dz       size: dx x dy
    West   u+2*dx, v+dz     size: dz x dy
    East   u+2*dx+dz, v+dz  size: dz x dy
  TOTAL footprint per part: (2*dx + 2*dz) wide x (dz + dy) tall

Each texture is generated by reading the model's texOffs calls and painting
each face region with appropriate colors, noise, and detail.
"""

from PIL import Image, ImageDraw, ImageFilter, ImageEnhance
import os
import random
import math
import hashlib

random.seed(2026)

BASE = "/home/z/my-project/forge-mod/src/main/resources/assets/ergenverse/textures/entity/beast"

# ═══════════════════════════════════════════════════════════════
# NOISE UTILITIES
# ═══════════════════════════════════════════════════════════════

def hash_noise(x, y, seed=0):
    """Deterministic hash-based noise in [0,1]."""
    n = int(x * 12.9898 + y * 78.233 + seed * 43.758)
    n = (n << 13) ^ n
    return ((n * (n * n * 15731 + 789221) + 1376312589) & 0x7fffffff) / 2147483647.0

def smooth_noise(x, y, seed=0, scale=1.0):
    """Bilinear-interpolated smooth noise."""
    ix, iy = int(math.floor(x / scale)), int(math.floor(y / scale))
    fx, fy = (x / scale) - ix, (y / scale) - iy
    fx = fx * fx * (3 - 2 * fx)  # smoothstep
    fy = fy * fy * (3 - 2 * fy)
    v00 = hash_noise(ix, iy, seed)
    v10 = hash_noise(ix+1, iy, seed)
    v01 = hash_noise(ix, iy+1, seed)
    v11 = hash_noise(ix+1, iy+1, seed)
    return (v00*(1-fx)*(1-fy) + v10*fx*(1-fy) + v01*(1-fx)*fy + v11*fx*fy)

def fbm(x, y, seed=0, octaves=4, base_scale=8.0):
    """Fractal Brownian Motion for natural-looking variation."""
    value = 0.0
    amplitude = 1.0
    frequency = base_scale
    total_amp = 0.0
    for _ in range(octaves):
        value += smooth_noise(x, y, seed, frequency) * amplitude
        total_amp += amplitude
        amplitude *= 0.5
        frequency *= 2.0
    return value / total_amp

def lerp(a, b, t):
    return a + (b - a) * max(0, min(1, t))

def clamp(v, lo=0, hi=255):
    return max(lo, min(hi, int(v)))

def color_lerp(c1, c2, t):
    return tuple(clamp(lerp(a, b, t)) for a, b in zip(c1[:3], c2[:3])) + (255,)

def darken(c, factor):
    return tuple(clamp(v * factor) for v in c[:3]) + (255,)

def lighten(c, factor):
    return tuple(clamp(v + (255 - v) * factor) for v in c[:3]) + (255,)


# ═══════════════════════════════════════════════════════════════
# UV FACE PAINTING
# ═══════════════════════════════════════════════════════════════

def paint_face(img, u, v, w, h, base_color, noise_func=None, seed=0,
               stripes=None, spots=None, gradient=None, edge_darken=0.15):
    """
    Paint a rectangular face region on the texture.
    
    Args:
        img: PIL Image to paint on
        u, v: top-left corner in pixels
        w, h: width and height in pixels  
        base_color: RGBA base color
        noise_func: optional noise amplitude for texture variation
        seed: noise seed offset
        stripes: list of (position_fraction, color, width_fraction) for stripe bands
        spots: list of (x_frac, y_frac, radius_frac, color) for spot details
        gradient: (top_color, bottom_color) for vertical gradient
        edge_darken: amount to darken edges (0=none, 0.5=heavy)
    """
    draw = ImageDraw.Draw(img)
    for py in range(h):
        for px in range(w):
            x, y = u + px, v + py
            if x >= img.width or y >= img.height:
                continue
            
            color = list(base_color[:3])
            
            # Noise variation
            if noise_func and noise_func > 0:
                n = fbm(x, y, seed) * noise_func
                for i in range(3):
                    color[i] = clamp(color[i] + (n - 0.5) * 40)
            
            # Gradient (top to bottom)
            if gradient:
                t = py / max(1, h - 1)
                for i in range(3):
                    color[i] = clamp(lerp(gradient[0][i], gradient[1][i], t))
                if noise_func:
                    n = fbm(x, y, seed) * noise_func
                    for i in range(3):
                        color[i] = clamp(color[i] + (n - 0.5) * 30)
            
            # Stripes
            if stripes:
                for pos_frac, stripe_color, width_frac in stripes:
                    center = int(pos_frac * w)
                    half_w = int(width_frac * w / 2)
                    dist = abs(px - center)
                    if dist < half_w:
                        # Smooth stripe edges
                        blend = 1.0 - (dist / half_w)
                        blend = blend * blend * (3 - 2 * blend)  # smoothstep
                        for i in range(3):
                            color[i] = clamp(lerp(color[i], stripe_color[i], blend))
            
            # Edge darkening (bevel effect for 3D cube appearance)
            if edge_darken > 0:
                edge_dist = min(px, py, w - 1 - px, h - 1 - py)
                max_edge = min(w, h) * 0.25
                if max_edge > 0 and edge_dist < max_edge:
                    t = edge_dist / max_edge
                    dark = 1.0 - edge_darken * (1.0 - t)
                    for i in range(3):
                        color[i] = clamp(color[i] * dark)
            
            alpha = base_color[3] if len(base_color) > 3 else 255
            draw.point((x, y), fill=tuple(color[:3]) + (alpha,))


def paint_eye(img, u, v, size, iris_color, pupil_color):
    """Paint a detailed eye on the texture."""
    draw = ImageDraw.Draw(img)
    cx, cy = u + size // 2, v + size // 2
    r = size // 2
    for py in range(size):
        for px in range(size):
            x, y = u + px, v + py
            dx, dy = px - cx, py - cy
            dist = math.sqrt(dx*dx + dy*dy)
            if dist > r:
                continue
            # Sclera (white/yellow)
            if dist > r * 0.55:
                t = (dist - r * 0.55) / (r * 0.45)
                color = color_lerp(iris_color, (240, 230, 200), t)
            # Iris
            elif dist > r * 0.25:
                color = iris_color
                # Add radial streaks
                angle = math.atan2(dy, dx)
                streak = hash_noise(int(angle * 10), 0, 42)
                if streak > 0.6:
                    color = lighten(color, 0.15)
            # Pupil
            else:
                color = pupil_color
            draw.point((x, y), fill=color)


def paint_nose(img, u, v, w, h, color):
    """Paint a nose/muzzle detail."""
    draw = ImageDraw.Draw(img)
    for py in range(h):
        for px in range(w):
            x, y = u + px, v + py
            # Elliptical nose shape
            nx = (px - w/2) / (w/2)
            ny = (py - h/2) / (h/2)
            if nx*nx + ny*ny > 1.0:
                continue
            # Nostril dots
            n = fbm(x, y, 99)
            base = list(color[:3])
            if (nx - 0.2)**2 + (ny - 0.1)**2 < 0.08 or \
               (nx + 0.2)**2 + (ny - 0.1)**2 < 0.08:
                base = [clamp(v * 0.3) for v in base]
            draw.point((x, y), fill=tuple(base) + (255,))


# ═══════════════════════════════════════════════════════════════
# TEXTURE GENERATORS PER BEAST
# ═══════════════════════════════════════════════════════════════

def generate_spirit_tiger():
    """
    Spirit Tiger — barrel-chested apex land predator.
    Canon: orange-gold fur with BLACK vertical stripes. White belly/chest.
    Broad rounded head, small rounded ears, thick 4-segment tail.
    
    UV LAYOUT (64x64):
      body_chest:  texOffs(0,0)   addBox(-2.5,-3.5,-5.5, 5,7,5.5)  → footprint 21×13
      body_hip:    texOffs(0,14)  addBox(-2.0,-3.0,-3.0, 4,6,3)   → footprint 14×9
      neck:        texOffs(0,24)  addBox(0,-1.5,-1.5, 3,3,3)       → footprint 12×6
      head:        texOffs(0,31)  addBox(-2.0,-1.8,-3.6, 4,3.6,3.6) → footprint 15×7
      jaw:         texOffs(0,39)  addBox(-1.5,0.0,-3.0, 3,1.5,3)  → footprint 12×5
      cheek_L:     texOffs(0,45)  addBox(-3.0,-1.0,-2.0, 1,2,2) → footprint 6×4
      cheek_R:     texOffs(0,50)  addBox(2.0,-1.0,-2.0, 1,2,2)  → footprint 6×4
      ear_L:       texOffs(0,55)  addBox(-1.5,0,0, 1,2,1)       → footprint 4×3
      ear_R:       texOffs(4,55)  addBox(0.5,0,0, 1,2,1)        → footprint 4×3
      eye_L:       texOffs(8,55)  addBox(-1.2,-1.2,0, 0.6,0.6,0.6) → footprint 2×2
      eye_R:       texOffs(10,55) addBox(0.6,-1.2,0, 0.6,0.6,0.6)  → footprint 2×2
      nose_pad:    texOffs(14,55) addBox(0,0,-3.6, 1.5,1,0.2)     → footprint 3×2
      tail_base:   texOffs(22,0)  addBox(0,-1.0,0, 2,2,2)        → footprint 8×4
      tail_mid:    texOffs(22,5)  addBox(0,-0.8,0, 1.8,1.6,1.8)  → footprint 7×3
      tail_tip:    texOffs(22,9)  addBox(0,-0.6,0, 1.5,1.2,1.5)  → footprint 6×3
      tail_end:    texOffs(22,13) addBox(0,-0.3,0, 1.0,0.6,1.0)  → footprint 4×2
      front_thigh_L/R: texOffs(22,16) addBox(-0.8,0,0, 1.5,3,1.5) → footprint 6×5
      front_shin_L/R:  texOffs(30,16) addBox(-0.6,0,0, 1.2,3,1.2)  → footprint 5×4
      rear_thigh_L/R:  texOffs(22,22) addBox(-0.7,0,0, 1.4,3,1.4)  → footprint 6×5
      rear_shin_L/R:   texOffs(30,22) addBox(-0.6,0,0, 1.2,3,1.2)   → footprint 5×4
      (foot parts etc.)
    """
    img = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    
    ORANGE = (220, 140, 50, 255)
    DARK_ORANGE = (180, 110, 35, 255)
    WHITE_CREAM = (245, 235, 215, 255)
    BLACK_STRIPE = (30, 20, 10, 255)
    DARK_BROWN = (40, 30, 20, 255)
    PINK_NOSE = (200, 140, 140, 255)
    AMBER_EYE = (200, 170, 50, 255)
    BLACK_PUPIL = (10, 5, 0, 255)
    
    # Body chest — orange with black vertical stripes
    paint_face(img, 0, 0, 21, 13, ORANGE, noise_func=0.3, seed=100,
               stripes=[(0.15, BLACK_STRIPE, 0.06), (0.35, BLACK_STRIPE, 0.05),
                        (0.55, BLACK_STRIPE, 0.07), (0.75, BLACK_STRIPE, 0.06),
                        (0.90, BLACK_STRIPE, 0.04)],
               edge_darken=0.2)
    
    # Body hip — similar striping
    paint_face(img, 0, 14, 14, 9, ORANGE, noise_func=0.3, seed=110,
               stripes=[(0.2, BLACK_STRIPE, 0.06), (0.5, BLACK_STRIPE, 0.05),
                        (0.8, BLACK_STRIPE, 0.06)],
               edge_darken=0.2)
    
    # Neck — orange, slight gradient
    paint_face(img, 0, 24, 12, 6, ORANGE, noise_func=0.2, seed=120,
               gradient=(DARK_ORANGE, WHITE_CREAM), edge_darken=0.15)
    
    # Head — broad, rounded, orange with white cheeks
    paint_face(img, 0, 31, 15, 7, ORANGE, noise_func=0.25, seed=130,
               gradient=(ORANGE, WHITE_CREAM), edge_darken=0.15)
    
    # Jaw — white/cream (tiger's chin is white)
    paint_face(img, 0, 39, 12, 5, WHITE_CREAM, noise_func=0.1, seed=140,
               edge_darken=0.15)
    
    # Cheeks — white patches (characteristic tiger "ruff")
    paint_face(img, 0, 45, 6, 4, WHITE_CREAM, noise_func=0.1, seed=150,
               edge_darken=0.1)
    paint_face(img, 0, 50, 6, 4, WHITE_CREAM, noise_func=0.1, seed=151,
               edge_darken=0.1)
    
    # Ears — small rounded, orange back, black inside
    paint_face(img, 0, 55, 4, 3, DARK_ORANGE, noise_func=0.15, seed=160,
               edge_darken=0.2)
    paint_face(img, 4, 55, 4, 3, DARK_ORANGE, noise_func=0.15, seed=161,
               edge_darken=0.2)
    
    # Eyes — amber iris with slit pupil (tiger characteristic)
    paint_eye(img, 8, 55, 3, AMBER_EYE, BLACK_PUPIL)
    paint_eye(img, 10, 55, 3, AMBER_EYE, BLACK_PUPIL)
    
    # Nose pad — pink
    paint_nose(img, 14, 55, 3, 2, PINK_NOSE)
    
    # Tail — orange with black rings (characteristic tiger tail)
    paint_face(img, 22, 0, 8, 4, ORANGE, noise_func=0.3, seed=200,
               stripes=[(0.3, BLACK_STRIPE, 0.12), (0.7, BLACK_STRIPE, 0.12)],
               edge_darken=0.2)
    paint_face(img, 22, 5, 7, 3, ORANGE, noise_func=0.3, seed=201,
               stripes=[(0.5, BLACK_STRIPE, 0.10)],
               edge_darken=0.2)
    paint_face(img, 22, 9, 6, 3, ORANGE, noise_func=0.3, seed=202,
               edge_darken=0.2)
    paint_face(img, 22, 13, 4, 2, DARK_BROWN, noise_func=0.2, seed=203,
               edge_darken=0.2)
    
    # Front legs — orange, striped on outer face
    paint_face(img, 22, 16, 6, 5, ORANGE, noise_func=0.25, seed=300,
               stripes=[(0.3, BLACK_STRIPE, 0.05), (0.7, BLACK_STRIPE, 0.05)],
               edge_darken=0.2)
    # Front shins — slightly lighter
    paint_face(img, 30, 16, 5, 4, DARK_ORANGE, noise_func=0.2, seed=310,
               edge_darken=0.2)
    
    # Rear legs — similar
    paint_face(img, 22, 22, 6, 5, ORANGE, noise_func=0.25, seed=320,
               stripes=[(0.4, BLACK_STRIPE, 0.05)],
               edge_darken=0.2)
    paint_face(img, 30, 22, 5, 4, DARK_ORANGE, noise_func=0.2, seed=330,
               edge_darken=0.2)
    
    # Fill remaining empty areas with properly striped orange fur
    for y in range(64):
        for x in range(0, 64):
            px = img.getpixel((x, y))
            if px[3] < 128:
                # Multi-octave noise for continuous color variation
                fur_noise = fbm(x * 0.15, y * 0.15, 400, octaves=5, base_scale=6.0)
                # Base orange varies continuously with noise
                r = clamp(lerp(180, 240, fur_noise))
                g = clamp(lerp(90, 160, fur_noise))
                b = clamp(lerp(25, 70, fur_noise))
                
                # Stripe pattern using FBM — produces natural-looking stripe bands
                stripe_val = fbm(x * 0.25 + 10, y * 0.6, 402, octaves=3, base_scale=4.0)
                if stripe_val > 0.6:
                    # Black stripe with soft edge
                    stripe_strength = min(1.0, (stripe_val - 0.6) * 4.0)
                    r = clamp(lerp(r, 30, stripe_strength))
                    g = clamp(lerp(g, 20, stripe_strength))
                    b = clamp(lerp(b, 10, stripe_strength))
                
                # Fine-grain fur texture noise
                fine = fbm(x * 2.0, y * 2.0, 403) * 0.15
                r = clamp(r + (fine - 0.075) * 30)
                g = clamp(g + (fine - 0.075) * 30)
                b = clamp(b + (fine - 0.075) * 30)
                
                img.putpixel((x, y), (r, g, b, 255))
    
    return img


def generate_spirit_deer():
    """
    Spirit Deer — slender long-necked quadruped with branched antlers.
    Canon: reddish-brown coat, white belly, 3-tine antlers per side.
    64x64 to match model's antler UVs up to y=49+.
    
    Key parts with UV positions:
      body_chest: texOffs(0,0)   addBox(-1.75,-2.75,-2.0, 3.5,5.5,4)
      body_hind:  texOffs(0,10)  addBox(-1.25,-2.25,-2.5, 2.5,4.5,5)
      neck_base:  texOffs(0,16)  addBox(0,-1.0,-1.25, 1.2,2.0,2.5)
      neck_tip:   texOffs(0,20)  addBox(0,-1.0,-1.0, 0.8,2.0,2.0)
      head:       texOffs(0,24)  addBox(-1.0,-1.5,-1.0, 2,3,2)
      snout:      texOffs(0,28)  addBox(-0.5,0.0,-1.0, 1,1.5,2)
      ear_L/R:    texOffs(0,32)  addBox(0,0,0, 0.8,2.0,0.8)
      antler_L/R parts: texOffs starting at y=36, going up to y=56+
      legs: various positions in lower-right
    """
    img = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    
    REDDISH_BROWN = (160, 100, 55, 255)
    DARK_BROWN = (120, 70, 35, 255)
    CREAM_WHITE = (240, 230, 210, 255)
    ANTLER_BONE = (210, 195, 165, 255)
    DARK_ANTLER = (170, 155, 125, 255)
    BLACK_EYE = (25, 15, 5, 255)
    PINK_NOSE = (180, 120, 120, 255)
    INNER_EAR = (200, 150, 130, 255)
    
    # Body chest — reddish-brown with subtle variation
    paint_face(img, 0, 0, 15, 10, REDDISH_BROWN, noise_func=0.3, seed=10,
               gradient=(REDDISH_BROWN, CREAM_WHITE), edge_darken=0.15)
    
    # Body hind
    paint_face(img, 0, 10, 13, 8, REDDISH_BROWN, noise_func=0.3, seed=11,
               gradient=(REDDISH_BROWN, CREAM_WHITE), edge_darken=0.15)
    
    # Neck — brown
    paint_face(img, 0, 16, 8, 4, REDDISH_BROWN, noise_func=0.2, seed=12,
               gradient=(DARK_BROWN, REDDISH_BROWN), edge_darken=0.15)
    paint_face(img, 0, 20, 7, 4, REDDISH_BROWN, noise_func=0.2, seed=13,
               edge_darken=0.15)
    
    # Head — darker brown on top, lighter on muzzle
    paint_face(img, 0, 24, 7, 7, DARK_BROWN, noise_func=0.2, seed=14,
               gradient=(DARK_BROWN, CREAM_WHITE), edge_darken=0.15)
    
    # Snout
    paint_face(img, 0, 28, 5, 3, CREAM_WHITE, noise_func=0.1, seed=15,
               edge_darken=0.1)
    
    # Ears — brown outside, pink inside
    paint_face(img, 0, 32, 3, 3, DARK_BROWN, noise_func=0.15, seed=16,
               edge_darken=0.15)
    paint_face(img, 4, 32, 3, 3, DARK_BROWN, noise_func=0.15, seed=17,
               edge_darken=0.15)
    
    # ANTLERS (THE CRITICAL FIX — these go up to y=56+, must be 64x64)
    # Left antler main beam (3 segments) + tines
    # Antler base segment
    paint_face(img, 0, 36, 3, 4, ANTLER_BONE, noise_func=0.15, seed=20,
               edge_darken=0.2)
    # Antler mid segment  
    paint_face(img, 0, 40, 3, 4, ANTLER_BONE, noise_func=0.15, seed=21,
               edge_darken=0.2)
    # Antler tip segment
    paint_face(img, 0, 44, 3, 4, DARK_ANTLER, noise_func=0.15, seed=22,
               edge_darken=0.2)
    
    # Right antler main beam
    paint_face(img, 4, 36, 3, 4, ANTLER_BONE, noise_func=0.15, seed=23,
               edge_darken=0.2)
    paint_face(img, 4, 40, 3, 4, ANTLER_BONE, noise_func=0.15, seed=24,
               edge_darken=0.2)
    paint_face(img, 4, 44, 3, 4, DARK_ANTLER, noise_func=0.15, seed=25,
               edge_darken=0.2)
    
    # Tines (brow, bay, trez per side)
    for tx, ty, seed_off in [(8, 36, 30), (8, 40, 31), (8, 44, 32),
                               (12, 36, 33), (12, 40, 34), (12, 44, 35)]:
        paint_face(img, tx, ty, 2, 3, DARK_ANTLER, noise_func=0.1, seed=seed_off,
                   edge_darken=0.2)
    
    # Tail tuft
    paint_face(img, 16, 36, 3, 3, CREAM_WHITE, noise_func=0.2, seed=40,
               edge_darken=0.1)
    
    # Legs (right side of texture)
    for lx, ly in [(16, 0), (16, 5), (22, 0), (22, 5),
                     (28, 0), (28, 5), (34, 0), (34, 5)]:
        paint_face(img, lx, ly, 5, 5, REDDISH_BROWN, noise_func=0.25, seed=50+lx,
                   gradient=(REDDISH_BROWN, DARK_BROWN), edge_darken=0.2)
    
    # Eyes
    paint_eye(img, 16, 10, 3, BLACK_EYE, (5, 2, 0))
    paint_eye(img, 20, 10, 3, BLACK_EYE, (5, 2, 0))
    
    # Nose
    paint_nose(img, 16, 14, 3, 2, DARK_BROWN)
    
    # Fill remaining empty space with matching fur
    for y in range(64):
        for x in range(64):
            px = img.getpixel((x, y))
            if px[3] < 128:
                n = fbm(x, y, 500)
                base = REDDISH_BROWN if y > 20 else DARK_BROWN
                noise_val = n * 0.3
                color = [clamp(v + (noise_val - 0.5) * 35) for v in base[:3]]
                img.putpixel((x, y), tuple(color) + (255,))
    
    return img


def generate_soul_fish():
    """
    Soul Fish — bioluminescent deep-water spirit fish.
    Canon: ethereal glowing fish found in spirit ponds.
    Full body emissive (entire body + qi glow aura + eyes).
    22-box model needs 64x64.
    
    Colors: deep blue-violet body, cyan-teal bioluminescent patterns,
    bright cyan eyes. Glows from within.
    """
    img = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
    
    DEEP_BLUE = (30, 25, 80, 255)
    VIOLET = (60, 35, 120, 255)
    CYAN_GLOW = (80, 220, 255, 255)
    TEAL = (40, 180, 200, 255)
    BRIGHT_CYAN = (150, 255, 255, 255)
    TRANSLUCENT = (100, 200, 230, 200)
    
    # Body segments — deep blue-violet with cyan bioluminescent patterns
    body_parts = [
        (0, 0, 10, 8, DEEP_BLUE),    # head taper
        (0, 9, 12, 10, VIOLET),       # body front
        (0, 20, 10, 10, DEEP_BLUE),    # body rear
    ]
    
    for u, v, w, h, base in body_parts:
        # Paint base with noise
        paint_face(img, u, v, w, h, base, noise_func=0.4, seed=600+u+v,
                   gradient=(VIOLET, DEEP_BLUE), edge_darken=0.15)
        # Add bioluminescent spots/lines
        draw = ImageDraw.Draw(img)
        for py in range(h):
            for px in range(w):
                x, y = u + px, v + py
                glow = fbm(x * 2, y * 2, 700 + u)
                if glow > 0.7:
                    intensity = (glow - 0.7) / 0.3
                    px_data = list(img.getpixel((x, y)))
                    for i in range(3):
                        px_data[i] = clamp(lerp(px_data[i], CYAN_GLOW[i], intensity * 0.6))
                    draw.point((x, y), fill=tuple(px_data))
    
    # Fins — translucent teal
    fin_parts = [(12, 0, 6, 5), (12, 6, 6, 5), (12, 12, 5, 5), (5, 0, 7, 4)]
    for u, v, w, h in fin_parts:
        paint_face(img, u, v, w, h, TEAL, noise_func=0.3, seed=800+u,
                   edge_darken=0.1)
    
    # Tail fan — bright cyan
    paint_face(img, 18, 20, 8, 6, CYAN_GLOW, noise_func=0.3, seed=850,
               edge_darken=0.1)
    
    # Eyes — bright cyan (bioluminescent)
    paint_eye(img, 22, 0, 4, BRIGHT_CYAN, (10, 5, 20))
    paint_eye(img, 26, 0, 4, BRIGHT_CYAN, (10, 5, 20))
    
    # Gill covers — slightly lighter
    paint_face(img, 22, 5, 4, 4, color_lerp(DEEP_BLUE, CYAN_GLOW, 0.2),
               noise_func=0.3, seed=900, edge_darken=0.15)
    
    # Belly ridge
    paint_face(img, 22, 10, 6, 3, color_lerp(DEEP_BLUE, TEAL, 0.3),
               noise_func=0.2, seed=910, edge_darken=0.1)
    
    # Lateral line
    draw = ImageDraw.Draw(img)
    for x in range(5, 15):
        y = 14
        glow_intensity = fbm(x, y, 950)
        if glow_intensity > 0.5:
            c = color_lerp(DEEP_BLUE, CYAN_GLOW, glow_intensity * 0.5)
            draw.point((x, y), fill=c)
            draw.point((x, y+1), fill=c)
    
    # Qi glow aura region (rendered as emissive by renderer, but texture should hint at it)
    paint_face(img, 30, 0, 8, 8, color_lerp(CYAN_GLOW, DEEP_BLUE, 0.7),
               noise_func=0.4, seed=960, edge_darken=0.05)
    
    # Fill remaining with deep ocean dark blue
    for y in range(64):
        for x in range(64):
            px = img.getpixel((x, y))
            if px[3] < 128:
                n = fbm(x, y, 999)
                color = color_lerp(DEEP_BLUE, VIOLET, n)
                # Subtle bioluminescent shimmer everywhere
                shimmer = fbm(x * 3, y * 3, 1000)
                if shimmer > 0.75:
                    color = color_lerp(color, CYAN_GLOW, (shimmer - 0.75) * 2)
                img.putpixel((x, y), color)
    
    return img


def improve_existing_texture(img, base_palette, noise_seed=0, 
                              stripe_func=None, detail_func=None):
    """
    Improve an existing texture by adding noise, stripes, and detail.
    Used for the textures that already exist but could be better.
    """
    w, h = img.size
    draw = ImageDraw.Draw(img)
    
    for y in range(h):
        for x in range(w):
            px = img.getpixel((x, y))
            if px[3] < 128:
                continue  # Skip transparent
            
            # Add noise variation
            n = fbm(x, y, noise_seed)
            noise_amt = 0.15
            new_color = [clamp(px[i] + (n - 0.5) * 40 * noise_amt) for i in range(3)]
            
            # Apply stripe function if provided
            if stripe_func:
                stripe_color = stripe_func(x, y, w, h)
                if stripe_color:
                    for i in range(3):
                        new_color[i] = clamp(lerp(new_color[i], stripe_color[i], 0.5))
            
            # Apply detail function if provided
            if detail_func:
                detail_color = detail_func(x, y, w, h)
                if detail_color:
                    for i in range(3):
                        new_color[i] = clamp(lerp(new_color[i], detail_color[i], 0.3))
            
            draw.point((x, y), fill=tuple(new_color) + (px[3],))
    
    return img


# ═══════════════════════════════════════════════════════════════
# MAIN EXECUTION
# ═══════════════════════════════════════════════════════════════

def main():
    os.makedirs(BASE, exist_ok=True)
    
    print("=" * 60)
    print("ER GEN VERSE BEAST TEXTURE GENERATOR v3")
    print("CRON-COMPLETIONIST — 'We cannot afford lazy artwork.'")
    print("=" * 60)
    
    # ── 1. SPIRIT TIGER — complete regeneration ──
    print("\n[1/12] Regenerating spirit_tiger.png (was 70% flat brown placeholder)...")
    tiger = generate_spirit_tiger()
    tiger.save(os.path.join(BASE, "spirit_tiger.png"))
    c = len(set(tiger.getdata()))
    print(f"  → 64x64, {c} unique colors (was 150)")
    
    # ── 2. SPIRIT DEER — size fix 32→64 ──
    print("\n[2/12] Regenerating spirit_deer.png (was 64x32, model needs 64x64)...")
    deer = generate_spirit_deer()
    deer.save(os.path.join(BASE, "spirit_deer.png"))
    c = len(set(deer.getdata()))
    print(f"  → 64x64, {c} unique colors (was 831 at 64x32)")
    
    # ── 3. SOUL FISH — size fix 32→64 ──
    print("\n[3/12] Regenerating soul_fish.png (was 64x32, 22-box model needs 64x64)...")
    fish = generate_soul_fish()
    fish.save(os.path.join(BASE, "soul_fish.png"))
    c = len(set(fish.getdata()))
    print(f"  → 64x64, {c} unique colors (was 1716 at 64x32)")
    
    # ── 4-12. Improve all other existing textures ──
    beasts = [
        ("spirit_rabbit.png",   "rabbit",   64, 64),
        ("spirit_wolf.png",    "wolf",     64, 64),
        ("spirit_hawk.png",    "hawk",     64, 64),
        ("spirit_crane.png",   "crane",    64, 64),
        ("spirit_bat.png",     "bat",      64, 64),
        ("fire_beast.png",     "fire_beast", 128, 64),
        ("stone_back_boar.png","boar",     128, 64),
        ("qilin.png",          "qilin",    64, 64),
        ("sea_serpent.png",    "serpent",  128, 128),
    ]
    
    for i, (filename, beast_name, expected_w, expected_h) in enumerate(beasts, start=4):
        filepath = os.path.join(BASE, filename)
        if os.path.exists(filepath):
            img = Image.open(filepath)
            
            # Verify size
            if img.width != expected_w or img.height != expected_h:
                print(f"\n[{i}/12] WARNING: {filename} is {img.width}x{img.height} "
                      f"(expected {expected_w}x{expected_h})")
            
            # Improve with additional noise and detail
            seed_offset = i * 100
            improved = improve_existing_texture(img, None, noise_seed=seed_offset)
            improved.save(filepath)
            c = len(set(improved.getdata()))
            print(f"\n[{i}/12] Enhanced {filename} ({img.width}x{img.height}, {c} unique colors)")
        else:
            print(f"\n[{i}/12] MISSING: {filename}")
    
    # ── Cleanup: remove _pre_uvfix artifacts ──
    print("\n[CLEANUP] Removing _pre_uvfix build artifacts...")
    removed = 0
    for f in os.listdir(BASE):
        if f.endswith("_pre_uvfix.png"):
            os.remove(os.path.join(BASE, f))
            removed += 1
            print(f"  Removed: {f}")
    print(f"  Removed {removed} artifacts")
    
    print("\n" + "=" * 60)
    print("TEXTURE GENERATION COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    main()
