// Generated by scripts/generate_registry_entries.py
// Append these register() calls to CanonicalInventory.doBootstrap()


        register(CanonicalEntry.of(
                "I05_five_sword_sheaths", "Five Sword Sheaths", "五把剑鞘",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("Ch. ~100-300"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The five sheaths that hold Wang Lin's signature flying swords. Each sheath has formation patterns.",
                List.of(
                        "Holds flying swords",
                        "Formation patterns carved on surface"
                ),
                List.of("sword", "sheath", "formation", "storage")
        ));


        register(CanonicalEntry.of(
                "I37_bronze_mirror", "Bronze Mirror / Time Domain", "铜镜/时间领域",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("Ch. ~800-1200"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "An ancient mirror artifact that can create time-domain effects. Used by Wang Lin in mid-to-late stages.",
                List.of(
                        "Creates time-domain effects",
                        "Ancient artifact of unknown origin"
                ),
                List.of("time", "domain", "artifact", "mirror")
        ));


        register(CanonicalEntry.of(
                "I49_soul_flag_soul_refining_sect", "Soul Flag (Soul Refining Sect)", "魂幡（炼魂宗）",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("early Nascent Soul"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A soul banner from the Soul Refining Sect. One of Wang Lin's early soul-type artifacts. Evolved into the Billion Soul Flag.",
                List.of(
                        "Captures souls of the slain",
                        "Soul Refining Sect standard equipment"
                ),
                List.of("soul", "flag", "refining", "sect")
        ));


        register(CanonicalEntry.of(
                "I82_seven_colored_nails", "Seven-Colored Nail (set)", "七彩钉",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("Ch. ~600-1082"), 5),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Set of nails forged from Seven-Colored Daoist's essence. Used as sealing weapons. Destroyed in battle, later restored by Wang Lin at Heaven Trampling.",
                List.of(
                        "Sealing/striking weapon",
                        "Seven-Colored Daoist's essence",
                        "Destroyed then restored at Heaven Trampling (Ch.1082→1626)"
                ),
                List.of("seven_colored", "seal", "weapon", "restoration")
        ));


        register(CanonicalEntry.of(
                "I76_celestial_spirit_clock", "Celestial Spirit Clock", "仙灵钟",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("mid-to-late RI"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A clock-type artifact with celestial spiritual properties. Used for temporal sensing.",
                List.of(
                        "Temporal sensing",
                        "Celestial spiritual properties"
                ),
                List.of("time", "celestial", "clock", "sensing")
        ));


        register(CanonicalEntry.of(
                "I90_dot_immortal_pen", "Dot Immortal Pen", "点仙笔",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("Restriction era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A pen artifact used to draw restrictions and formations. Wang Lin used it for restriction art.",
                List.of(
                        "Draws restrictions and formations",
                        "Restriction-art implement"
                ),
                List.of("restriction", "formation", "pen", "tool")
        ));


        register(CanonicalEntry.of(
                "I92_golden_print", "Golden Print", "金印",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("Nascent Soul era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A golden seal/print artifact. Used for authority and sealing purposes.",
                List.of(
                        "Sealing authority",
                        "Golden spiritual pressure"
                ),
                List.of("seal", "authority", "golden")
        ));


        register(CanonicalEntry.of(
                "I115_beast_skin_tattoo", "Beast Skin Tattoo", "兽皮刺青",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("Core Formation era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A tattoo carved on beast skin. Contains formation/restriction patterns for body enhancement.",
                List.of(
                        "Body enhancement patterns",
                        "Restriction-based tattoo art"
                ),
                List.of("tattoo", "formation", "body", "beast")
        ));


        register(CanonicalEntry.of(
                "I03_three_ink_stones", "Three Ink Stones", "三方墨石",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("Ch. ~180"), 5),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The three Ink Stones required for refining Restriction Flags. Obtained from the Land of the Ancient God trial.",
                List.of(
                        "Essential reagent for Restriction Flag refining",
                        "From the Land of the Ancient God"
                ),
                List.of("inkstone", "restriction", "ancient_god", "reagent")
        ));


        register(CanonicalEntry.of(
                "I100_infant_skull_da_yi", "Infant Skull (Da Yi)", "大妖婴儿头骨",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("Soul Formation era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A skull from the infant Da Yi. Used as a cultivation/sealing component.",
                List.of(
                        "Sealing component",
                        "Da Yi's remains"
                ),
                List.of("skull", "sealing", "da_yi", "remains")
        ));


        register(CanonicalEntry.of(
                "I65_three_battle_scrolls", "Three Battle Scrolls", "战字三卷",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("Nascent Soul era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Three scrolls containing battle techniques. Part of Wang Lin's tactical arsenal.",
                List.of(
                        "Battle technique scrolls",
                        "Tactical combat arts"
                ),
                List.of("scroll", "battle", "technique", "tactics")
        ));


        register(CanonicalEntry.of(
                "I40_human_shaped_armor", "Human-Shaped Armor (Green Bull)", "人形铠甲（青牛）",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("Soul Formation era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Armor shaped like a human figure, related to the Green Bull. Provides physical + spiritual defense.",
                List.of(
                        "Human-shaped defensive armor",
                        "Green Bull origin"
                ),
                List.of("armor", "defense", "green_bull")
        ));


        register(CanonicalEntry.of(
                "I160_dream_dao_mirror", "Dream Dao Mirror", "梦道镜",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("late RI"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A mirror related to the Dream Dao — one of Wang Lin's Original Spells. Reflects dream-based illusions.",
                List.of(
                        "Dream Dao implementation",
                        "Illusion reflection"
                ),
                List.of("dream_dao", "mirror", "illusion", "original_spell")
        ));


        register(CanonicalEntry.of(
                "AT01_red_lightning_ji_realm", "1st Accompanying Thunder (Ji Thunder)", "第一道伴雷（极雷）",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("Ch. ~1368"), 5),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The first of Wang Lin's 9 accompanying thunders — formed from his Ji Realm divine sense. Red lightning.",
                List.of(
                        "1st of 9 accompanying thunders",
                        "Formed from Ji Realm divine sense",
                        "Red lightning attribute"
                ),
                List.of("thunder", "accompanying", "ji_realm", "lightning")
        ));


        register(CanonicalEntry.of(
                "I60_blood_nascent_soul_seven_colored", "Blood Red Nascent Soul (Seven-Colored)", "血色元婴（七彩）",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("Nascent Soul era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Wang Lin's blood-red Nascent Soul, infused with Seven-Colored Daoist's essence.",
                List.of(
                        "Blood-red Nascent Soul",
                        "Seven-Colored infusion"
                ),
                List.of("nascent_soul", "blood", "seven_colored")
        ));


        register(CanonicalEntry.of(
                "I167_ancient_bloodline_ancestor", "Ancient Bloodline Ancestor", "远古血脉之祖",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("late RI"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Ancestral bloodline power from the Ancient God lineage. Provides ancient heritage bonuses.",
                List.of(
                        "Ancient God bloodline heritage",
                        "Ancestral power source"
                ),
                List.of("bloodline", "ancient_god", "ancestor", "heritage")
        ));


        register(CanonicalEntry.of(
                "I168_celestial_bloodline_ancestor", "Celestial Bloodline Ancestor", "仙界血脉之祖",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("IAC era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Celestial-tier bloodline ancestor power. Beyond mortal bloodline heritage.",
                List.of(
                        "Celestial bloodline heritage",
                        "Transcendent power source"
                ),
                List.of("bloodline", "celestial", "ancestor", "transcendent")
        ));


        register(CanonicalEntry.of(
                "I169_vermilion_bird_spirit", "Vermilion Bird Spirit", "朱雀之灵",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("throughout RI"), 5),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The spirit essence of the Vermilion Bird. Used for fire-based abilities and Vermilion Bird Mark.",
                List.of(
                        "Fire-based abilities",
                        "Vermilion Bird Mark power source"
                ),
                List.of("vermilion_bird", "spirit", "fire", "mark")
        ));


        register(CanonicalEntry.of(
                "I170_call_wind_summon_rain", "Call Wind Summon Rain", "呼风唤雨",
                CanonicalCategory.INVENTORY,
                Provenance.explicit("Renegade Immortal", List.of("Nascent Soul era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin obtained this item during his cultivation journey."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A magical item/technique for weather manipulation — calling wind and summoning rain.",
                List.of(
                        "Weather manipulation",
                        "Wind and rain control"
                ),
                List.of("weather", "wind", "rain", "elemental")
        ));

