// Generated by scripts/generate_registry_entries.py
// Append these register() calls to CanonicalTechniques.doBootstrap()


        register(CanonicalEntry.of(
                "T01_devouring_technique", "Devouring Technique", "吞噬之术",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("early RI"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A foundational absorption technique. Wang Lin used it to absorb spiritual energy, pills, and items.",
                List.of(
                        "Absorbs spiritual energy and items",
                        "Foundational absorption art"
                ),
                List.of("devouring", "absorption", "foundational")
        ));


        register(CanonicalEntry.of(
                "T03_fiend_transformation_art", "Fiend Transformation Art", "化魔之术",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Core Formation era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Transforms the user into a fiend/demon form. Increases combat power at the cost of cultivation stability.",
                List.of(
                        "Transforms into fiend form",
                        "Power boost with risk",
                        "Used by Wang Lin in desperate battles"
                ),
                List.of("transformation", "fiend", "demon", "combat")
        ));


        register(CanonicalEntry.of(
                "T09_yin_energy_detection", "Yin Energy Detection Technique", "阴气探测术",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("early RI"), 5),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Detects Yin energy in the environment. Essential for finding cultivation sites for the Underworld Ascension Method.",
                List.of(
                        "Detects Yin energy sources",
                        "Pairs with Underworld Ascension Method"
                ),
                List.of("detection", "yin", "sensing", "underworld")
        ));


        register(CanonicalEntry.of(
                "T16_mountains_crumble", "Mountains Crumble", "山崩",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Qi Condensation era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "An earth-type attack technique that causes the ground to collapse and crumble.",
                List.of(
                        "Earth-type attack",
                        "Ground collapse"
                ),
                List.of("earth", "attack", "destruction")
        ));


        register(CanonicalEntry.of(
                "T21_fog_transformation_thunder", "Fog Transformation Thunder Spell", "雾化雷术",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Foundation era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Transforms fog into thunder/lightning. An offensive spell combining mist and lightning elements.",
                List.of(
                        "Fog-to-thunder conversion",
                        "Combined mist + lightning offense"
                ),
                List.of("fog", "thunder", "transformation", "offense")
        ));


        register(CanonicalEntry.of(
                "T22_giant_thunder_stamp", "Giant Thunder Stamp", "大雷印",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Core Formation era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A large-scale thunder seal technique. Projects a giant stamp of thunder energy.",
                List.of(
                        "Large-scale thunder attack",
                        "Seal-type technique"
                ),
                List.of("thunder", "seal", "large_scale", "attack")
        ));


        register(CanonicalEntry.of(
                "T24_open_ancient_thunder_realm", "Open the Ancient Thunder Realm", "开古雷界",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Soul Formation era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Opens a passage to the Ancient Thunder Realm. Used for accessing thunder-type inheritances.",
                List.of(
                        "Opens Ancient Thunder Realm passage",
                        "Dimensional access technique"
                ),
                List.of("thunder", "realm", "dimension", "ancient")
        ));


        register(CanonicalEntry.of(
                "T31_rapid_spell_art_xu_decai", "Rapid Spell Art (Xu Decai)", "徐才快速法术",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Foundation era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A rapid-casting technique learned from Xu Decai. Enables near-instant spell incantations.",
                List.of(
                        "Rapid spell casting",
                        "Reduced incantation time",
                        "Learned from Xu Decai"
                ),
                List.of("speed", "casting", "spell", "xu_decai")
        ));


        register(CanonicalEntry.of(
                "T33_rapid_spell_technique", "Rapid Spell Technique", "快速施法术",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Core Formation era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Wang Lin's own improved rapid-casting technique. Builds on the Xu Decai method.",
                List.of(
                        "Improved rapid casting",
                        "Wang Lin's refinement"
                ),
                List.of("speed", "casting", "improvement")
        ));


        register(CanonicalEntry.of(
                "T34_body_fixation_art_xiangang", "Body Fixation Art (Xiang'ang)", "香冈定身术",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Foundation era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A body-fixation/immobilization technique. Learned or adapted from Xiang'ang.",
                List.of(
                        "Immobilizes targets",
                        "Body fixation"
                ),
                List.of("fixation", "immobilize", "control")
        ));


        register(CanonicalEntry.of(
                "T38_life_transformation_spell", "Life Transformation Spell", "化命术",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Nascent Soul era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A spell that transforms life force. Can convert life energy between forms.",
                List.of(
                        "Transforms life force",
                        "Life energy conversion"
                ),
                List.of("life", "transformation", "energy")
        ));


        register(CanonicalEntry.of(
                "T41_slaughter_immortal_art", "Slaughter Immortal Art", "杀仙术",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Soul Formation era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A killing art specialized against immortals/cultivators. Part of Wang Lin's offensive arsenal.",
                List.of(
                        "Anti-cultivator killing art",
                        "Slaughter-focused"
                ),
                List.of("slaughter", "killing", "immortal", "offense")
        ));


        register(CanonicalEntry.of(
                "T44_god_slaying_seal_origin", "God-Slaying Seal Origin", "诛神印本源",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("late RI"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The origin/essence of the God-Slaying Seal technique. The fundamental principle behind the seal.",
                List.of(
                        "Origin technique of God-Slaying Seal",
                        "Fundamental seal principle"
                ),
                List.of("god_slaying", "seal", "origin", "fundamental")
        ));


        register(CanonicalEntry.of(
                "T50_life_seizing_hex", "Life-Seizing Hex", "夺命咒",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Nascent Soul era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A hex that seizes the target's life force. Used in combat to weaken or kill.",
                List.of(
                        "Seizes target's life force",
                        "Hex-type technique"
                ),
                List.of("hex", "life", "seizing", "combat")
        ));


        register(CanonicalEntry.of(
                "T55_nine_mysterious_transformations", "Nine Mysterious Transformations", "九玄变化",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Soul Formation era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A transformation art with 9 forms. Allows the user to assume different shapes and properties.",
                List.of(
                        "9 transformation forms",
                        "Shape-shifting art"
                ),
                List.of("transformation", "nine", "mysterious", "shape")
        ));


        register(CanonicalEntry.of(
                "T90_ji_realm_execution", "Ji Realm Execution", "极境处决",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Core Formation era"), 5),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "An execution technique powered by the Ji Realm divine sense. Instantly kills targets below a certain realm.",
                List.of(
                        "Ji Realm-powered instant kill",
                        "Realm-gated execution"
                ),
                List.of("ji_realm", "execution", "killing", "divine_sense")
        ));


        register(CanonicalEntry.of(
                "T96_eyes_suppressing_world", "Eyes Suppressing World", "眼压天地",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Soul Formation era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A gaze-based technique that suppresses everything in the user's field of vision. Uses divine sense projection.",
                List.of(
                        "Gaze-based suppression",
                        "Divine sense projection"
                ),
                List.of("gaze", "suppression", "divine_sense", "domain")
        ));


        register(CanonicalEntry.of(
                "T100_ice_imitation_dongling_pool", "Ice Imitation (Dongling Pool)", "冰之模仿（东灵池）",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Foundation era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "An ice-type technique imitated from the Dongling Pool. Creates and manipulates ice.",
                List.of(
                        "Ice creation and manipulation",
                        "Imitated technique"
                ),
                List.of("ice", "imitation", "dongling", "elemental")
        ));


        register(CanonicalEntry.of(
                "T105_nine_drops_poison_miao_yin", "Nine Drops Poison (Miao Yin)", "九滴毒（妙音）",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Nascent Soul era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A poison technique from Miao Yin. Uses nine drops of concentrated poison.",
                List.of(
                        "Poison attack",
                        "Nine-drop concentration",
                        "Miao Yin origin"
                ),
                List.of("poison", "miao_yin", "nine_drops")
        ));


        register(CanonicalEntry.of(
                "T110_three_life_spell", "Three-Life Spell", "三世咒",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("late RI"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A spell that spans three lives/incarnations. Related to the Samsara Dao.",
                List.of(
                        "Spans three incarnations",
                        "Samsara-linked"
                ),
                List.of("samsara", "three_lives", "reincarnation", "spell")
        ));


        register(CanonicalEntry.of(
                "T135_defying_thunder", "Defying Thunder", "逆雷",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Soul Formation era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A heaven-defying thunder technique. Goes beyond normal thunder cultivation limits.",
                List.of(
                        "Beyond normal thunder limits",
                        "Heaven-defying property"
                ),
                List.of("thunder", "defying", "heaven_defying")
        ));


        register(CanonicalEntry.of(
                "T140_nine_revolutions_refining", "Nine Revolutions Refining Immortal", "九转炼仙",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Nascent Soul era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A nine-revolution refining technique for immortal-grade items. Part of Wang Lin's crafting arts.",
                List.of(
                        "Nine-revolution refining process",
                        "Immortal-grade crafting"
                ),
                List.of("refining", "crafting", "nine_revolutions", "immortal")
        ));


        register(CanonicalEntry.of(
                "T145_extreme_fire_dao_imitation", "Extreme Fire Dao Imitation", "极火道模仿",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Soul Formation era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "An imitation of the Extreme Fire Dao. A fire-type technique模仿 from observation.",
                List.of(
                        "Fire Dao imitation",
                        "Learned through observation"
                ),
                List.of("fire", "dao", "imitation", "extreme")
        ));


        register(CanonicalEntry.of(
                "AT07_store_all_ji_thunder", "Store All Ji Thunder", "储极雷",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Ch. ~1400"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The 7th accompanying thunder — stores all Ji Realm thunder energy. The culmination of the 9-thunder series.",
                List.of(
                        "7th of 9 accompanying thunders",
                        "Stores all Ji thunder energy",
                        "Culmination of thunder series"
                ),
                List.of("thunder", "accompanying", "ji_realm", "storage")
        ));


        register(CanonicalEntry.of(
                "OS04_karma_print", "Karma Print — 4th Original Spell", "因果印·第四元神术",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("late RI"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The 4th of Wang Lin's Original Spells. A karma-based sealing print that binds cause and effect.",
                List.of(
                        "4th Original Spell",
                        "Karma-based sealing",
                        "Binds cause and effect"
                ),
                List.of("original_spell", "karma", "seal", "fourth")
        ));


        register(CanonicalEntry.of(
                "OS05_life_death_seal", "Life and Death Seal — 5th Original Spell", "生死印·第五元神术",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("late RI"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The 5th of Wang Lin's Original Spells. Controls life and death of targets within range.",
                List.of(
                        "5th Original Spell",
                        "Life-death control",
                        "Domain-type authority"
                ),
                List.of("original_spell", "life_death", "seal", "fifth")
        ));


        register(CanonicalEntry.of(
                "OS06_true_false_eternal_seal", "True and False Eternal Seal — 6th Original Spell", "真假永恒印·第六元神术",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("late RI"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The 6th of Wang Lin's Original Spells. Distinguishes truth from falsehood; creates an eternal seal of distinction.",
                List.of(
                        "6th Original Spell",
                        "Truth-falsehood distinction",
                        "Eternal sealing"
                ),
                List.of("original_spell", "true_false", "eternal", "seal", "sixth")
        ));


        register(CanonicalEntry.of(
                "I138_life_death_domain", "Life and Death Domain", "生死域",
                CanonicalCategory.DOMAIN,
                Provenance.explicit("Renegade Immortal", List.of("late RI"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A domain that controls life and death within its area. One of Wang Lin's powerful domain-type abilities.",
                List.of(
                        "Life-death control within domain",
                        "Area-of-effect authority"
                ),
                List.of("domain", "life_death", "area", "authority")
        ));


        register(CanonicalEntry.of(
                "I153_blood_lines_rules", "Blood Lines Rules / Restriction Essence", "血脉规则·禁制本源",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("late RI"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The essence of restriction art combined with bloodline rules. Represents the ultimate fusion of restriction + bloodline.",
                List.of(
                        "Fusion of restriction + bloodline",
                        "Ultimate restriction art form"
                ),
                List.of("restriction", "bloodline", "essence", "fusion")
        ));


        register(CanonicalEntry.of(
                "T136_bloodline_thunder", "Bloodline Thunder", "血脉之雷",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("late RI"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Thunder technique powered by bloodline energy. Combines Ancient God bloodline with thunder cultivation.",
                List.of(
                        "Bloodline-powered thunder",
                        "Ancient God + thunder fusion"
                ),
                List.of("thunder", "bloodline", "ancient_god", "fusion")
        ));


        register(CanonicalEntry.of(
                "T95_flame_dragon", "Flame Dragon", "火龙",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Nascent Soul era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Summons or transforms into a flame dragon. A fire-type offensive technique.",
                List.of(
                        "Flame dragon summon/transformation",
                        "Fire-type offense"
                ),
                List.of("fire", "dragon", "summon", "offense")
        ));


        register(CanonicalEntry.of(
                "T150_nine_star_ancient_god", "Nine-Star Ancient God Power", "九星古神之力",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("late RI"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The power of the nine-star Ancient God. Represents peak Ancient God Tactic cultivation.",
                List.of(
                        "Nine-star Ancient God power",
                        "Peak Ancient God Tactic"
                ),
                List.of("ancient_god", "nine_star", "power", "peak")
        ));


        register(CanonicalEntry.of(
                "T155_extreme_land_sky_life", "Extreme Land Sky Life Dao", "极地天生命道",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("IAC era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "An extreme Dao combining land, sky, and life concepts. One of Wang Lin's late-stage Dao comprehensions.",
                List.of(
                        "Combines land + sky + life",
                        "Late-stage Dao comprehension"
                ),
                List.of("dao", "extreme", "land", "sky", "life")
        ));


        register(CanonicalEntry.of(
                "T160_mother_child_dao", "Mother-Child Dao (Withered)", "母子道（枯萎）",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("IAC era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A Mother-Child Dao technique in a withered/state. Represents a Dao that has been diminished.",
                List.of(
                        "Mother-Child Dao variant",
                        "Withered/diminished state"
                ),
                List.of("dao", "mother_child", "withered")
        ));


        register(CanonicalEntry.of(
                "T165_wither_dao_pair", "Wither Dao Pair", "枯道对",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("IAC era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A pair of wither-type Dao techniques. Used together for enhanced effect.",
                List.of(
                        "Paired wither Dao techniques",
                        "Enhanced when combined"
                ),
                List.of("dao", "wither", "pair", "combined")
        ));


        register(CanonicalEntry.of(
                "E08_taichu_essence", "Taichu Essence", "太初本源",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("late RI"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The Taichu (Primordial Beginning) essence. One of the origin essences Wang Lin comprehended.",
                List.of(
                        "Origin essence comprehension",
                        "Taichu/Primordial concept"
                ),
                List.of("essence", "taichu", "origin", "primordial")
        ));


        register(CanonicalEntry.of(
                "E09_miemie_essence", "Miemie Essence", "灭灭本源",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("late RI"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The Miemie (Annihilation-Extinction) essence. One of the origin essences Wang Lin comprehended.",
                List.of(
                        "Origin essence comprehension",
                        "Annihilation-Extinction concept"
                ),
                List.of("essence", "miemie", "annihilation", "extinction")
        ));


        register(CanonicalEntry.of(
                "T170_cultivator_dao_avatar", "Cultivator Dao Avatar", "修仙分身道",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Nascent Soul era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The technique of creating a cultivator clone/avatar that can cultivate independently.",
                List.of(
                        "Clone/avatar creation technique",
                        "Independent cultivation by avatar"
                ),
                List.of("clone", "avatar", "cultivation", "separation")
        ));


        register(CanonicalEntry.of(
                "B01_ancient_god_body", "Ancient God Body", "古神之体",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Ch. 190+"), 5),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The physical body transformation into an Ancient God form via the Ancient God Tactic.",
                List.of(
                        "Ancient God body transformation",
                        "Outer-body cultivation result"
                ),
                List.of("ancient_god", "body", "transformation")
        ));


        register(CanonicalEntry.of(
                "B02_undying_ancient_body", "Undying Ancient Body", "不古道身",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("late RI"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "The Undying Ancient God body form. A higher evolution of the Ancient God Body.",
                List.of(
                        "Undying Ancient God form",
                        "Higher body evolution"
                ),
                List.of("ancient_god", "undying", "body", "evolution")
        ));


        register(CanonicalEntry.of(
                "companion_xu_liguo_devil", "Xu Liguo (Devil Form)", "许立国（魔头形态）",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("early RI"), 5),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Xu Liguo's devil form — one of Wang Lin's primary companions. A sentient devil head with personality.",
                List.of(
                        "Sentient devil companion",
                        "Comic relief + combat support",
                        "Loyal but cowardly personality"
                ),
                List.of("companion", "devil", "xu_liguo", "sentient")
        ));


        register(CanonicalEntry.of(
                "companion_xu_liguo_first", "Xu Liguo (First Form)", "许立国（初始形态）",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("early RI"), 5),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Xu Liguo's first/devouring form before full awakening.",
                List.of(
                        "Initial devil form",
                        "Devouring capability"
                ),
                List.of("companion", "devil", "xu_liguo", "initial")
        ));


        register(CanonicalEntry.of(
                "companion_xie_qing_guard", "Xie Qing (Immortal Guard)", "谢青（仙卫）",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Soul Formation era"), 4),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "Xie Qing, one of Wang Lin's immortal guards. A powerful combat companion.",
                List.of(
                        "Immortal guard companion",
                        "Combat specialist"
                ),
                List.of("companion", "guard", "xie_qing", "combat")
        ));


        register(CanonicalEntry.of(
                "I130_tattoo_talisman_speed", "Tattoo Talisman (Speed Boost)", "刺青符（加速）",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Core Formation era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A tattoo talisman that boosts movement speed. Applied to the body.",
                List.of(
                        "Movement speed boost",
                        "Body-applied talisman"
                ),
                List.of("talisman", "tattoo", "speed", "movement")
        ));


        register(CanonicalEntry.of(
                "I20_short_sword_seals_shadows", "Short Sword (Seals Shadows)", "短剑·封影",
                CanonicalCategory.TECHNIQUES,
                Provenance.explicit("Renegade Immortal", List.of("Foundation era"), 3),
                OwnershipState.WANG_LIN_OWNED,
                Transferability.selfCreated("Wang Lin developed or obtained this technique during his cultivation."),
                Demonstrability.CAN_DEMONSTRATE_FULLY,
                "A short sword that can seal shadows. One of Wang Lin's early weapons.",
                List.of(
                        "Shadow-sealing capability",
                        "Early weapon"
                ),
                List.of("sword", "shadow", "seal", "weapon")
        ));

