// Generated by scripts/generate_registry_entries.py
// Append these m.put() lines to WangLinItems.java bridge map

        m.put("five_sword_sheaths", "I05_five_sword_sheaths");
        m.put("bronze_mirror_time_domain", "I37_bronze_mirror");
        m.put("soul_flag_soul_refining_sect", "I49_soul_flag_soul_refining_sect");
        m.put("seven_colored_nails", "I82_seven_colored_nails");
        m.put("celestial_spirit_clock", "I76_celestial_spirit_clock");
        m.put("dot_immortal_pen", "I90_dot_immortal_pen");
        m.put("golden_print", "I92_golden_print");
        m.put("beast_skin_tattoo", "I115_beast_skin_tattoo");
        m.put("three_ink_stones_restriction", "I03_three_ink_stones");
        m.put("infant_skull_da_yi", "I100_infant_skull_da_yi");
        m.put("three_battle_scrolls_zhan", "I65_three_battle_scrolls");
        m.put("human_shaped_armor_green_bull", "I40_human_shaped_armor");
        m.put("dream_dao_mirror", "I160_dream_dao_mirror");
        m.put("red_lightning_ji_realm", "AT01_red_lightning_ji_realm");
        m.put("blood_nascent_soul_seven_colored", "I60_blood_nascent_soul_seven_colored");
        m.put("ancient_bloodline_ancestor", "I167_ancient_bloodline_ancestor");
        m.put("celestial_bloodline_ancestor", "I168_celestial_bloodline_ancestor");
        m.put("vermilion_bird_spirit", "I169_vermilion_bird_spirit");
        m.put("call_wind_summon_rain_magic_arsenal", "I170_call_wind_summon_rain");
        m.put("devouring_technique", "T01_devouring_technique");
        m.put("fiend_transformation_art", "T03_fiend_transformation_art");
        m.put("yin_energy_detection", "T09_yin_energy_detection");
        m.put("mountains_crumble", "T16_mountains_crumble");
        m.put("fog_transformation_thunder_spell", "T21_fog_transformation_thunder");
        m.put("giant_thunder_stamp", "T22_giant_thunder_stamp");
        m.put("open_ancient_thunder_realm", "T24_open_ancient_thunder_realm");
        m.put("rapid_spell_art_xu_decai", "T31_rapid_spell_art_xu_decai");
        m.put("rapid_spell_technique", "T33_rapid_spell_technique");
        m.put("body_fixation_art_xiangang", "T34_body_fixation_art_xiangang");
        m.put("life_transformation_spell", "T38_life_transformation_spell");
        m.put("slaughter_immortal_art", "T41_slaughter_immortal_art");
        m.put("god_slaying_seal_origin", "T44_god_slaying_seal_origin");
        m.put("life_seizing_hex", "T50_life_seizing_hex");
        m.put("nine_mysterious_transformations", "T55_nine_mysterious_transformations");
        m.put("ji_realm_execution", "T90_ji_realm_execution");
        m.put("eyes_suppressing_world", "T96_eyes_suppressing_world");
        m.put("ice_imitation_dongling_pool", "T100_ice_imitation_dongling_pool");
        m.put("nine_drops_poison_miao_yin", "T105_nine_drops_poison_miao_yin");
        m.put("three_life_spell_william", "T110_three_life_spell");
        m.put("defying_thunder", "T135_defying_thunder");
        m.put("nine_revolutions_refining_immortal", "T140_nine_revolutions_refining");
        m.put("extreme_fire_dao_imitation", "T145_extreme_fire_dao_imitation");
        m.put("store_all_ji_thunder", "AT07_store_all_ji_thunder");
        m.put("karma_print", "OS04_karma_print");
        m.put("life_death_seal", "OS05_life_death_seal");
        m.put("true_false_eternal_seal", "OS06_true_false_eternal_seal");
        m.put("life_death_domain", "I138_life_death_domain");
        m.put("blood_lines_rules_restriction", "I153_blood_lines_rules");
        m.put("bloodline_thunder", "T136_bloodline_thunder");
        m.put("flame_dragon", "T95_flame_dragon");
        m.put("nine_star_ancient_god_power", "T150_nine_star_ancient_god");
        m.put("extreme_land_sky_life_dao", "T155_extreme_land_sky_life");
        m.put("mother_child_dao_withered", "T160_mother_child_dao");
        m.put("wither_dao_pair", "T165_wither_dao_pair");
        m.put("taichu_essence", "E08_taichu_essence");
        m.put("miemie_essence", "E09_miemie_essence");
        m.put("cultivator_dao_avatar", "T170_cultivator_dao_avatar");
        m.put("ancient_god_body", "B01_ancient_god_body");
        m.put("undying_ancient_body_version", "B02_undying_ancient_body");
        m.put("xu_liguo_devil", "companion_xu_liguo_devil");
        m.put("devil_xu_liguo_first", "companion_xu_liguo_first");
        m.put("xie_qing_immortal_guard", "companion_xie_qing_guard");
        m.put("tattoo_talisman_speed_boost", "I130_tattoo_talisman_speed");
        m.put("short_sword_seals_shadows", "I20_short_sword_seals_shadows");
        m.put("burning_realm_ancient_umbrella_dao", "I46_blue_umbrella"); // DAO variant — bridges to base item
        m.put("li_guang_heaven_shattering_bow", "I47_silver_dragon_star_compass"); // DAO variant — bridges to base item
        m.put("li_guang_heaven_shattering_bow_dao", "I47_silver_dragon_star_compass"); // DAO variant — bridges to base item
        m.put("seven_colored_lance_dao", "I48_soul_lasser_karma_whip"); // DAO variant — bridges to base item
        m.put("seven_colored_lance_dao_spell", "I48_soul_lasser_karma_whip"); // DAO variant — bridges to base item
