package dev.ergenverse.simulation.cognition;

import java.util.ArrayList;
import java.util.List;

/**
 * ActionOption — a single possible action generated by the {@link Planner}.
 *
 * <p>An ActionOption carries trait alignments (which personality traits it
 * satisfies or violates), expected success probability, reward, risk, and
 * karmic cost. The {@link PersonalityModel#scoreOption} function combines
 * these with the actor's personality curves to produce a single decision
 * score.
 *
 * <p>Canon-aligned action set (RI + canon audit):
 * trade, steal, kill_owner, offer_favor, wait, explore, fight, flee, hide,
 * call_help, meditate, breakthrough, study_formation, break_formation,
 * craft_talisman, craft_pill, deceive, investigate, seek_dao, take_revenge,
 * honor_promise, defend_territory, gather_herb, gather_qi, submit,
 * corrupt_target, offer_disciple, accept_disciple, leave_sect, found_sect.
 */
public final class ActionOption {

    public enum ActionId {
        TRADE, STEAL, KILL_OWNER, OFFER_FAVOR, WAIT, EXPLORE,
        FIGHT, FLEE, HIDE, CALL_HELP, MEDITATE, BREAKTHROUGH,
        STUDY_FORMATION, BREAK_FORMATION, CRAFT_TALISMAN, CRAFT_PILL,
        DECEIVE, INVESTIGATE, SEEK_DAO, TAKE_REVENGE, HONOR_PROMISE,
        DEFEND_TERRITORY, GATHER_HERB, GATHER_QI, SUBMIT,
        CORRUPT_TARGET, OFFER_DISCIPLE, ACCEPT_DISCIPLE, LEAVE_SECT, FOUND_SECT
    }

    public final ActionId id;
    public final String label;
    public final CognitionGoal.Category category;

    /** Map of personality trait name → alignment value (−1..+1). */
    public final java.util.Map<String, Double> traitAlignments = new java.util.HashMap<>();

    public double successProbability;  // 0..1
    public double reward;              // 0..1 utility
    public double risk;                // 0..1
    public double karmicCost;          // 0..1 — karma gained by taking this action

    public ActionOption(ActionId id, String label, CognitionGoal.Category category) {
        this.id = id;
        this.label = label;
        this.category = category;
    }

    /** Builder-style setter for trait alignments. */
    public ActionOption withTrait(String trait, double alignment) {
        traitAlignments.put(trait, alignment);
        return this;
    }

    public ActionOption withSuccess(double p)   { this.successProbability = p; return this; }
    public ActionOption withReward(double r)    { this.reward = r; return this; }
    public ActionOption withRisk(double r)      { this.risk = r; return this; }
    public ActionOption withKarma(double k)     { this.karmicCost = k; return this; }

    /** Build the canonical RI action set used by the Planner. */
    public static List<ActionOption> canonicalSet() {
        List<ActionOption> opts = new ArrayList<>();
        opts.add(new ActionOption(ActionId.TRADE,            "Trade",            CognitionGoal.Category.TRADE));
        opts.add(new ActionOption(ActionId.STEAL,            "Steal",            CognitionGoal.Category.GATHER_RESOURCE));
        opts.add(new ActionOption(ActionId.KILL_OWNER,       "Kill Owner",       CognitionGoal.Category.KILL));
        opts.add(new ActionOption(ActionId.OFFER_FAVOR,      "Offer Favor",      CognitionGoal.Category.OFFER_FAVOR));
        opts.add(new ActionOption(ActionId.WAIT,             "Wait",             CognitionGoal.Category.WAIT));
        opts.add(new ActionOption(ActionId.EXPLORE,          "Explore",          CognitionGoal.Category.EXPLORE));
        opts.add(new ActionOption(ActionId.FIGHT,            "Fight",            CognitionGoal.Category.DEFEND));
        opts.add(new ActionOption(ActionId.FLEE,             "Flee",             CognitionGoal.Category.FLEE));
        opts.add(new ActionOption(ActionId.HIDE,             "Hide",             CognitionGoal.Category.HIDE));
        opts.add(new ActionOption(ActionId.CALL_HELP,        "Call for Help",    CognitionGoal.Category.CALL_HELP));
        opts.add(new ActionOption(ActionId.MEDITATE,         "Meditate",         CognitionGoal.Category.MEDITATE));
        opts.add(new ActionOption(ActionId.BREAKTHROUGH,     "Breakthrough",     CognitionGoal.Category.BREAKTHROUGH));
        opts.add(new ActionOption(ActionId.STUDY_FORMATION,  "Study Formation",  CognitionGoal.Category.STUDY));
        opts.add(new ActionOption(ActionId.BREAK_FORMATION,  "Break Formation",  CognitionGoal.Category.BREAK_FORMATION));
        opts.add(new ActionOption(ActionId.CRAFT_TALISMAN,   "Craft Talisman",   CognitionGoal.Category.CRAFT));
        opts.add(new ActionOption(ActionId.CRAFT_PILL,       "Craft Pill",       CognitionGoal.Category.CRAFT));
        opts.add(new ActionOption(ActionId.DECEIVE,          "Deceive",          CognitionGoal.Category.DECEIVE));
        opts.add(new ActionOption(ActionId.INVESTIGATE,      "Investigate",      CognitionGoal.Category.INVESTIGATE));
        opts.add(new ActionOption(ActionId.SEEK_DAO,         "Seek Dao",         CognitionGoal.Category.SEEKING_DAO));
        opts.add(new ActionOption(ActionId.TAKE_REVENGE,     "Take Revenge",     CognitionGoal.Category.KILL));
        opts.add(new ActionOption(ActionId.HONOR_PROMISE,    "Honor Promise",    CognitionGoal.Category.KEEP_PROMISE));
        opts.add(new ActionOption(ActionId.DEFEND_TERRITORY, "Defend Territory", CognitionGoal.Category.DEFEND_TERRITORY));
        opts.add(new ActionOption(ActionId.GATHER_HERB,      "Gather Herb",      CognitionGoal.Category.GATHER_RESOURCE));
        opts.add(new ActionOption(ActionId.GATHER_QI,        "Gather Qi",        CognitionGoal.Category.GATHER_RESOURCE));
        opts.add(new ActionOption(ActionId.SUBMIT,           "Submit",           CognitionGoal.Category.SUBMIT));
        opts.add(new ActionOption(ActionId.CORRUPT_TARGET,   "Corrupt Target",   CognitionGoal.Category.CORRUPT));
        opts.add(new ActionOption(ActionId.OFFER_DISCIPLE,   "Offer to Take Disciple", CognitionGoal.Category.LEGACY));
        opts.add(new ActionOption(ActionId.ACCEPT_DISCIPLE,  "Accept Disciple",  CognitionGoal.Category.LEGACY));
        opts.add(new ActionOption(ActionId.LEAVE_SECT,       "Leave Sect",       CognitionGoal.Category.OTHER));
        opts.add(new ActionOption(ActionId.FOUND_SECT,       "Found Sect",       CognitionGoal.Category.POLITICS));
        return opts;
    }

    @Override
    public String toString() {
        return "Action[" + label + " success=" + successProbability
                + " reward=" + reward + " risk=" + risk + " karma=" + karmicCost + "]";
    }
}
