package dev.ergenverse.wanglin.ai.reasoning;

/**
 * GiftingOutcome — the three possible responses Wang Lin can give to a gift
 * request, per PROJECT_MASTER.md §4.4.
 *
 * <p>The outcome is decided by the {@link WangLinReasoningEngine} based on the
 * aggregate score of the six {@link GiftingFactor}s:
 * <ul>
 *   <li><b>YES</b> — aggregate score ≥ 0.7. Wang Lin gives the replica
 *       immediately (the true body sends it). Happens when necessity +
 *       usefulness are high and safety is acceptable.</li>
 *   <li><b>NO_FOR_NOW</b> — aggregate score &lt; 0.3. "Your affinity with me
 *       isn't enough yet. Come back when you've grown." Never angry, just
 *       honest. The player learns what they need to improve. This is the
 *       anti-content-dispenser guarantee — Wang Lin refuses more often than
 *       he agrees.</li>
 *   <li><b>CHALLENGE</b> — 0.3 ≤ aggregate score &lt; 0.7. Wang Lin offers a
 *       crazy, thematically-tied challenge: "I'll give you the Karma Whip —
 *       but first, survive three days in Mosquito Valley without any
 *       cultivation." Generated by {@link ChallengeGenerator}. This turns a
 *       rejection into gameplay.</li>
 * </ul>
 *
 * <h2>Wang Lin is NOT a content dispenser (§4.4 ⚠ WARNING)</h2>
 * <p>{@link #NO_FOR_NOW} exists precisely so Wang Lin can refuse. If players
 * sometimes leave disappointed but understanding why, you've captured his
 * character correctly. The temptation to make him an endgame reward vendor
 * MUST be resisted. He gives because he sees the player's path — not because
 * the player asked.
 */
public enum GiftingOutcome {
    YES(
            "Yes",
            "Wang Lin gives the replica immediately. The true body sends it.",
            "%s"
    ),
    NO_FOR_NOW(
            "No (for now)",
            "Wang Lin declines honestly. The player learns what they need to improve.",
            "Wang Lin says: \"Your affinity with me isn't enough yet. Come back when you've grown. %s\""
    ),
    CHALLENGE(
            "Challenge",
            "Wang Lin offers a thematically-tied challenge. Rejection becomes gameplay.",
            "Wang Lin says: \"I will consider it — but first, prove yourself. %s\""
    );

    /** Short label (e.g. "Yes", "No (for now)", "Challenge"). */
    public final String label;

    /** What this outcome means, in canon-grounded terms. */
    public final String description;

    /**
     * The dialogue template spoken to the player. Contains a single %s
     * placeholder for the outcome-specific content (the granted item name for
     * YES; the improvement hint for NO_FOR_NOW; the challenge description for
     * CHALLENGE).
     */
    public final String playerMessageTemplate;

    GiftingOutcome(String label, String description, String playerMessageTemplate) {
        this.label = label;
        this.description = description;
        this.playerMessageTemplate = playerMessageTemplate;
    }

    /**
     * Whether this outcome grants the requested item to the player.
     * Only {@link #YES} grants; {@link #NO_FOR_NOW} and {@link #CHALLENGE}
     * do not (CHALLENGE grants only after the challenge is completed, handled
     * by a separate system).
     */
    public boolean isItemGranted() {
        return this == YES;
    }

    /** Whether this outcome ends the interaction without granting the item now. */
    public boolean isRefusalForNow() {
        return this == NO_FOR_NOW || this == CHALLENGE;
    }
}
